### ISSUE TITLE
Stuck downloading m3u8 from shahid.mbc.net

### ISSUE THREAD

**Issue by kim0** [rg3/youtube-dl#10195]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.30*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.30**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

youtube-dl is stuck (hung) downloading from shahid.mbc.net
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v 'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html' -F
[debug] System config: []
[debug] User config: [u'--no-mtime']
[debug] Command-line args: [u'-v', u'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html', u'-F']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.30
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Shahid] 142785: Downloading player JSON
[Shahid] 142785: Downloading m3u8 information
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl is just hung (stuck) trying to download from shahid.mbc.net (stuck trying to download m3u8 information as above). This was working fine a few days ago, so some new change (either code, or on the website) caused the breakage!

**Comment by mshmomo** [comment]
Hello
I followup all the instruction but I have error 
`C:\Users\Mostafa\Desktop\youtube-dl-master>youtube-dl -v 'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html' -F
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', "'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html'", '-F']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2016.08.12
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] وعد-الموسم-1-الحلقة-10: Requesting header
WARNING: Could not send HEAD request to http://'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html': <urlopen error [Errno 11001] getaddrinfo failed>
[generic] وعد-الموسم-1-الحلقة-10: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\YoutubeDL.py", line 1996, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpzyhyyrce\build\youtube_dl\utils.py", line 840, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open`

I didnt install python on my device so I dont know if this make the problem or not
waiting your answer.

**Comment by remitamine** [comment]
it's working without problem.
```
youtube-dl 'https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html'
[Shahid] 142785: Downloading player JSON
[Shahid] 142785: Downloading m3u8 information
[Shahid] 142785: Downloading video JSON
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 256
[download] Destination: وعد الموسم 1 الحلقة 10-142785.mp4
[download]   0.1% of ~744.34MiB at 189.30KiB/s ETA 01:13:16
```
@mshmomo in windows, you have to use the double quotes:
`youtube-dl "https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html"`

**Comment by mshmomo** [comment]
Thanks for quick replay
I copy your code but I have another problem

> C:\Users\Mostafa\Desktop\youtube-dl-master>youtube-dl "https://shahid.mbc.net/ar/episode/142785/%D9%88%D8%B9%D8%AF-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-10.html"
[Shahid] 142785: Downloading player JSON
[Shahid] 142785: Downloading m3u8 information
[Shahid] 142785: Downloading video JSON
[download] Destination: وعد الموسم 1 الحلقة 10-142785.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

**Comment by remitamine** [comment]
> ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

as error said you have to install ffmpeg or avconv.

**Comment by mshmomo** [comment]
I have ffmpeg on my pc and I added it like this way
http://s9.postimg.org/g0w7oj4an/screenshot_159.png
but still not working
can you please help me with this?

**Comment by remitamine** [comment]
i didn't try to use it in windows before but i think that puttinng it in `PATH` can help.
you can follow instruction in http://www.wikihow.com/Install-FFmpeg-on-Windows.

**Comment by apolikamixitos** [comment]
@mshmomo : You have to add the directory where the binaries are placed to the PATH Environment Variable : "set PATH=%PATH%;(your new directory);"

**Comment by mshmomo** [comment]
Thanks so much everyone for help
its work now :+1:

**Comment by kim0** [comment]
I confirm it's working well for me now! Thanks

**Comment by ehaab** [comment]
Kim0 do i need to have plus account to download those episodes?

**Comment by kim0** [comment]
@ehaab I don't no .. and they worked for me (although some other episodes need it I think)

**Comment by DarbyCrash** [comment]
This plugin is not working. Login fail.

`youtube-dl https://shahid.mbc.net/ar/series/%D9%85%D8%B1%D8%A7%D9%8A%D8%A7-2011-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-1/episode-90511 -u xxx@xxx.xxx -p xxxxxxxxxxxx
[Shahid] Logging in
WARNING: [Shahid] None: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to download JSON metadata: HTTP Error 405: Method Not Allowed (caused by <HTTPError 405: 'Method Not Allowed'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by remitamine** [comment]
works for free content, if you're trying to download premium content than try to [use cookies](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) if it doesn't work than open a new issue.
