### ISSUE TITLE
EXTRACTING MP3s FROM A YOUTUBE PLAYLIST NOT WORKING

### ISSUE THREAD

**Issue by ssjc02** [rg3/youtube-dl#10312]
It only downloads the first song and then gets stuck at "Deleting original file"

![terminal](https://cloud.githubusercontent.com/assets/15344555/17627537/4116f848-60ba-11e6-911d-61889defc221.png)
![ev](https://cloud.githubusercontent.com/assets/15344555/17627569/61b56774-60ba-11e6-8e13-8da0cb79a48e.png)

**Comment by yan12125** [comment]
You need to enclose the URL in single or double quotes. See [this FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for more information.

By the way, please paste text outputs instead of screenshots so that others can copy and paste your command easily.

**Comment by ssjc02** [comment]
Worked like a charm. Thank you.
