### ISSUE TITLE
I can not download Previous episodes in CR

### ISSUE THREAD

**Issue by exborn** [rg3/youtube-dl#10513]

**Comment by exborn** [comment]
D:\CR-Rip>youtube-dl.exe "http://www.crunchyroll.com/fatekaleid-liner-prisma-ill
ya/episode-1-city-fading-to-silver-715497" -f 720p --all-subs --write-sub --sub-
format ass --embed-subs --verbose -u xxxxxx -p xxxxx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.crunchyroll.com/fatekaleid-liner-prisma-
illya/episode-1-city-fading-to-silver-715497', '-f', '720p', '--all-subs', '--wr
ite-sub', '--sub-format', 'ass', '--embed-subs', '--verbose', '-u', 'PRIVATE', '
-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81154-gfb91143, ffprobe N-81154-gfb91143, rtmpdum
p 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 715497: Downloading webpage
[Crunchyroll] 715497: Downloading media info for 360p
[Crunchyroll] 715497: Downloading m3u8 information
[Crunchyroll] 715497: Downloading media info for 480p
[Crunchyroll] 715497: Downloading m3u8 information
[Crunchyroll] 715497: Downloading media info for 720p
[Crunchyroll] 715497: Downloading m3u8 information
[Crunchyroll] 715497: Downloading media info for 1080p
[Crunchyroll] 715497: Downloading m3u8 information
[Crunchyroll] 715497: Downloading media info
[Crunchyroll] 715497: Downloading subtitles for English (US)
[Crunchyroll] 715497: Downloading subtitles for Español
[Crunchyroll] 715497: Downloading subtitles for Español (España)
[Crunchyroll] 715497: Downloading subtitles for Français (France)
[Crunchyroll] 715497: Downloading subtitles for Português (Brasil)
[Crunchyroll] 715497: Downloading subtitles for Italiano
[Crunchyroll] 715497: Downloading subtitles for Deutsch
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\YoutubeDL.py", line 702, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\YoutubeDL.py", line 748, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\YoutubeDL.py", line 1424, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available

D:\CR-Rip>

**Comment by dstftw** [comment]
>ERROR: requested format not available

There is no format `720p` exist. `-F` to list formats.

**Comment by dilworks** [comment]
The format DOES exist, but the format identifiers have now changed to video-specific IDs:

`tomman@m24legacy:~/temp$ youtube-dl --username USER -F http://www.crunchyroll.com/fatekaleid-liner-prisma-illya/episode-5-the-little-lady-attacks-715505
Type account password and press [Return]: 
[Crunchyroll] Logging in
[Crunchyroll] 715505: Downloading webpage
[Crunchyroll] 715505: Downloading media info for 360p
[Crunchyroll] 715505: Downloading m3u8 information
[Crunchyroll] 715505: Downloading media info for 480p
[Crunchyroll] 715505: Downloading m3u8 information
[Crunchyroll] 715505: Downloading media info for 720p
[Crunchyroll] 715505: Downloading m3u8 information
[Crunchyroll] 715505: Downloading media info for 1080p
[Crunchyroll] 715505: Downloading m3u8 information
[Crunchyroll] 715505: Downloading media info
[info] Available formats for 715505:
format code  extension  resolution note
hls-meta-0   mp4        multiple   Quality selection URL 
hls-meta-1   mp4        multiple   Quality selection URL 
hls-meta-2   mp4        multiple   Quality selection URL 
hls-meta-3   mp4        multiple   Quality selection URL 
hls-535      mp4        640x360     535k , avc1.4d001e, mp4a.40.2
hls-732      mp4        848x480     732k , avc1.4d001e, mp4a.40.2
hls-1114     mp4        1280x720   1114k , avc1.64001f, mp4a.40.2
hls-1898     mp4        1920x1080  1898k , avc1.640028, mp4a.40.2 (best)

youtube-dl --username USER -F http://www.crunchyroll.com/fatekaleid-liner-prisma-illya/episode-6-chilling-hostility-715507
Type account password and press [Return]: 
[Crunchyroll] Logging in
[Crunchyroll] 715507: Downloading webpage
[Crunchyroll] 715507: Downloading media info for 360p
[Crunchyroll] 715507: Downloading m3u8 information
[Crunchyroll] 715507: Downloading media info for 480p
[Crunchyroll] 715507: Downloading m3u8 information
[Crunchyroll] 715507: Downloading media info for 720p
[Crunchyroll] 715507: Downloading m3u8 information
[Crunchyroll] 715507: Downloading media info for 1080p
[Crunchyroll] 715507: Downloading m3u8 information
[Crunchyroll] 715507: Downloading media info
[info] Available formats for 715507:
format code  extension  resolution note
hls-meta-0   mp4        multiple   Quality selection URL 
hls-meta-1   mp4        multiple   Quality selection URL 
hls-meta-2   mp4        multiple   Quality selection URL 
hls-meta-3   mp4        multiple   Quality selection URL 
hls-541      mp4        640x360     541k , avc1.4d001e, mp4a.40.2
hls-749      mp4        848x480     749k , avc1.4d001e, mp4a.40.2
hls-1154     mp4        1280x720   1154k , avc1.64001f, mp4a.40.2
hls-1976     mp4        1920x1080  1976k , avc1.640028, mp4a.40.2 (best)
`

In my case I'm trying to get the 720p episode, yet one is labeled as "hls-1114" and the other is labeled as "hls-1154". This completely breaks scripting since you can no longer simply specifiy "download whatever video is at 720p".

is there a workaround for this?

**Comment by remitamine** [comment]
you can use `-f 'best[height=720]'` instead of `-f 720p`.
