### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError(u'flavorAssets',));

### ISSUE THREAD

**Issue by secupath** [rg3/youtube-dl#10617]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.08*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.08**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -u **REMOVED** -p **REMOVED** --playlist-start 361 -v https://www.safaribooksonline.com/library/view/android-6-app/9780134402017/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--playlist-start', u'361', u'-v', u'https://www.safaribooksonline.com/library/view/android-6-app/9780134402017/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.08
[debug] Python version 2.7.6 - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-81609-g7b3bc36-static
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in as **REMOVED**
[safari:course] Login successful
[safari:course] 9780134402017: Downloading course JSON
[download] Downloading playlist: Android 6 App Development Fundamentals I and II
[safari:course] playlist Android 6 App Development Fundamentals I and II: Collected 366 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[safari:api] 9780134402017/part360: Downloading part JSON
[safari] 9780134402017/part360: Downloading webpage
[safari] 9780134402017/part360: Downloading kaltura session JSON
WARNING: Unable to download kaltura session JSON: HTTP Error 401: UNAUTHORIZED
[Kaltura] " data-partner-id=: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'flavorAssets',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/kaltura.py", line 224, in _real_extract
    info, flavor_assets = entry_data['meta'], entry_data['contextData']['flavorAssets']
KeyError: u'flavorAssets'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'flavorAssets',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by brennebeck** [comment]
Hi,

I'm having the same issue as well. It seems something has happened with the kaltura downloader?

See [gist](https://gist.github.com/brennebeck/6c898e542b8489a44e0a9c127c6200dd) with `-v` output.

**Comment by dstftw** [comment]
@brennebeck completely different issue. Use another format for download - they now serve some unavailable formats.

**Comment by dstftw** [comment]
@secupath this video is not available in browser either https://www.safaribooksonline.com/library/view/android-6-app/9780134402017/part360.html. Thus it's safaribooks serving broken links in this playlist.

**Comment by brennebeck** [comment]
@dstftw what do you mean use a different format? I don't know of any way to change the format of safari videos?

**Comment by dstftw** [comment]
@brennebeck https://github.com/rg3/youtube-dl#format-selection.

**Comment by vincentHub-coder** [comment]
hi @dstftw I'm having this issue as well [gist ](https://gist.github.com/vincentHub-coder/377b590fb16a4a2623b37663059a5a82). 

Thanks! :)

**Comment by joeygeo** [comment]
The solution is to simply ignore those errors, and let it continue.

**Comment by ThomasFreedman** [comment]
How do you selectively ignore some errors and not others when using youtube-dl?

I would love to have the ability to catch errors that way. For example, you give youtube-dl a URL to a playlist of 200 videos. If you set "ignoreerrors" = True you can't catch any exceptions and if you set it to False you get a stack overflow before an exception is thrown.

`                try:
                    ydl.download(urls)  # BEGIN DOWNLOADING!!!
                except DownloadError as e:         # To catch httpError 429 for example
                    err = "ytdlProcess exception: Grupe=%s:\n%s" % (grupe, e)
                    eLog.write(err + '\n')
                    print(err)
                except Exception:   # ignore all other exceptions
                    pass

`

The code above never prints the DownloadError exception err. Instead the program is terminated due to a stack overflow due to the HttpError 429 error on each video dl attempt. The callback is never called and exceptions don't seem to bubble up to escape the download loop for the playlist. 

It would be great to have a hook (similar to the download progress callback) that gets called after / while each video is being processed. As it is now there is no way to be involved as youtube-dl processes each video of a playlist. Upper application layers are only able to react to each URL as a whole, not the individual videos that may be included in a URL, such as a playliast.

Once HttpError 429 occurs youtube essentially blacklists further requests from that IP address for some amount of time.  My code currently has ignoreerrors = True, so I get 200 of those errors for such a playlist and would like to change the code to abort downloading on the first HttpError 429 error I receive. I am trying to figure out how to do that.

I have tried using the various request rate limit techniques in youtube-dl but they don't prevent the 429 errors. If I immediately run the same code from a different computer (that has a different IP address), I can download, so it's not about too many requests from multiple sources or too many requests for a specific video causing the error, as in a DDoS attack. It is x number of requests from y=IP address in z amount of time. Don't know what youtube uses for the x & z numbers, but I download hundreds of yt videos every day and have been doing so all year long, and it takes more than a week or 2 for this error to show up for a given IP address with no rate limits set.
