### ISSUE TITLE
youtube-dl --update not working ?

### ISSUE THREAD

**Issue by mdmrcglu** [rg3/youtube-dl#1116]
Hi
 i have old version 23.07.2013.1
 need new version (24.07.2013)

[root@pc youtube-dl-master]# youtube-dl --update
youtube-dl is up-to-date (2013.07.23.1)

Thank you

**Comment by phihag** [comment]
@Ravinder0201 Your issue is unrelated to this issue entry. Please [open a new issue](https://github.com/rg3/youtube-dl/issues/new) if your problem persists. It looks like you did not install youtube-dl using pip in the first place. I'd bet that you used `apt-get`. See [our FAQ](https://yt-dl.org/) for more information, including the way to update if you are unsatisfied by the version included in the repositories used by apt-get.

**Comment by Ravinder0201** [comment]
Yes, I did it using apt-get and now i have recently intsalled ubuntu 14.04 LTS and in that too i have installed youtube-dl using apt-get. could you please tell me the difference between installing using apt-get and pip. and now if i want to do it using pip, how can i do it.

**Comment by phihag** [comment]
If you want to use pip you need to install pip, for example with `sudo apt-get install python-pip`.

Since this issue thread is getting exceedingly off-topic, I'm locking it. Please [open a new issue](https://github.com/rg3/youtube-dl/issues/new) if you have a new issue.
