### ISSUE TITLE
Is there a way to download the audio only from a watch later list using youtube-dl?

### ISSUE THREAD

**Issue by bitcoinmeetups** [rg3/youtube-dl#11193]
Is there a way to download the audio only from a watch later list using youtube-dl?

I have tried downloading the audio from this whole watch later list using this format:

youtube-dl -f 140 http://m.youtube.com/watch?list=WL&v=reZ4na9tc5Y

I get an error message: 

ERROR: Unsupported URL: https://www.youtube.com/

If possible, please describe the command I should use to achieve my goal.

Tag

**Comment by bitcoinmeetups** [comment]
(Ubuntu 15.10)

**Comment by siddht1** [comment]
no , the video now has been deleted  ,this is the message you will obtain

This video has been removed for violating YouTube's policy on hate speech

**Comment by siddht1** [comment]
use  
youtube-dl -i [web_link] -f [format_nos]

to download

**Comment by bitcoinmeetups** [comment]
Well, this format works well for playlists but I want to download the watch later list:

Works for playlist:

youtube-dl -i --extract-audio --audio-format mp3 https://www.youtube.com/playlist?list=PLi1FCxGBD-x6HW2OD0534F-NWjKXY2pyo

Does not work for watch later list (just downloads the first audio file, not the whole list):

youtube-dl -i --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=p_rQ-bcYrQc&list=WL

So, what I'm wondering is if it's possible to download the whole watch later list somehow rather than having to generate a playlist first?

**Comment by jdunn0** [comment]
The reason this isn't working is because the "&" character in your command tells the shell to run two commands.
So it runs `youtube-dl -i --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=p_rQ-bcYrQc` as a command that successfully downloads one YouTube video in mp3 format and a second command of `list=WL` which fails as that isn't an an actual command.
You need to quote the URL in your command so the whole URL gets passed to youtube-dl.
Your command would then be `youtube-dl -i --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=p_rQ-bcYrQc&list=WL"`

With the quoted URL, youtube-dl will see the `&list=WL` part and download the playlist.
This of course assumes you have configured youtube-dl to login to youtube with your username and password as otherwise, youtube-dl would not be able to access your Watch Later list.

**Comment by bitcoinmeetups** [comment]
Cool. That seems to work. Although sometimes it just downloads the first few videos and then I get some error message. I might be updating this thread again with regard to those pesky error messages : )

**Comment by cemretok** [comment]
I am using this to download list, extract music and resume if it's stop
youtube-dl --download-archive downloaded.txt -ixv -i --extract-audio --audio-format mp3 "https://www.youtube.com/playlist?list=rrbrn933h1_renrenG2Q&list=WL"

**Comment by norcaljohnny** [comment]
Im surprised no one has used --yes-playlist
This is what I use.
`youtube-dl -i -x --audio-format mp3 --yes-playlist "https://www.youtube.com/watch?v=UVtpXvzzXiA&list=PL9CBD197B2E453347"`

Use double quotes are url if '&' is in the url or change the & => &amp;
