### ISSUE TITLE
Use thread with postprocessors [request] [postprocessors]

### ISSUE THREAD

**Issue by Knah-Tsaeb** [rg3/youtube-dl#1125]
Ffmpeg support option for use multi thread (-threads N). Can you add option for define nb thread postprocessors can use. I think the good choice is nbcore-1.

**Comment by pricejn2** [comment]
subscribed! this would be excellent.

**Comment by ravkr** [comment]
Any updates? it would be very helpful on my Raspberry Pi... 👍

**Comment by yan12125** [comment]
Since June 2015 (#5942), you can use ```--postprocessor-args "-threads 3"```

**Comment by STonEDSTonE** [comment]
I stumbled over this because i was frustrated that the ffmpeg convert just runs on one thread.
I know this is closed for years, but i didn't find something newer regarding that matter.
My VM has 4 Threads to work with, i tried --postprocessor-args "-threads 3", but it did nothing.
youtube-dl --extract-audio --audio-format vorbis --audio-quality 0 --postprocessor-args "-threads 3" --metadata-from-title "%(artist)s - %(title)s" -o ~/Schreibtisch/%\(title\)s\ -\ %\(upload_date\)s.%\(ext\)s URL

I also tried different "places" for the postprocessor-args within the command, didn't help either.
Someone can give me a hint?

(Still i think since todays processors have multiple threads available, multithread support should be declared standard)
