### ISSUE TITLE
[pluralsight] Downloading course JSON ERROR

### ISSUE THREAD

**Issue by GaiusJulius** [rg3/youtube-dl#12075]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Again problem with Pluralsight
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-c', '-w', '-A','--min-sleep-interval', '35', '--max-sleep-interval', '40', '--no-mtime', '--autonumber-size', '3', '-v', '-a', 'url.txt']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/responsive-websites-bootstrap3/', 'https://app.pluralsight.com/library/courses/css3-in-depth/', 'https://app.pluralsight.com/library/courses/play-by-play-lea-verou/']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.02.10
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] responsive-websites-bootstrap3: Downloading course JSON ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdk0ryty4\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdk0ryty4\build\youtube_dl\YoutubeDL.py", line 2006, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
Can you watch it in browser in the first place?

**Comment by ArkadiuszZolnik** [comment]
I have exactly the same problem. In the morning everything was fine.

**Comment by ricardolopes86** [comment]
I am having the same issue, just reported the bug. Didn't pay attention that already had an issue reported.

**Comment by muffadalis** [comment]
I am having the same issue

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '600', '-
o', '%(autonumber)s-%(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/aws-certified-solutions-architect-professional/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aws-certified-solutions-architect-professional: Downloading course JSON
[pluralsight:course] aws-certified-solutions-architect-professional: Downloading course data JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdk0ryty4\build\youtube_dl\extractor\common.py", lin
e 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdk0ryty4\build\youtube_dl\YoutubeDL.py", line 2006,
 in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
`

**Comment by dstftw** [comment]
For any further investigations valid account credentials must be provided.

**Comment by mstickler** [comment]
This call used to work WITHOUT credentials, but fails with 404 now.

youtube-dl -s --skip-download --flat-playlist  https://app.pluralsight.com/library/courses/spark-streaming-stream-processing-getting-started

**Comment by ricardolopes86** [comment]
"Valid account should be provided"

I didn't understand what's being requested.

**Comment by mstickler** [comment]
Don't worry, it's already been fixed ;-) I pointed out a way to test WITHOUT credentials. Just update to version 2017.02.11 where everything is back to normal thanks to Sergey.
