### ISSUE TITLE
YouTube Page Format Changes

### ISSUE THREAD

**Issue by mysteryx93** [rg3/youtube-dl#12200]
This isn't a question directly about YouTube-dl, but I rather I'd like to know how you guys handled the issue.

Recently, YouTube appears to have changed their format. as discussed [here](https://github.com/flagbug/YoutubeExtractor/issues/240). For some videos, there is no longer a "ytplayer.config" section, and there is instead a "RELATED_PLAYER_ARGS" section which I believe contains the data... not yet sure if it's the same format or what else changed.

If I look in my browser, RELATED_PLAYER_ARGS is there with a lot of data inside. If I download from a software, however, the tag comes out empty as 'RELATED_PLAYER_ARGS': {"rvs":""},

How are you dealing with this, and what else is there to know about these latest changes?

Thanks

**Comment by Hanzalah-Adalan** [comment]
The only thing I could do now is waiting for a good genius to fix this.. 👍

**Comment by dstftw** [comment]
Nothing really changed for Firefox UA.

**Comment by Hanzalah-Adalan** [comment]
Yeah I agree.. perhaps nothing really changed, because these two beasts still work flawlessly..

1- http://www.saveitoffline.com/#https://www.youtube.com/watch?v=SkRSXFQerZs

2- http://en.savefrom.net/#url=http://youtube.com/watch?v=SkRSXFQerZs&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=www.ssyoutube.com
