### ISSUE TITLE
Problems parsing embedded youtube video URL

### ISSUE THREAD

**Issue by tjesp** [rg3/youtube-dl#1222]
Often when I copy and paste a link from an embedded youtube video I get a link on this format:

http://www.youtube.com/watch?feature=player_embedded&v=_o-sKdyUPO8

The problem is that youtube-dl seems to need the "watch?" string to be immediately followed by the "v=??????" string.

This url format is what I most often get when I right click an embedded video and select "copy video URL".

**Comment by jaimeMF** [comment]
Since it seems to work fine, I'm closing the issue. Make sure you are quoting the url, because it contains a `&`, which is a special character for the shell. If you still have the problem, feel free to post the output of `youtube-dl --verbose 'http://www.youtube.com/watch?feature=player_embedded&v=_o-sKdyUPO8'` and we will reopen the issue.
