### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by nikko24** [rg3/youtube-dl#12890]
Hi, i have this problem. 

![2017-04-28-080803_1360x768_scrot](https://cloud.githubusercontent.com/assets/15264150/25516278/ded19200-2be9-11e7-901b-4061fef85f2f.png)

I have any idea.

**Comment by dkaranja** [comment]
+1

**Comment by SuperdukeGates** [comment]
I also have the same problem.

> $ ./youtube-dl -v "https://www.youtube.com/watch?v=iYKe3aTc8D0"
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=iYKe3aTc8D0']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2017.04.26
> [debug] Python version 2.7.13 - Linux-4.10.12-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
> [debug] exe versions: none
> [debug] Proxy map: {}
> [youtube] iYKe3aTc8D0: Downloading webpage
> [youtube] iYKe3aTc8D0: Downloading video info webpage
> [youtube] iYKe3aTc8D0: Extracting video information
> WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> [youtube] {22} signature length 40.40, html5 player None
> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "./youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
>     ie_result = ie.extract(url)
>   File "./youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
>     ie_result = self._real_extract(url)
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1642, in _real_extract
>     encrypted_sig, video_id, player_url, age_gate)
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1091, in _decrypt_signature
>     'Signature extraction failed: ' + tb, cause=e)
> ExtractorError: Signature extraction failed: Traceback (most recent call last):
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "./youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

where take the OP's clip as the example.

**Comment by einstein95** [comment]
https://pastebin.com/CG2ayHpJ
Yet another confirmation using a video from 2009

**Comment by astevens** [comment]
+1
https://www.youtube.com/watch?v=Ad6SxduZfis

File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'

**Comment by udany** [comment]
![image](https://cloud.githubusercontent.com/assets/6425637/25517129/58188cde-2bc4-11e7-9621-2f17d7bb0a1f.png)
Same here...

**Comment by nikko24** [comment]
Why @dstftw close this Issue? Isn´t duplicate.

**Comment by rodzky** [comment]
I have the same issue, I'm using windows exe version 04.26.2017

C:\Users\Administrator>youtube-dl -v --extract-audio --audio-format mp3 -o C:/yo
utube-downloads/%(id)s.%(ext)s http://www.youtube.com/watch?v=RgKAFK5djSk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format', 'mp3', '-
o', 'C:/youtube-downloads/%(id)s.%(ext)s', 'http://www.youtube.com/watch?v=RgKAF
K5djSk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-85588-g6108805, ffprobe N-85588-g6108805
[debug] Proxy map: {}
[youtube] RgKAFK5djSk: Downloading webpage
[youtube] RgKAFK5djSk: Downloading video info webpage
[youtube] RgKAFK5djSk: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/
jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its comple
te output.",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1642, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1091, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most re
cent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/
jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its comple
te output.",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
See: #12885
