### ISSUE TITLE
Feature request: --touch-files (update timestamp on skipped local files)

### ISSUE THREAD

**Issue by glenn-slayden** [rg3/youtube-dl#13321]
**Feature request:**  `--touch-files` which would cause a previously downloaded file's **timestamp** (i.e. its local filesystem 'modified' date) to be updated any time the download is reconsidered, even if excluded by selection features (such as  `--download-archive`).

**Use case:**  enables acquiring and unconditionally tagging a specific set of files based on a URL list, regardless of whether newly or previously downloaded.

**Comment by glenn-slayden** [comment]
Although a similar effect could be achieved by temporarily omitting `--download-archive`, doing so would re-download previously obtained files. The proposed `--touch-files` option would ensure that existing files are simply marked without re-downloading.

**Comment by glenn-slayden** [comment]
Obviously, this option would only apply if a local file can be found to `touch`. I believe that, currently, being listed in the `--download-archive` bypasses the filename-building step altogether, so this code would need to be changed in the case where `--touch-files` is active.

Specifically, for skipped files, the filename would be have to be built as usual with the available/current templates, and if that target file exists locally then it can be 'touched'. If no such file exists, it would not be an error, instead just reverting to the current behavior (no action taken).

**Comment by dstftw** [comment]
Videos which haven't passed filters (in particular videos presented in download archive) are always skipped  and other options have no effect on corresponding files. I don't feel like changing this behavior for just one option. This feature also seems too specific and may produce unexpected results since download archive doesn't track filenames.
You can achieve this with simple script.
