### ISSUE TITLE
pornhd: unable to extract error message

### ISSUE THREAD

**Issue by vorequeen** [rg3/youtube-dl#13783]
Here is the errot log from youtube-dl when you try it on
https://www.pornhd.com/videos/56284/hot-wife-gets-her-married-ass-slammed-in-front-of-hubby-hd-porn-movie

Debug output:

youtube-dl --verbose --newline https://www.pornhd.com/videos/56284/hot-wife-gets-her-married-ass-slammed-in-front-of-hubby-hd-porn-movie[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--newline', u'https://www.pornhd.com/videos/56284/hot-wife-gets-her-married-ass-slammed-in-front-of-hubby-hd-porn-movie']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 2.7.13 - Linux-4.11.3-202.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.8, ffprobe 3.1.8
[debug] Proxy map: {}
[PornHd] hot-wife-gets-her-married-ass-slammed-in-front-of-hubby-hd-porn-movie: Downloading webpage
ERROR: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pilate/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/pilate/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/pilate/bin/youtube-dl/youtube_dl/extractor/pornhd.py", line 63, in _real_extract
    webpage, 'error message', group='value')
  File "/home/pilate/bin/youtube-dl/youtube_dl/extractor/common.py", line 791, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/pilate/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by arielesp** [comment]
same error here ... changed something....

youtube-dl https://www.pornhd.com/videos/13424/krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhd.com/videos/13424/krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 2.7.5 - Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: avconv v13_dev0-902-gd7b2bb5-static, avprobe v13_dev0-902-gd7b2bb5-static, ffmpeg 3.3-static, ffprobe 3.3-static
[debug] Proxy map: {}
[PornHd] krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video: Downloading webpage
ERROR: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhd.py", line 63, in _real_extract
    webpage, 'error message', group='value')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 791, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract error message; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by arielesp** [comment]
... changed something.... again ...

# youtube-dl https://www.pornhd.com/videos/13424/krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhd.com/videos/13424/krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.5 - Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: avconv v13_dev0-902-gd7b2bb5-static, avprobe v13_dev0-902-gd7b2bb5-static, ffmpeg 3.3.3-static, ffprobe 3.3.3-static
[debug] Proxy map: {}
[PornHd] krissy-in-the-kitchen-suck-and-fucks-until-his-cock-erupts-hd-porn-video: Downloading webpage
ERROR: 13424: Failed to parse JSON  (caused by ValueError('Extra data: line 1 column 416 - line 1 column 760 (char 415 - 759)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 691, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 416 - line 1 column 760 (char 415 - 759)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhd.py", line 58, in _real_extract
    webpage, 'sources', default='{}')), video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 695, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 13424: Failed to parse JSON  (caused by ValueError('Extra data: line 1 column 416 - line 1 column 760 (char 415 - 759)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
