### ISSUE TITLE
Support translated titles (youtube)

### ISSUE THREAD

**Issue by Zayon** [rg3/youtube-dl#13811]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?utf8=%E2%9C%93&q=lang&type=Issues)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Sometime youtube video's titles are translated from original to the lang of the visitor.
Example : https://www.youtube.com/watch?v=XZnySZWeSJM

This video is french and its title is `L'ÉPOPÉE TEMPORELLE EP1 - LE ROBOT`, but if your navigator is configured in english it is displayed as `THE TEMPORAL EPOPEE EP1 - THE ROBOT`.

So when I use this command : 
`youtube-dl --get-filename -o "%(title)s" "https://www.youtube.com/watch?v=XZnySZWeSJM"`

I will get : `THE TEMPORAL EPOPEE EP1 - THE ROBOT`

It would be cool if one can specify the language youtube-dl use, for example

`youtube-dl --lang="FR" --get-filename -o "%(title)s" "https://www.youtube.com/watch?v=XZnySZWeSJM"`

Thanks.

**Comment by frou** [comment]
This was marked as **duplicate**, but which issue is it a duplicate of? I can't find anything.

**Comment by GlassedSilver** [comment]
Maybe they mean issue #10758?

Which would be ironic, since whilst the topic is the same, the preferred solution is different...

In any case, this should be a toggle and ideally an option to save both the original title as well as the translated one in the json.

Would love to download my Japanese videos with the English title if available and still keep the Japanese title in the json for reference. Or the other way around once I'm fluent in Japanese and my preferences shift. :)
