### ISSUE TITLE
youtube-dl is unable to download sensitive content from Tumblr

### ISSUE THREAD

**Issue by amg1127** [rg3/youtube-dl#13829]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ /usr/bin/youtube-dl -v -u "${TUMBLR_USERNAME}" -p "${TUMBLR_PASSWORD}" 'http://sweetliciousnet.tumblr.com/post/163673652169'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'http://sweetliciousnet.tumblr.com/post/163673652169']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.6.2 - Linux-4.12.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 163673652169: Downloading webpage
[generic] 163673652169: Requesting header
WARNING: Could not send HEAD request to https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/: HTTP Error 404: Not Found
[generic] 163673652169: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 163673652169: Extracting information
ERROR: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/

```
---

### Description of your *issue*, suggested solution and other information

A recent Tumblr policy change now requires a Tumblr user to log in and turn off safe mode in order to access sensitive content. According to their [FAQ regarding sensitive content](https://tumblr.zendesk.com/hc/en-us/articles/231885248-Sensitive-content):

> I marked my blog as explicit. What happens now?
> 
> Now you can be sure that only suitable audiences are seeing your content. Blogs that are marked explicit are kept out of search results for people in Safe Mode. Anyone viewing your blog on the web will have to be logged in (with safe mode off) to see it.
> 

However, I am unable to download sensitive content from Tumblr even though I supply valid account credentials on youtube-dl command line.

In order to reproduce the issue, one can obtain a Tumblr account [here](https://www.tumblr.com/register). An adult content that youtube-dl is unable to get can be accessed [here](http://sweetliciousnet.tumblr.com/post/163673652169).

**Comment by amg1127** [comment]
@dstftw ,

In order to reproduce the issue, please use the following Tumblr account:

Username: 13829youtubedlbug@thisisnotmyrealemail.com
Password: youtube-dl_2017.07.30.1

The account is linked to a disposable mail service located at www.mailinator.com .


```
$ export TUMBLR_USERNAME='13829youtubedlbug@thisisnotmyrealemail.com'
$ export TUMBLR_PASSWORD='youtube-dl_2017.07.30.1'
$ /usr/bin/youtube-dl -v -u "${TUMBLR_USERNAME}" -p "${TUMBLR_PASSWORD}" 'http://sweetliciousnet.tumblr.com/post/163673652169'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'http://sweetliciousnet.tumblr.com/post/163673652169']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.06
[debug] Python version 3.6.2 - Linux-4.12.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Tumblr] 163673652169: Downloading webpage
[generic] 163673652169: Requesting header
WARNING: Could not send HEAD request to https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/: HTTP Error 404: Not Found
[generic] 163673652169: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 163673652169: Extracting information
ERROR: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/

```

**Comment by Hrxn** [comment]
```
PS F:\> youtube-dl --ignore-config -v -u <tumblr_test_account> "http://sweetliciousnet.tumblr.com/post/163673652169"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-u', 'PRIVATE', 'http://sweetliciousnet.tumblr.com/post/163673652169']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 3.6.1 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-87043-gf0f4888, ffprobe N-87043-gf0f4888
[debug] Proxy map: {}
[Tumblr] 163673652169: Downloading webpage
[generic] 163673652169: Requesting header
WARNING: Could not send HEAD request to https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/: HTTP Error 404: Not Found
[generic] 163673652169: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 163673652169: Extracting information
ERROR: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/
Traceback (most recent call last):
  File "c:\users\hrxn\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\hrxn\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "c:\users\hrxn\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\generic.py", line 2989, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/

PS F:\>
```

So, yeah. I used a wrong password on purpose. Authentication does not work at all. Has it ever for Tumblr? Not sure actually, can't remember that it was used at all..

OP, what you could alternatively do is try to [supply cookies to youtube-dl.](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)

@dstftw could you please explain what you meant here with account required? Best way forward to add proper auth to tumblr extractor? With support for .netrc, for example..

**Comment by raindog469** [comment]
I can confirm that the workaround suggested by @Hrxn (extracting and supplying cookies) works as intended for tumblr URLs that would normally redirect to the safe-mode page in youtube-dl version 2017.09.15. 

I did this by extracting the cookies in wget format using the "cliget" firefox extension, then converting those cookies to Netscape cookie jar format using the tool at http://crdx.org/misc/cookies/, saving in a local file and passing that file to youtube-dl's --cookies option. I expect this will only last as long as tumblr thinks I'm logged in, so it's not a particularly convenient workaround, but it is faster than visiting every page and using a Firefox download helper to get the videos.

Please note that I also had to use the --user-agent option to match the Firefox version with which I signed into tumblr, also provided with the cliget extension's output.

**Comment by royhsia** [comment]
I've tried the pass cookies method on Mac's Terminal and Windows' command line. It works on windows, but it doesn't works on mac.

On windows: 
1. Using the binary [youtube-dl.exe](https://rg3.github.io/youtube-dl/download.html) with version 2017.09.15. 
2. Export Firefox cookies with [Export Cookies](https://addons.mozilla.org/zh-TW/firefox/addon/export-cookies/) add-ons. It exports cookies in Netscape format.
3. Log
`C:\Users\User\Downloads>youtube-dl.exe http://sweetliciousnet.tumblr.com/post/163673652169
[Tumblr] 163673652169: Downloading webpage
[generic] 163673652169: Requesting header
WARNING: Could not send HEAD request to https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/: HTTP Error 404: Not Found
[generic] 163673652169: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 163673652169: Extracting information
ERROR: Unsupported URL: https://www.tumblr.com/safe-mode?url=http://sweetliciousnet.tumblr.com/post/163673652169/

C:\Users\User\Downloads>youtube-dl.exe --cookies cookies.txt http://sweetliciousnet.tumblr.com/post/163673652169
[Tumblr] 163673652169: Downloading webpage
[Tumblr] 163673652169: Downloading iframe page
[download] Destination: sweetlicious.net-163673652169.mp4
[download] 100% of 1008.46KiB in 00:06

C:\Users\User\Downloads>`

On Mac:
1. `sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ~/Downloads/youtube-dl
sudo chmod a+rx ~/Downloads/youtube-dl`
2. Export Firefox cookies with [Export Cookies](https://addons.mozilla.org/zh-TW/firefox/addon/export-cookies/) add-ons. It exports cookies in Netscape format.
3. Log
`User-MBP:Downloads User$ youtube-dl --version
2017.09.15
User-MBP:Downloads User$ youtube-dl --cookies cookies.txt http://sweetliciousnet.tumblr.com/post/163673652169 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'http://sweetliciousnet.tumblr.com/post/163673652169', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4-tessus
[debug] Proxy map: {}
[Tumblr] 163673652169: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2177, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

User-MBP:Downloads User$ 
`

**Comment by dstftw** [comment]
@royhsia invalid newline format. https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by royhsia** [comment]
@dstftw Thanks!
After I use TextMate to replace /r/n with /n, It works.
