### ISSUE TITLE
please support BitChute (free speech first video hoster)

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#14052]
thanks in advance

```
youtube-dl -v https://www.bitchute.com/video/szoMrox2JEI/
[debug] System config: [u'--recode-video=mp4', u'-f', u'bestvideo+bestaudio/best']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bitchute.com/video/szoMrox2JEI/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'http://127.0.0.1:8118'}
[generic] szoMrox2JEI: Requesting header
WARNING: Falling back on generic information extractor.
[generic] szoMrox2JEI: Downloading webpage
[generic] szoMrox2JEI: Extracting information
ERROR: Unsupported URL: https://www.bitchute.com/video/szoMrox2JEI/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2116, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 58, column 31
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2989, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.bitchute.com/video/szoMrox2JEI/
```
https://www.bitchute.com/video/szoMrox2JEI/
Single video: https://www.bitchute.com/embed/lbb5G1hjPhw/
Single video: https://www.bitchute.com/embed/msVA0ajknjA/
Playlist: https://www.bitchute.com/channel/stefanmolyneux/
Playlist: https://www.bitchute.com/feeds/rss/channel/corbettreport/

**Comment by tv21** [comment]
You probably should be careful about sites that promote themselves as "free speech" sites these days; in some cases (but definitely not all) "free speech" is an euphemism for "hate speech", in that they allow people to post the most vile anti-Semitic and racist speech, and other hate speech.  Or it could be posting instructional videos on how to commit illegal or harmful acts.  I am not saying this particular site is or isn't that way, I am just saying that you might want to be careful about sites that have no filters, lest you inadvertently end up enabling the dissemination of speech that most people might have a strong objection to (which could bring about some entirely unwanted publicity).

**Comment by klopsi** [comment]
"Truth sounds like hate, to those who hate truth."

**Comment by Tatsh** [comment]
@tv21 If that's the case demand removal of all the porn site extractors. Far more damaging long-term, scientifically proven (see brain studies on porn addicts). youtube-dl is neutral except on sites that are dedicated to copyright infringement.

Support for this is going to require some extra work compared to others. Two ways to achieve this:

* Download direct via the HTTP URI, which is extremely slow from what I can tell. The MP4 URI expires eventually so I do not know how reliable this is anyway. You can try downloading in Firefox. Easy but probably not reliable.
* Use the torrent file, making a lightweight torrent client in `downloaders` (no this is not as hard as it sounds). The torrent client must ignore `wss:` URLs. On any video page, there is this line:

```html
<script>
    var torrentId = "https://www.bitchute.com/torrent/2637/VoJn2bZ7i0Cd.torrent"
// ...
</script>
```

If this line isn't found for some reason, fall back on the meta tag and replace .jpg with .torrent: `<meta name="twitter:image:src" content="https://www.bitchute.com/torrent/1565/CdQwcvtdRVyE.jpg">`

Most certainly it will be faster than the direct HTTP method, especially since unlike their site, the normal torrent client can do out of order downloading. As far as I can tell, there is only one format they use so there is no need to be concerned about the user's preferences on this.

**Comment by tv21** [comment]
Look, it was just a warning.  People nowadays (except for some strongly religious types) pretty much accept that there is going to be porn on the Internet, and there is not much you can do about it.  However, certain types of hate speech are a totally different animal, especially in the world we live in today. Hate speech can get people killed (I suppose porn can also, but it's not nearly as common).  The problem is that sometimes "Free Speech" means they are telling you about subjects the major media avoids (which can be good, at least when it's truthful speech) but sometimes it is just people spewing venomous hate, and I don't believe any good person should give those people a platform to spew their hate.

If you side with the hate purveyors then you are a despicable person and I have nothing to say to you.  If you side with shining a light on topics the major media avoids, or distorts the truth about, I am right there with you.  Those are not the same thing.  And my real fear is that if youtube-dl becomes an enabler for the haters, and someone were to commit an act of hate based on a video they obtained using youtube-dl and that somehow got publicized, the developers would probably not want the hell of bad publicity that would come upon them.  Youtube-dl can operate pretty freely as long as it stays under the radar, but get linked to something really nasty and suddenly a whole lot of people that the devs probably don't want to be involved with are going to be asking a lot of questions about what youtube-dl is and what it does.

Again, I want to stress that I have no idea where this particular site stands on hate speech, my reason for posting was just to say that maybe that is something that should be investigated with regard to any site using the code words "Free Speech" in today's climate.  Those words mean different things to different people.

**Comment by klopsi** [comment]
This censorship has no place in a piece of software.

**Comment by Tatsh** [comment]
I think the scenario you have described is not realistic:

* Would-be bad person finds a video they like.
* Downloads said video using youtube-dl.
* Watches the video? They probably already watched it on the actual website. The website is providing the platform. No hosting of the video means no platform. youtube-dl does not host content.
* Would-be person can now share the video? Who should be responsible if other people who receive the video do anything criminal or 'wrong'?
* This bad person does a criminal act (hate or not), inspired by the video. Blames youtube-dl.

You think youtube-dl should be held responsible?

We do not prosecute gun manufacturers when someone uses one for harm. The individual is responsible for their actions, no matter the means to get there.

There is plenty of content I do not like seeing that exists on YouTube (99% of what is in the trending section) but I am not demanding youtube-dl not download those videos, nor am I asking for removal of those people's platforms.
