### ISSUE TITLE
YouTube: no maxresdefault thumb anymore?

### ISSUE THREAD

**Issue by MacDada** [rg3/youtube-dl#14103]
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

I'm gonna repeat my issue from here: https://github.com/rg3/youtube-dl/issues/14079#issuecomment-326392063

It's marked as duplicate, but i searched all issues with [maxresdefault](https://github.com/rg3/youtube-dl/search?o=desc&q=maxresdefault&s=created&type=Issues&utf8=%E2%9C%93) and found nothing.

```
$ youtube-dl --version
2017.08.27.1
$ youtube-dl -j https://www.youtube.com/watch?v=V7oiro8tYA4 | grep -Po '"thumbnail":.*?[^\\]",'
WARNING: unable to extract uploader nickname
"thumbnail": "https://i.ytimg.com/vi/V7oiro8tYA4/default.jpg",
```

`youtube-dl` now returns a default thumb: https://i.ytimg.com/vi/V7oiro8tYA4/default.jpg

I'm quite sure it used to return maxresdefault thumb: https://i.ytimg.com/vi/V7oiro8tYA4/maxresdefault.jpg

Question: is it going to be "fixed" and youtube-dl will return `maxresdefault` thumbs or should I generate thumb urls by myself, without the use of `youtube-dl` for that matter?

**Comment by MacDada** [comment]
nvm, with `2017.09.02` it's back to maxresdefault again ;)

**Comment by KingMob** [comment]
I wouldn't say it's invalid just yet, since we're still seeing the issue on a decent fraction of our requests.

It may be related to missing VideoObject schemas, since if youtube-dl can't find `<span itemprop="thumbnail"...>`, the backup thumbnail methods only find the low-res thumbs. It could also be the `disable_polymer=true` query param, since without it, the Youtube web page doesn't have the VideoObject schema on it.

I wonder if it's related to the intermittency issues or choice of DNS servers as mentioned in the comments of  #11270.

**Comment by victornpb** [comment]
I'm getting 120x90 thumbnails here
