### ISSUE TITLE
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>

### ISSUE THREAD

**Issue by dustycy** [rg3/youtube-dl#14104]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched]() the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\LAK\Downloads\youtube_dl>youtube_dl.exe -v https://chaturbate.com/sweet_ary/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://chaturbate.com/sweet_ary/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-87130-g2b9fd15, ffprobe N-87130-g2b9fd15
[debug] Proxy map: {}
[Chaturbate] sweet_ary: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 2168, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\utils.py", line 1086, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

C:\Users\LAK\Downloads\youtube_dl>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I occasionally get the ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> with youtube-dl. It looks as though this is a time-out problem with youtube-dl (_ssl.c:600). The problem appears to be with somewhat slow downloading of the web pages where youtube-dl times out. I have no issues downloading the pages with either Firefox or Opera (Internal VPN enabled or not). Otherwise, the ERROR appears to random as I cannot reproduce it when I rerun youtube-dl again. It sometimes spits the error and sometimes it does not.

**Comment by dustycy** [comment]
I do not know what exactly youtube-dl is doing to my network connection, but I am now also getting occasional "TLS Handshake" errors in Firefox.

**Comment by dstftw** [comment]
If it appears randomly then it's obviously an issue with your network connection.

**Comment by Oaroyal** [comment]
I'v got the same issue ssl.c:600 issue when 
youtube-dl -v --write-auto-sub https://www.youtube.com/user/OracleMidlands
......
[download] Downloading video 13 of 17
[youtube] 75O-38YKbjw: Downloading webpage
[youtube] 75O-38YKbjw: Downloading video info webpage
[youtube] 75O-38YKbjw: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Oracle Midlands #4 - Oracle Big Data Appliance - What's in the box - Salih Ozop-75O-38YKbjw.en.vtt
[download] Oracle Midlands #4 - Oracle Big Data Appliance - What's in the box - Salih Ozop-75O-38YKbjw.mp4 has already been downloaded and merged
[download] Downloading video 14 of 17
[youtube] qlFyAYewBDI: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
