### ISSUE TITLE
streamango.com no longer working

### ISSUE THREAD

**Issue by drewc** [rg3/youtube-dl#14160]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure 
# Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://streamango.com/f/caeceelccblmrpal/VICE_S05E24_HDTV_x264-UAV_mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 2.5.3-1kxstudio1, ffprobe 2.5.3-1kxstudio1
[debug] Proxy map: {}
[Streamango] caeceelccblmrpal: Downloading webpage
WARNING: [Streamango] caeceelccblmrpal: Failed to parse JSON Expecting ':' delimiter: line 2 column 41 (char 42)
WARNING: [Streamango] caeceelccblmrpal: Failed to parse JSON Expecting ',' delimiter: line 1 column 30 (char 29)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/streamango.py", line 68, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1072, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

It stopped working for streamandgo, for all videos, earlier this week.

**Comment by tb3d** [comment]
Getting same error. Any solutions?

**Comment by mpmman** [comment]
still getting same error for version 2017-09-15

**Comment by arnrob14344** [comment]
user@Laptop1 ~]$ youtube-dl -g https://streamango.com/embed/lrsealcbtakklcar/tvpatrol_20180105_mp4
WARNING: [Streamango] lrsealcbtakklcar: Failed to parse JSON Expecting ',' delimiter: line 1 column 30 (char 29)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bato3** [comment]
```
youtube-dl --version
2018.02.04
```

Still not working

**Comment by bato3** [comment]
It is possible to execute javascript, and get variable value as object?

in code is (without "namespace" / privace space):
```
eval(function(p,a,c,k,e,d){  [..]  window.d=function(){[..]}  [..] }) //pseudocode part
var srces=[];
srces.push({type:"video/mp4",src:d('1+DNjJ3boaLflqjR1qzRleDK16wRlavdm57To5zOkJvflqnanpIPzd8I0NsQzNcNht8JyOIO09sS0OIQhrrnipX8qpjM19kO0QAA',3),height:720,bitrate:1344});	
```

**Comment by Westerlysse** [comment]
I installed the latest version for this purpose
`youtube-dl --version
2018.02.08` 
which was annoying because I had to solve another error that prevented installation, only to discover that there was still no patch for Streamango.  I use an OSX machine but the error appears to be the same for me anyway.  
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://streamango.com/f/sptlraqkffmcoqna', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Streamango] sptlraqkffmcoqna: Downloading webpage
WARNING: [Streamango] sptlraqkffmcoqna: Failed to parse JSON Expecting ',' delimiter: line 1 column 30 (char 29)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/streamango.py", line 68, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1071, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by csanthosh75** [comment]
I am getting the same error what is the correct format
