### ISSUE TITLE
Vidlii Support (Trying A Post Again)

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#14472]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.12*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

~$ youtube-dl http://www.vidlii.com/watch?v=vBo2IcrwOkO -v --write-info-json
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.vidlii.com/watch?v=vBo2IcrwOkO', '-v', '--write-info-json']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.12
[debug] Python version 3.5.2 - Linux-4.10.0-35-generic-i686-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] watch?v=vBo2IcrwOkO: Requesting header
[redirect] Following redirect to https://www.vidlii.com/watch?v=vBo2IcrwOkO
[generic] watch?v=vBo2IcrwOkO: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=vBo2IcrwOkO: Downloading webpage
[generic] watch?v=vBo2IcrwOkO: Extracting information
[generic] embed?v=vBo2IcrwOkO&a=0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed?v=vBo2IcrwOkO&a=0: Downloading webpage
[generic] embed?v=vBo2IcrwOkO&a=0: Extracting information
ERROR: Unsupported URL: https://www.vidlii.com/embed?v=vBo2IcrwOkO&a=0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 3041, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vidlii.com/embed?v=vBo2IcrwOkO&a=0

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.vidlii.com/watch?v=vBo2IcrwOkO
- User account: https://www.vidlii.com/user/TekstaMembrain

---

### Description of your *issue*, suggested solution and other information

Ok, apparently my previous issue in August was not described accurately, so here's a site support request. Apparently the output is different this time; also Vidlii is a 2000s YouTube clone.

**Comment by patrickj0607** [comment]
Hi dkl3, my friend and me are beginners in Open Source software development and as this looks like a great starter issue, we would like to implement it. 

We just take a look at vidlii.com. Are we right in the assumption that there is not playlist functionality on this site?

**Comment by dkl3** [comment]
I don't see any playlists, no. :(

**Comment by patrickj0607** [comment]
Alright. Thanks for your feedback. We will start working on it next week.

**Comment by patrickj0607** [comment]
Hi dkl3,
we just got familiar with the page structure of vidlii in order to implement the video extractor. We found the following meta data which can be extracted from the site:
- title
- description
- uploader
- url
- uploader_url
- upload_date
- categories
- tags
- duration
- view_count
- comment_count
- average_rating
- thumbnail
- type

Do you have any further suggestions?

In the next step we will generate appropriate regular expressions for scraping the data and implement the extractor by using the methods provided in commons.py and utils.py.

We would appreciate a short feedback. Thank you!

**Comment by dkl3** [comment]
oh no, that's perfect, thank you :D :)

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/issues/13883

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/pull/14512

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/pull/14779

**Comment by SunflowerPKU** [comment]
> Hi dkl3, my friend and me are beginners in Open Source software development and as this looks like a great starter issue, we would like to implement it.
> 
> We just take a look at vidlii.com. Are we right in the assumption that there is not playlist functionality on this site?

Hi @patrickj0607 ,

I am a Ph.D. student. I am doing research about **helping newcomers participate in OSS projects**. I noticed that many projects are using labels such as 'good first issue/bug, difficulty/newcomer' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

**1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?**

I am looking forward to hearing from you soon. Thank you very much!

**Comment by patrickj0607** [comment]
Hi @SunflowerPKU 

thanks for asking about my experience in contributing to this project!

Our contribution is long time ago, however, I hope I can give you some valuable feedback.

1. The instructions on how to implement extractors were not very specific. For example, the regular expressions should be flexible to allow tolerance for site changes. However, it is very difficult to find the right level of flexibility. Furthermore, as the existing extractors were of highly varying quality, it was difficult to find some very good implementations. We would have been happy if there were some extractors marked as _very good implementation_ to have some references. 

2. Yes, I think the implementation of an extractor is a good starting point because after implementing the first extractor, the next ones will be much easier.

2. I think labels with tasks for newcomers make sense because they motivate and help beginners to find a starting point. However, in this specific project the extractors are the most fundamental part which can easily be extended. Therefore I think that labels are not required therefore. In general, I think that a good communication and helpful resources (guidelines, example code, etc.) are most valuable for starters.

At the end, our pull request was not merged. This is very frustrating. Instead, the reviewer should give us more helpful and precise feedback such that we can make the required changes by ourself.
