### ISSUE TITLE
Album art not added from some soundcloud songs

### ISSUE THREAD

**Issue by davisonio** [rg3/youtube-dl#15022]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -o '~/Downloads/%(title)s.%(ext)s' --audio-format mp3 --embed-thumbnail --add-metadata https://soundcloud.com/garyvee/sideways-prod-mad-real -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '~/Downloads/%(title)s.%(ext)s', '--audio-format', 'mp3', '--embed-thumbnail', '--add-metadata', 'https://soundcloud.com/garyvee/sideways-prod-mad-real', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.3 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[soundcloud] garyvee/sideways-prod-mad-real: Resolving id
[soundcloud] garyvee/sideways-prod-mad-real: Downloading info JSON
[soundcloud] 309699954: Downloading track url
[soundcloud] 309699954: Downloading m3u8 information
[soundcloud] 309699954: Checking http_mp3_128_url video format URL
[soundcloud] 309699954: Checking hls_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cf-media.sndcdn.com/2J4HFe1jjmlX.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vMko0SEZlMWpqbWxYLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MTM1OTQ1MDR9fX1dfQ__&Signature=KoNtc2AZglBAzxF9lripmNkyBpa9kSjX0MXbZxYREThuOYYJcM~Zs5ie6C9FU5wPf-Vkv~PXnF1VJpRfNnARIKYE9ahM2h3h-wgQuxqwhOLYOio3wtFssb36U0INUC2LLdCm1v8zv0oQIj7thl3SEBnLfrOwLw6vjHXvfoDKWFPICABVG~aLW~Y5n3tNSC9cA2ZLCuSaFgfmS5bwkss~KscEqUt6iK8amza5H8Q4cTi4LSaNX2q0ERiVULaSuv-xfCOVl9FrU4A-X3J7xp5rt-JouWCZh65qrHREw6KfiQV8YQTx4wY-yPYxHrAFDGZydZk09Yaxchl4UkUDrJy7LA__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ'
[download] /Users/craig/Downloads/Sideways (Prod. Mad Real).mp3 has already been downloaded
[download] 100% of 3.16MiB
[ffmpeg] Adding metadata to '/Users/craig/Downloads/Sideways (Prod. Mad Real).mp3'
[debug] ffmpeg command line: ffmpeg -y -i 'file:/Users/craig/Downloads/Sideways (Prod. Mad Real).mp3' -c copy -metadata 'title=Sideways (Prod. Mad Real)' -metadata date=20170226 -metadata description= -metadata comment= -metadata purl=https://soundcloud.com/garyvee/sideways-prod-mad-real -metadata artist=garyvee 'file:/Users/craig/Downloads/Sideways (Prod. Mad Real).temp.mp3'
ERROR: Thumbnail was not found. Nothing to do.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2032, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 34, in run
    raise EmbedThumbnailPPError('Thumbnail was not found. Nothing to do.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Thumbnail was not found. Nothing to do.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Soundcloud song: https://soundcloud.com/garyvee/sideways-prod-mad-real

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Issue is that some album art is not added from some songs from soundcloud**

Example is this song https://soundcloud.com/garyvee/sideways-prod-mad-real which shows album art on soundcloud.com but this is not added when running `youtube-dl -o '~/Downloads/%(title)s.%(ext)s' --audio-format mp3 --embed-thumbnail --add-metadata https://soundcloud.com/garyvee/sideways-prod-mad-real -v`

**Comment by parmjitv** [comment]
Hi @davisonio,

There does not appear to be any album art associated with this entry on Soundcloud, and hence no thumbnail can be generated by the post-processor.  This can be seen from the raw data fetched from the site by the youtube-dl robot:

{u'reposts_count': 9, u'attachments_uri': u'https://api.soundcloud.com/tracks/309699954/attachments', u'video_url': None, u'track_type': None, u'release_month': None, u'original_format': u'mp3', u'label_name': None, u'duration': 207012, u'id': 309699954, u'streamable': True, u'user_id': 2366352, u'title': u'Sideways (Prod. Mad Real)', u'favoritings_count': 166, u'commentable': True, u'label_id': None, u'download_url': u'https://api.soundcloud.com/tracks/309699954/download', u'state': u'finished', u'downloadable': False, u'policy': u'ALLOW', u'waveform_url': u'https://w1.sndcdn.com/2J4HFe1jjmlX_m.png', u'sharing': u'public', u'description': u'', u'release_day': None, u'purchase_url': None, u'permalink': u'sideways-prod-mad-real', u'comment_count': 1, u'purchase_title': None, u'stream_url': u'https://api.soundcloud.com/tracks/309699954/stream', u'last_modified': u'2017/02/28 14:43:54 +0000', u'user': {u'username': u'garyvee', u'permalink': u'garyvee', **u'avatar_url': u'https://i1.sndcdn.com/avatars-000298106657-ogrgmg-large.jpg'**, u'kind': u'user', u'uri': u'https://api.soundcloud.com/users/2366352', u'last_modified': u'2017/06/23 16:49:10 +0000', u'permalink_url': u'http://soundcloud.com/garyvee', u'id': 2366352}, u'genre': u'', u'isrc': None, u'download_count': 0, u'permalink_url': u'https://soundcloud.com/garyvee/sideways-prod-mad-real', u'playback_count': 18992, u'kind': u'track', u'release_year': None, u'license': u'all-rights-reserved', u'monetization_model': u'NOT_APPLICABLE', **u'artwork_url': None**, u'created_at': u'2017/02/26 23:40:09 +0000', u'bpm': None, u'uri': u'https://api.soundcloud.com/tracks/309699954', u'original_content_size': 8281906, u'key_signature': None, u'release': None, u'tag_list': u'', u'embeddable_by': u'all'}

I believe this page displays the artist avatar instead, which is why youtube-dl is tossing the error about the thumbnail.  If you run the same command with the following URL instead, you will see a proper thumbnail included with the download:

https://soundcloud.com/postmalone/rockstar-feat-21-savage

Cheers,

Parmjit V.

**Comment by davisonio** [comment]
Hi yeah that seems to be the case hmm... shouldn't it download the artist avatar as a 2nd try though? Maybe this is intended behaviour...

**Comment by parmjitv** [comment]
Makes sense - this idea has already been raised in issue #12878.  A new PR has been submitted to address this.

Happy 2018!

**Comment by davisonio** [comment]
Thank you! I'll close this now in favour of the PR you created thanks :)
