### ISSUE TITLE
[openload] re-open #15118

### ISSUE THREAD

**Issue by 360up** [rg3/youtube-dl#15166]
Fix https://github.com/rg3/youtube-dl/commit/620ee8712e264c71b444748c86a51b258818b4a1 worked for a couple of days. Now broken again.

Please re-open https://github.com/rg3/youtube-dl/issues/15118

**Comment by IDerr** [comment]
PR incoming : https://github.com/rg3/youtube-dl/pull/15161

**Comment by bagud** [comment]
Looks like span element holding stream URL changed ID from "streamurl" to "streamurj".

**Comment by yan12125** [comment]
Thanks @bagud. They are really boring LOL

**Comment by steebchen** [comment]
Why not simply check #video[src]? It should always work, regardless of what funny ids they think of, right?

**Comment by bagud** [comment]
Aaargh. I'm working on PHP/PhantomJS implementation of openload link extractor, but phantomjs returns completely useless streamurl, like: "ØﾋVQRS®ﾹð´￘SXﾋA?õﾙÑyl￨eZ0￿ Ó¡'±￟DÔ-". What could I be doing wrong? I understand this is not the place to ask this but any help would be really appreciated.

**Comment by yan12125** [comment]
@bagud: Possibly phantomjs is too old. Version 2.1.1 is known to work.

**Comment by bagud** [comment]
@yan12125 Thanks for replying. It's not that, I'm using the latest version 2.1.1.

It's frustrating because you can easily see the url with standard browser using developer tools, but when the page is rendered with phantomjs the url gets obfuscated?

I'm not python guy, but as much as I can see in your openload extractor code you don't use any additional decoding of the stream url, you just output it as plain text, right?

Also I'm setting only user-agent header, not additonal headers are required in request?

I'll be really grateful for your answer on this or anybody who would be kind enough to help out. :)

**Comment by Hrxn** [comment]
Maybe @Tithen-Firion knows the answer?

**Comment by yan12125** [comment]
> Also I'm setting only user-agent header, no additonal headers are required in request?

A point. openload extraction is sensitive to user-agent. It might be better to avoid another user-agent than the default one.

Anyway pasting full verbose log helps debugging.

**Comment by Tithen-Firion** [comment]
@steebchen no because it's not in `video`'s `src` until you click on specific element. Their JS code is encoded with `aaencode` and some obfuscator. I've got some dirty-sketch of deobfuscator but even if we use it they will change it to something else. 

@bagud take a look at [this](https://gist.github.com/Tithen-Firion/8b3921d745131837519d5c5b95b86440). Keep in mind that video urls work only on the same IP that accessed the site. 

It's the same thing over again. In past they changed how the video url is encoded. Now they change where that url is stored. Of course you can scan all elements searching for specific pattern but it's easy to add dummy ones. What we need is to simulate click event. Tried that with PhantomJS but it failed.

**Comment by steebchen** [comment]
@Tithen-Firion In my browser, it's directly filled in without clicking anything. And even if, maybe you could just click on the play button and wait for it to be filled in.

**Comment by Tithen-Firion** [comment]
Tested `https://openload.co/f/*/` and `https://openload.co/embed/*/` in Firefox, Chrome and PhantomJS. Src not set.

As for the click part: read my previous comment till the end.

**Comment by bagud** [comment]
Thank you all for your suggestions. I managed to solve my problem checking into @Tithen-Firion code.
`page.onInitialized = function() {
  page.evaluate(function() {
    delete window._phantom;
    delete window.callPhantom;
  });
};`
I was missing this part in my code.

I naively assumed setting up custom user agent header would be enough to hide PhantomJS browser, but it's not. You have to manually delete those two references also (which I didn't know existed), otherwise you can be still easily identified as PhantomJS and denied, what openload obviously does check.

@Tithen-Firion I have tried to simulate click event and it fires, eg. I can see element class changes, but there must be something else preventing generation of src attribute. If I come up with something I'll post it.
