### ISSUE TITLE
la7: Unable to extract player data

### ISSUE THREAD

**Issue by Vrihub** [rg3/youtube-dl#15501]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Regex error while downloading from la7.it

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'http://www.la7.it/omnibus/rivedila7/omnibus-04-02-2018-233121']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.04
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-5-amd64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] omnibus-04-02-2018-233121: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/la7.py", line 52, in _real_extract
    self._search_regex(r'videoLa7\(({[^;]+})\);', webpage, 'player data'),
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by avagraha** [comment]
surely there is a duplicate of this new issue of "rivediLa7", but I did not
find the duplicate via Search, search results lead me here, therefore:


C:\Users\agapito>y -v
https://www.la7.it/atlantide/rivedila7/atlantide-con-an
drea-purgatori-paolo-borsellino-depistaggio-di-stato-17-10-2019-287996
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.la7.it/atlantide/rivedila7/a
tlantide-con-andrea-purgatori-paolo-borsellino-depistaggio-di-stato-17-10-2
019-287996']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] atlantide-con-andrea-purgatori-paolo-borsellino-depistaggio-di-sta
to-17-10-2019-287996: Downloading webpage
[Kaltura] 0_hhwjubjw: Downloading video info JSON
ERROR: 0_hhwjubjw: Failed to parse JSON  (caused by ValueError('Expecting v
alue: line 1 column 1 (char 0)',)); please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 899, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\kaltura.py", line 230, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\kaltura.py", line 220, in _get_video_inf
o
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\kaltura.py", line 174, in _kaltura_api_c
all
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 892, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 876, in _download_json_
handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpf
c5s43s4\build\youtube_dl\extractor\common.py", line 903, in _parse_json
youtube_dl.utils.ExtractorError: 0_hhwjubjw: Failed to parse JSON  (caused
by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report
 this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
