### ISSUE TITLE
ERROR: FAIL on afreecatv vods

### ISSUE THREAD

**Issue by coys1031** [rg3/youtube-dl#15507]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.04**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

When I try to execute the address below on afreecatv, I get a fail message

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl http://vod.afreecatv.com/PLAYER/STATION/30523154
[afreecatv] 30523154: Downloading XML
ERROR: afreecatv said: FAIL

youtube-dl http://vod.afreecatv.com/PLAYER/STATION/30507968
[afreecatv] 30507968: Downloading XML
ERROR: afreecatv said: FAIL
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I have tried different websites, but resulted in same issue as above- The word error:fail shows up. 
This my first time writing out an issue- I apologize in advance if any formatting is corrupt.  Thanks for your help!

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/35866721-7b8abcae-0b8a-11e8-9f2e-2dc1b4983e0f.png)

**Comment by coys1031** [comment]
hello, thanks for your reply.  I saw that you showed the locale error.  

However, the same issue exists for a non-locale restricting afreecatv video.  Here is a link:
http://vod.afreecatv.com/PLAYER/STATION/30529210

Thanks for your continued help.

**Comment by vkorablin** [comment]
The reason is that Afreeca no longer gives out correct information in the get_video_info.php API endpoint (which youtube-dl uses).

Consider this video: http://vod.afreecatv.com/PLAYER/STATION/30561002
Before Feb 6, calling this endpoint would give out information about where one could reach the dowloadable files corresponding to the video with that ID: http://afbbs.afreecatv.com:8080/api/video/get_video_info.php?nTitleNo=30561002

But now Afreeca just returns:

<Contents>
<track>
<flag>FAIL</flag>
<message>영상 정보를 찾을 수 없습니다.</message>
</track>
</Contents>

The Korean text means "No image information found." according to google translate.

Not sure what can be done about this, to be honest.

**Comment by coys1031** [comment]
vkorablin,

Thank you for the reply.

I see- I guess they revised their coding to prevent downloading.
It was awesome while it lasted!

Regards,
sam

**Comment by vkorablin** [comment]
After a little bit of investigating, here's what's needed to fix this: Afreeca now requires two new query parameters for the `get_video_info.php` endpoint:

http://afbbs.afreecatv.com:8080/api/video/get_video_info.php?nStationNo=12485253&nBbsNo=24756004&nTitleNo=30561002

This URL works as long as the referer header is set up correctly as well. (As already fixed in https://github.com/rg3/youtube-dl/commit/fde677fed4eb04a493abed333e437bb43786f952 ).

I'm not sure where it's easiest to acquire the `nStationNo` and `nBbsNo` parameters, but one place they're available is in the source code of the video page itself: http://vod.afreecatv.com/PLAYER/STATION/30561002

The `HEAD` element contains a link to an embedded player in a meta tag with, among others, the parameters that we require: `<META property="og:video" content="http://vod.afreecatv.com/embed.php?isAfreeca=false&autoPlay=true&showChat=true&szBjId=momo130&nStationNo=12485253&nBbsNo=24756004&nTitleNo=30561002&szCategory=00010000&szPart=REVIEW&type=station&szSysType=html5" />`

**Comment by coys1031** [comment]
I see. So in a very very high level, if those parameters can be called,
then the endpoints can be retrieved.. interesting changes made from the
AfreecaTV team.

Obviously I am just somebody in the sidelines, so all I can hope is for the
original author to re open this case and implement this change.. but I
appreciate you looking into this!

(Or are you the author or one of the coders responsible? Not aure how the
ids work)

Much thanks,
Sam
