### ISSUE TITLE
Unable to download Udemy courses using youtube-dl

### ISSUE THREAD

**Issue by razahaider** [rg3/youtube-dl#15578]
facing error:
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
URl used:

C:\Users\Haider Raza> youtube-dl -u email@gmail.com -p 'pwd' -o '~E:/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playt_index)s - %(title)s.%(ext)s' https://www.udemy.com/the-modern-python3-bootcamp/learn/

**Comment by razahaider** [comment]
Hi The issue is still there check it please its not working, can you give any resolution Sergey?

**Comment by RobbiNespu** [comment]
Hi @razahaider,  
You not the first report the issue. So that why @dstftw mark this issue duplicate. Plus you report also not follow the given bug template. 

Btw PR patch abe8766c35bb33e4d8ef3dc516ed210f3b4dacd2 has been made for new release. Please update.

or else, as work around ..do append `--user-agent` paratemer like
```
--user-agent 'Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A403 Safari/8536.25'
```
* try change with other user agent. Don't just CP and use.

Should be working fine for old version. Good luck

**Comment by Jighead** [comment]
This does not work either. tried a number of different user-agent strings.. same issue. keep getting 403

**Comment by divyang-desai** [comment]
Updated with latest version and also tried with number of user agents though, same error!

**Comment by RSeidelsohn** [comment]
I have the same issue here. Using the correct user agent and cookies.txt, correct username and password... youtube-dl version 2019.01.17

**Comment by imvikas7526** [comment]
[Please Help] Every Time I Try To Download A Course From Udemy I Get That Error
>youtube-dl.exe -u username -p password https://www.udemy.com/chrome-extension-dev/learn/v4/

[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Unauthorized (caused by <HTTPError 403: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
