### ISSUE TITLE
How to put the files I downloaded to the specified folder

### ISSUE THREAD

**Issue by poppingcode** [rg3/youtube-dl#15865]
How to put the files I downloaded to the specified folder

**Comment by siddht5** [comment]
look here   https://github.com/rg3/youtube-dl#configuration

example:

`youtube-dl -o [folder_path]  [url]`

here :  

-o stands for output
[file_path] stands for the path where you want to download like

`-o ~/Movies/ `    for linux
`-o D:\movies\ ` for windows

[url] for the url from where you want to download

**Comment by rautamiekka** [comment]
2 caveats: you
1. should use double quotes on Window$ and single quotes on NIX around the URL's to protect them against the shell's manipulations.
1. need to use double forward slashes `\\` on Window$ for paths, or just the single backward slash, works fine on both Window$ and NIX since Python processes the paths.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#output-template
