### ISSUE TITLE
Pluralsight downloads

### ISSUE THREAD

**Issue by masteramoebe** [rg3/youtube-dl#16460]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password',
'PRIVATE', '-v', '--min-sleep-interval', '90', '--max-sleep-interval', '120', '-
-limit-rate', '150K', '-o', '%(playlist_index)s - %(title)s.%(ext)s', '--playlis
t-start', '1', 'https://app.pluralsight.com/library/courses/dotnet-standard-gett
ing-started/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.05.09
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] dotnet-standard-getting-started: Downloading course JSON
[download] Downloading playlist: .NET Standard: Getting Started
[pluralsight:course] playlist .NET Standard: Getting Started: Collected 45 video
 ids (downloading 45 of them)
[download] Downloading video 1 of 45
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] 225063f8-d12b-4738-a1df-33d402f03216-0: Downloading course JSON
[pluralsight] 225063f8-d12b-4738-a1df-33d402f03216-0: Downloading mp4-high-wides
creen viewclip JSON
[pluralsight] 225063f8-d12b-4738-a1df-33d402f03216-0: Waiting for 4 seconds to a
void throttling
ERROR: An extractor error has occurred. (caused by KeyError('name',)); please re
port this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\extractor\pluralsight.py", line 336, in _real_extract
KeyError: 'name'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\extractor\pluralsight.py", line 336, in _real_extract
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\bu
ild\youtube_dl\extractor\common.py", line 516, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by Key
Error('name',)); please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; type  youtube-dl -U  to update. Be sure to call
 youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Pluralsight downloads dont seem to work anymore since today.

**Comment by Druopel** [comment]
Can confirm also get same error as of today

**Comment by masteramoebe** [comment]
It only seems to be happening with new pluralsight courses, the name seems to be changed to some kind of guid https://app.pluralsight.com/player?course=dotnet-standard-getting-started&author=thomas-huber&name=225063f8-d12b-4738-a1df-33d402f03216&clip=0&mode=live

**name=225063f8-d12b-4738-a1df-33d402f03216**

**Comment by abdulmoiz** [comment]
Error coming on new courses download as **dotnet-standard-getting-started** has been released on 14th of May, while the older courses download is functional.

**Comment by luizconrado** [comment]
I can confirm I have the same error.
I just test it now with the newest version and also older versions. Same error.
For me older courses also have this error 

ERROR: An extractor error has occurred. (caused by KeyError('name',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\pluralsight.py", line 336, in _real_extract
KeyError: 'name'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\pluralsight.py", line 336, in _real_extract
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 516, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('name',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaan143** [comment]
getting same issue on my side also

**Comment by Druopel** [comment]
whats account needed mean, devs need an account to check? you can get a free 3 month pluralsight account via microsoft visual studio developer essentials

**Comment by jaan143** [comment]
@remitamine  i sent you account details in your email 
kindly check
