### ISSUE TITLE
Would like a command line option to print date strings

### ISSUE THREAD

**Issue by NinKenDo64** [rg3/youtube-dl#16515]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [n/a] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

-------------------------------------

I'd like this for a project I'm doing to better facilitate using org-mode to catalogue YouTube channels using a combination of org-feed and youtube-dl.

I would like to see support for printing date string like pub and upload dates like the options -g and -e. The values are available in JSON and clearly available to the client as I can pass them to the output template. I'd love to have simple native support for just getting the simple date strings out on the cmd. Even better would be an option that could be passed any of the field names and print them, but dates are the main missing feature for me anyway.

**Comment by dstftw** [comment]
No such duplicating functionality will be added. Parse JSON.

**Comment by dstftw** [comment]
`--get-title` was introduces long before `--dump-json` existed. Output template has completely nothing to do with JSON parsing, both are different options with different purpose: the former for consuming data, the latter for managing how files are written on disk.
There are more than 70 meta fields available and it's just pointless to have such amount of redundant options littering `--help` just because someone is comfortable with them and doesn't want to bother with JSON. Needless to say such printing options are non deterministic since you technically can't figure out where the one ends and the following starts in case of multiline meta field values.
So I'll strongly discourage adding new printing options as well as using them. JSON is clear deterministic way of consuming data that does not have aforementioned flaws.
