### ISSUE TITLE
Downloading entire season on NRK broken (patch included)

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#17258]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)

Downloading all episodes in a season in a series on NRK doesn't work.

```
$ youtube-dl --verbose https://tv.nrk.no/serie/zombielars/sesong/1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tv.nrk.no/serie/zombielars/sesong/1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[NRKTVSeason] 1: Downloading webpage
ERROR: Unable to extract config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 450, in _real_extract
    series = self._extract_series(webpage, display_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 407, in _extract_series
    default='{}' if not fatal else NO_DEFAULT),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by forthrin** [comment]
```
ZGlmZiAtLWdpdCBhL3lvdXR1YmVfZGwvZXh0cmFjdG9yL25yay5weSBiL3lvdXR1YmVfZGwvZXh0
cmFjdG9yL25yay5weQppbmRleCBhMjMxNzM1ZmIuLjA2ODAyZjU4NiAxMDA2NDQKLS0tIGEveW91
dHViZV9kbC9leHRyYWN0b3IvbnJrLnB5CisrKyBiL3lvdXR1YmVfZGwvZXh0cmFjdG9yL25yay5w
eQpAQCAtNDA0ICs0MDQgQEAgY2xhc3MgTlJLVFZTZXJpZUJhc2VJRShJbmZvRXh0cmFjdG9yKToK
LSAgICAgICAgY29uZmlnID0gc2VsZi5fcGFyc2VfanNvbigKKyAgICAgICAgaW5pdGlhbCA9IHNl
bGYuX3BhcnNlX2pzb24oCkBAIC00MDYgKzQwNiBAQCBjbGFzcyBOUktUVlNlcmllQmFzZUlFKElu
Zm9FeHRyYWN0b3IpOgotICAgICAgICAgICAgICAgIHInKHsuKz99KVxzKixccyoiW14iXSsiXHMq
XClccyo8L3NjcmlwdD4nLCB3ZWJwYWdlLCAnY29uZmlnJywKKyAgICAgICAgICAgICAgICByJ3dp
bmRvdy5fX05SS19UVl9TRVJJRVNfSU5JVElBTF9EQVRBX18gPSAoey4qfSk7Jywgd2VicGFnZSwg
J2luaXRpYWwnLApAQCAtNDA4LDAgKzQwOSBAQCBjbGFzcyBOUktUVlNlcmllQmFzZUlFKEluZm9F
eHRyYWN0b3IpOgorICAgICAgICBjb25maWcgPSBpbml0aWFsWydpbml0aWFsU3RhdGUnXQo=

```

**Comment by bombaaa** [comment]
@forthrin Patch working for series where all episodes are available, but quits if some has expired rights

Regading issues: #17159 and patched suggested here.

Tried this patch, it's working if all epsiodes are still available in series.
But if only some, and by that I mean that maybe not the 1st and 2nd epsiode is available anymore, but only like episode 5 and 43, they will not be downloaded, cause the program quits after first failure of expired rights.

Output from a series where epsiode 1-7 is not longer available (due to rights)
And where episode 8-20 is still available.
We need the program to skip epsiodes that gives the message "Programmet har gått ut" and move on to try download the next episode.
Now the programs just exits, see code below:

`UBUNTU# youtube-dl --yes-playlist https://tv.nrk.no/serie/thomas-og-vennene-hans
[NRKTVSeries] thomas-og-vennene-hans: Downloading webpage
[download] Downloading playlist: Thomas og vennene hans
[NRKTVSeries] playlist Thomas og vennene hans: Collected 46 video ids (downloading 46 of them)
[download] Downloading video 1 of 46
[NRK] MSUI21004115: Downloading mediaelement JSON
ERROR: NRK said: Programmet har gått ut
UBUNTU#`



Output from a series where 5 of 5 epsiodes in series are available:

`UBUNTU# youtube-dl --yes-playlist https://tv.nrk.no/serie/uten-pappa
[NRKTVSeries] uten-pappa: Downloading webpage
[download] Downloading playlist: Uten pappa
[NRKTVSeries] playlist Uten pappa: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[NRK] MYNT13000118: Downloading mediaelement JSON
[NRK] MYNT13000118: Downloading f4m manifest
[NRK] MYNT13000118: Downloading m3u8 information
[download] Downloading playlist: Uten pappa 1:5
[NRK] playlist Uten pappa 1:5: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 158
[download] Destination: Uten pappa 1_5-MYNT13000118AA.mp4
[download] 100% of 467.96MiB in 00:15
[ffmpeg] Fixing malformed AAC bitstream in "Uten pappa 1_5-MYNT13000118AA.mp4"
[download] Finished downloading playlist: Uten pappa 1:5
[download] Downloading video 2 of 5
[NRK] MYNT13000218: Downloading mediaelement JSON
[NRK] MYNT13000218: Downloading f4m manifest
[NRK] MYNT13000218: Downloading m3u8 information
[download] Downloading playlist: Uten pappa 2:5
[NRK] playlist Uten pappa 2:5: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 139
[download] Destination: Uten pappa 2_5-MYNT13000218AA.mp4
[download] 100% of 411.37MiB in 00:13
[ffmpeg] Fixing malformed AAC bitstream in "Uten pappa 2_5-MYNT13000218AA.mp4"
[download] Finished downloading playlist: Uten pappa 2:5
[download] Downloading video 3 of 5
[NRK] MYNT13000318: Downloading mediaelement JSON
[NRK] MYNT13000318: Downloading f4m manifest
[NRK] MYNT13000318: Downloading m3u8 information
[download] Downloading playlist: Uten pappa 3:5
[NRK] playlist Uten pappa 3:5: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 149
[download] Destination: Uten pappa 3_5-MYNT13000318AA.mp4
[download] 100% of 439.15MiB in 00:14
[ffmpeg] Fixing malformed AAC bitstream in "Uten pappa 3_5-MYNT13000318AA.mp4"
[download] Finished downloading playlist: Uten pappa 3:5
[download] Downloading video 4 of 5
[NRK] MYNT13000418: Downloading mediaelement JSON
[NRK] MYNT13000418: Downloading f4m manifest
[NRK] MYNT13000418: Downloading m3u8 information
[download] Downloading playlist: Uten pappa 4:5
[NRK] playlist Uten pappa 4:5: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 149
[download] Destination: Uten pappa 4_5-MYNT13000418AA.mp4
[download] 100% of 439.38MiB in 00:14
[ffmpeg] Fixing malformed AAC bitstream in "Uten pappa 4_5-MYNT13000418AA.mp4"
[download] Finished downloading playlist: Uten pappa 4:5
[download] Downloading video 5 of 5
[NRK] MYNT13000518: Downloading mediaelement JSON
[NRK] MYNT13000518: Downloading f4m manifest
[NRK] MYNT13000518: Downloading m3u8 information
[download] Downloading playlist: Uten pappa 5:5
[NRK] playlist Uten pappa 5:5: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 174
[download] Destination: Uten pappa 5_5-MYNT13000518BA.mp4
[download] 100% of 515.39MiB in 00:17
[ffmpeg] Fixing malformed AAC bitstream in "Uten pappa 5_5-MYNT13000518BA.mp4"
[download] Finished downloading playlist: Uten pappa 5:5
[download] Finished downloading playlist: Uten pappa
UBUNTU#`

**Comment by remitamine** [comment]
@bombaaa
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by bombaaa** [comment]
> @bombaaa
> 
> ```
> -i, --ignore-errors              Continue on download errors, for example to
>                                  skip unavailable videos in a playlist
> ```

Embarrassed :S
