### ISSUE TITLE
[Discovery] Add former Scripps channels

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#17947]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
E:\>youtube-dl "https://watch.foodnetwork.com/tv-shows/trishas-southern-kitchen/full-episodes/trishas-space-kitchen" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://watch.foodnetwork.com/tv-shows/trishas-southern-kitchen/full-episodes/trishas-space-kitchen', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-89980-ge752da5464, ffprobe N-89980-ge752da5464, rtmpdump 2.4
[debug] Proxy map: {}
[generic] trishas-space-kitchen: Requesting header
WARNING: Falling back on generic information extractor.
[generic] trishas-space-kitchen: Downloading webpage
[generic] trishas-space-kitchen: Extracting information
ERROR: Unsupported URL: https://watch.foodnetwork.com/tv-shows/trishas-southern-kitchen/full-episodes/trishas-space-kitchen
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.foodnetwork.com/tv-shows/trishas-southern-kitchen/full-episodes/trishas-space-kitchen
```

---

Discovery purchased Scripps earlier this year and some channels have been updated to use the Discovery format.  The Discovery extractor needs to be updated to recognize the new URLs.

Updated:
watch.foodnetwork.com
watch.hgtv.com

Not updated yet:
watch.cookingchannel.com
watch.diynetwork.com
watch.travelchannel.com

**Comment by tv21** [comment]
I tested VietTPham's patch but now I get "ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies."  I am giving the login credentials for my provider (spectrum), which work for non-Discovery channels but for some reason apparently not with Discovery channels (and those channels are part of my package so that is not the problem).  Those may fix the issue for those that are able to authenticate, though.

**Comment by StevenDTX** [comment]
The --ap-mso stuff has never worked with Discovery channels. You must use cookies.

**Comment by tv21** [comment]
How do you do that?  I've never understood that at all.

**Comment by tv21** [comment]
Thanks - I never had any idea how to do that but found the instructions at https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl and now it does work with VietTPham's patch.

**Comment by timethrow** [comment]
Does that mean you need to sign in with a provider to get the cookie?

**Comment by tv21** [comment]
Yes, you have to be able to login to the web site using a provider account.

**Comment by sydbat** [comment]
So this means that all the people who have dropped cable are no longer able to watch videos on HGTV (and other Discovery websites I imagine) because you require a cable subscription to sign in? There are no free videos to watch there since the site switched over last week. I also suppose there is no way of getting the cookie required without signing in, which means having to get cable again, which means what is the point.

**Comment by timethrow** [comment]
Been testing the patch further with Free Videos, and every 1 hour or so I get this.

`ERROR: Access to the requested resource path is unauthorized: v1/streaming/video/<videoID> [The access token provided has expired]; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/discovery.py", line 89, in _real_extract
    'Authorization': 'Bearer ' + access_token,
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 865, in _download_json
    expected_status=expected_status)
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 843, in _download_json_handle
    expected_status=expected_status)
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 633, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 618, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)

ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/user/Downloads/youtube-dl/youtube_dl/extractor/discovery.py", line 101, in _real_extract
    raise ExtractorError(e_description)

ExtractorError: Access to the requested resource path is unauthorized: v1/streaming/video/5b3245a56b66d1445e0ddada [The access token provided has expired]; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

It looks like the access token is not quite refreshing as expected, run the download a few more time and eventually it will pick up again. It does not appear to be related to any particular video. Is this related to the sites (HGTV and FoodNetwork) or is this a quirk of the Discovery downloader.

**Comment by NEET-Engineer** [comment]
Cooking Channel has updated to:
https://watch.cookingchanneltv.com/tv-shows/good-eats-reloaded/full-episodes/for-whom-the-cheese-melts

**Comment by domsmrc** [comment]
Travel Channel also updated their site. For example:
https://watch.travelchannel.com/tv-shows/ghost-adventures/full-episodes/manresa-castle
Please, add support for this site also. Thank you in advance.

**Comment by ricknorton** [comment]
DIY Network has changed to this Discovery system as well:
https://watch.diynetwork.com/tv-shows/

**Comment by Danielperalta07** [comment]
Hello, [DIY Network] is not working.

Does someone has a solution? 

`>youtube-dl --write-sub -a list.txt --cookies cookies.txt -v -C
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-sub', '-a', 'list.txt', '--cookies', 'cookies.txt', '-v', '-C']
[debug] Batch file urls: ['https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/building-off-the-grid', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/alaska', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/north-pole', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/yurts-so-good', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/gnome-sweet-home', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/rocky-mountains', 'https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/alaska-range']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[debug] Public IP address: xxx.xxx.xxx.xxx
[generic] building-off-the-grid: Requesting header
WARNING: Falling back on generic information extractor.
[generic] building-off-the-grid: Downloading webpage
[generic] building-off-the-grid: Extracting information
ERROR: Unsupported URL: https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/building-off-the-grid
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\generic.py", line 3323, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.diynetwork.com/tv-shows/building-off-the-grid/full-episodes/building-off-the-grid`

**Comment by PlaceboPRS** [comment]
Is there an idiots guide anywhere on how to get/use cookies please? I have a cable account and would love to be able to download HGTV shows but haven't been possible since their format changed :(

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by PlaceboPRS** [comment]
> 
> 
> https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

Yes I've read that previously thanks and when I tried it didn't work for me, hence asking for an idiots guide as obviously I'm an idiot if others can get HGTV working and I can't.

**Comment by PlaceboPRS** [comment]
> 
> 
> the process is as simple as it's been explained in the mentioned link, export cookies with a supported extension and pass them to youtube-dl with `--cookies` option, if that didn't work then you can start by providing more information about the error you're getting(verbose log and used cookie file with values changed).

You're absolutely right it's as simple as that, I must have screwed my cookies path or something, worked perfectly just now! So happy thanks :)

**Comment by timethrow** [comment]
Am using the cookies method fine, but its a bit tedious as you have to renew it pretty much every hour or so. Is there anyway to automate it a bit more, been looking at the discovery extractor but not been able to find a ways to get it to refresh and get the new cookies.

**Comment by PlaceboPRS** [comment]
> 
> 
> Am using the cookies method fine, but its a bit tedious as you have to renew it pretty much every hour or so. Is there anyway to automate it a bit more, been looking at the discovery extractor but not been able to find a ways to get it to refresh and get the new cookies.

Another option is to use a browser user agent addon to change to something like Android or ipad and depending on which provider you're trying to use they may give you simply URLs, this works with some of the sites I've been having problems with and for at least one of them I don't need to go down the cookie file path with the URLs.
