### ISSUE TITLE
National Geographic has changed their url, youtube-dl cannot detect the new link

### ISSUE THREAD

**Issue by tranminhche** [rg3/youtube-dl#17985]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-sub', '--cookies', 'C:\\Users\\minhd\\Desktop\\cookes.txt', '-v', 'https://www.nationalgeographic.com/tv/watch/b8dab72a633e5ce69d541247248cde52/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-91865-g404d21f486, ffprobe N-91865-g404d21f486
[debug] Proxy map: {}
[generic] b8dab72a633e5ce69d541247248cde52: Requesting header
WARNING: Falling back on generic information extractor.
[generic] b8dab72a633e5ce69d541247248cde52: Downloading webpage
[generic] b8dab72a633e5ce69d541247248cde52: Extracting information
ERROR: Unsupported URL: https://www.nationalgeographic.com/tv/watch/b8dab72a633e5ce69d541247248cde52/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.nationalgeographic.com/tv/watch/b8dab72a633e5ce69d541247248cde52/
...
<end of log>
```

https://www.nationalgeographic.com/tv/watch/b8dab72a633e5ce69d541247248cde52/
Above is the link of the video I want to download. However, when I try to use youtube-dl, it says "ERROR: Unsupported URL"

Thank you so much

**Comment by Bstark07** [comment]
When you try and play the video url: https://www.nationalgeographic.com/tv/watch/b8dab72a633e5ce69d541247248cde52/

Do you get a geolocking error such as not available in this region?

**Comment by Bstark07** [comment]
Judging from the error, youtube-dl does not support national geographic video links.

I'd recommend reading this section of the FAQ,  (https://github.com/rg3/youtube-dl/blob/master/README.md#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)

":As a matter of policy (as well as legality), youtube-dl does not include support for services that specialize in infringing copyright. As a rule of thumb, if you cannot easily find a video that the service is quite obviously allowed to distribute (i.e. that has been uploaded by the creator, the creator's distributor, or is published under a free license), the service is probably unfit for inclusion to youtube-d"

The National Geographic Terms and Conditions state:

Trademark & Copyright Notice: ™ and © 2018 National Geographic Partners, LLC. All rights reserved. Use of this Website (including any and all parts and components) constitutes your acceptance of these TERMS OF USE and PRIVACY POLICY. AD CHOICES

NG Content contained in the Services is protected by copyright, trademark, patent, trade secret and other laws and, as between you and National Geographic Partners, National Geographic Partners, its licensors, or its assignors, own and retain all rights in the NG Content and Services. National Geographic Partners hereby grants you a limited, revocable, nonsublicensable, nontransferable license, to access and display or perform the NG Content (excluding any software code) solely for your personal, non-commercial use, in connection with using the Services. The Services may also contain User Content. Except as provided in this Agreement or as explicitly allowed in the Additional Terms on the applicable Service, you may not copy, download, stream capture, reproduce, duplicate, archive, upload, modify, translate, publish, broadcast, transmit, retransmit, distribute, perform, display, sell, frame or deep-link, make available or otherwise use any Content contained in or through the Services.

**Comment by tv21** [comment]
This and #18325 appear to be the exact same issue, if you can fix it for one you can probably use the same approach to fix the other.

**Comment by Danielperalta07** [comment]
Same problem here. Says "unsupported URL".

**Comment by Danielperalta07** [comment]
Help? Someone? =/

**Comment by Danielperalta07** [comment]
I can provide login credentials if needed..

**Comment by ParadoxGBB** [comment]
I just confirmed by merging the above changelist that I was able to grab "Valley of the Boom". Thanks, @remitamine!

**Comment by msgongora** [comment]
@remitamine This is still happening with 96c186e
```
youtube-dl -v  --ap-mso Comcast_SSO --ap-username PRIVATE --ap-password PRIVATE "https://www.nationalgeographic.com/tv/watch/0a9a2ad6ee724495963ff14aee027df0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.nationalgeographic.com/tv/watch/0a9a2ad6ee724495963ff14aee027df0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] 0a9a2ad6ee724495963ff14aee027df0: Downloading JSON metadata
[FOX] 0a9a2ad6ee724495963ff14aee027df0: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/fox.py", line 93, in _real_extract
    url, video_id, 'fbc-fox', resource)
  File "./youtube-dl/youtube_dl/extractor/adobepass.py", line 1448, in _extract_mvpd_auth
    self._DOWNLOADING_LOGIN_PAGE)
  File "./youtube-dl/youtube_dl/extractor/adobepass.py", line 1360, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
@msgongora #11257.
