### ISSUE TITLE
Defaul Referer

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#1854]
Is it possible to add a default referer which is the site name. If using you tube it will be youtube.com. If vimeo it will be vimeo.com

**Comment by DrMcCoy** [comment]
I'd very much like a CLI argument to explictly set the HTTP referer.

Vimeo, for example, has a setting where uploaders can say that a video is only accessible through an embed from a specific domain. They check that by looking at the referer; I often run into problems there because I have referer disabled by default through the Firefox extension RefControl.

**Comment by DrMcCoy** [comment]
And if you want an example, [this video here](https://aeon.co/videos/there-s-a-lot-more-to-conversation-than-words-what-really-happens-when-we-talk) is where I ran into it just now.

**Comment by jaimeMF** [comment]
@DrMcCoy Have you tried the [--referer option](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#workarounds)? If that doesn't work, open a new issue.

**Comment by DrMcCoy** [comment]
Oh, you're right, this is exactly what I asked for. And it works, too. My bad! :)

Seems like my system's manpage for youtube-dl is outdated, and so the option wasn't listed there when I checked.
