### ISSUE TITLE
Youtube Premiere still screws up downloading of Videos.

### ISSUE THREAD

**Issue by GregoriusT** [rg3/youtube-dl#18578]
Because my properly reported Issue got ignored to hell, under the false accusation of posting a duplicate without telling where the original report was whatsoever, I am going to try to report it again, making it a real duplicate, and if this one gets ignored or instant closed again I am gonna give up.

https://github.com/rg3/youtube-dl/issues/18416

This Line will reproduce the Issue during the next two and a half hours:
youtube-dl "https://www.youtube.com/user/Lanipator/videos" --playlist-end 1

The Stats and the Issue themselves are still identical to my original Report that I already linked, and I did update youtube-dl again right before testing this Issue, and it still persists.

**Comment by dstftw** [comment]
1. Downloading live streams is expected behavior. It does not download "random parts", it downloads a live stream from now on. Skipping live streams with `--match-filter` is your responsibility if you don't need such behavior.
2. As for "screwing up". Incomplete/[corrupted](https://github.com/rg3/youtube-dl/issues/#14882)/whatever download may happen due to numerous reasons. Provide concrete verbose logs clearly demonstrating such cases. Log from the previous issue does not show any problem with downloading.

**Comment by GregoriusT** [comment]
Thank you for pointing me to the right general direction instead of just ignoring me.

"--match-filter !is_live" works so far for Youtube Premiere Videos. Lets hope it will work once the thing is out normally. I initially did not expect --match-filter to be the solution whatsoever when I have read through the Instructions.

And yes it was getting the Video from the point in time at which it was "live", which I considered corrupted, so this can be marked as solved.
