### ISSUE TITLE
youtube-dl - iView no longer copies links to clipboard

### ISSUE THREAD

**Issue by greenyellowdawn** [rg3/youtube-dl#19259]
Just a note that when using youtube-dl this morning, ABC iView no longer copies the link to your clipboard.  This is when a user goes into iView, seeks out the relevant program, clicks the down arrow to reveal "email this" and :"copy link".  Both result in a generic abc link (https://iview.abc.net.au/show/world#) and there is no program specific id'er at the end of the url.  Looks like people at the ABC have too much time on there hands again. :(

**Comment by thn7** [comment]
youtube-dl>youtube-dl.exe --verbose https://iview.abc.net.au/show/w1a/series/3/video/ZW1410A001
S00Updated youtube-dl to version 2019.02.18.

The batch file cannot be found.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://iview.abc.net.au/show/w1a/series/3/video/ZW1410A001S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6001-SP1
[debug] exe versions: ffmpeg N-70125-g6c9537b
[debug] Proxy map: {}
[debug] Using fake IP 1.150.227.55 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW1410A001S00: Downloading JSON metadata
[abc.net.au:iview] ZW1410A001S00: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https:
//yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", lin
e 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2225,
 in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

> worked two days ago

**Comment by greenyellowdawn** [comment]
Just making sure we are on the same page here.  There is nothing wrong with the program itself, Downloading from youtube itself is fine.    ABC have changed their iView system, so users can't no longer obtain program links for downloading specific shows.  Just trying to copy a link from iView into notepad shows the same generic link for every episode.

**Comment by remitamine** [comment]
> ABC iView no longer copies the link to your clipboard.

no, there is not change on the website.

**Comment by greenyellowdawn** [comment]
Okay, thanks.  Just installed firefox, and the links came up okay, so maybe a google chrome thing. :) :)
