### ISSUE TITLE
can we get Grooveshark working?

### ISSUE THREAD

**Issue by lacostenycoder** [rg3/youtube-dl#1968]
is this hard to do?

**Comment by ariasrodolfo** [comment]
https://github.com/gsteph/groove-dl

**Comment by phihag** [comment]
Grooveshark support has been present since youtube-dl 2014.08.26. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by Kokxx** [comment]
You should consider reopening this. The grooveshark extractor does only support downloading single songs. It would be a great improvement if it could actually download entire albums or artists. This unfortunately doesn't work yet.

Example URLs:
Artist: [grooveshark.com/#!/artist/Eminem/276](grooveshark.com/#!/artist/Eminem/276)
Album: [http://grooveshark.com/#!/album/Relapse/2925887](http://grooveshark.com/#!/album/Relapse/2925887)

**Comment by phihag** [comment]
@Kokxx As mentioned in our [bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#does-the-issue-involve-one-problem-and-one-problem-only), we strongly prefer opening new issues for new topics, in this case extending the grooveshark extractor. Otherwise, a lot of additional burden is placed upon us, both in tracking which part of an issue has yet to be implemented and in answering confused users who tend to post in that issue. So feel free to [open a new issue](https://github.com/rg3/youtube-dl/issues/new?title=[grooveshark]%20Support%20albums%20and%20artists&body=The+grooveshark+extractor+does+only+support+downloading+single+songs.+It+would+be+a+great+improvement+if+it+could+actually+download+entire+albums+or+artists.+This+unfortunately+has+not+been+implemented+yet.%0A%0AExample+URLs%3A%0AArtist%3A+%5Bgrooveshark.com%2F%23%21%2Fartist%2FEminem%2F276%5D%28grooveshark.com%2F%23%21%2Fartist%2FEminem%2F276%29%0AAlbum%3A+%5Bhttp%3A%2F%2Fgrooveshark.com%2F%23%21%2Falbum%2FRelapse%2F2925887%5D%28http%3A%2F%2Fgrooveshark.com%2F%23%21%2Falbum%2FRelapse%2F2925887%29%0A) if you are interested in grooveshark album/artist support.
