### ISSUE TITLE
youtube-dl not working

### ISSUE THREAD

**Issue by ram1123** [rg3/youtube-dl#2172]
ramkrishna@ramkrishna$ youtube-dl -t "http://www.youtube.com/watch?v=qT4nc92yQRM&list=PLDCA0C59984F46527"
[youtube:playlist] Downloading playlist PLPLDCA0C59984F46527 - add --no-playlist to just download video qT4nc92yQRM
[youtube:playlist] PLDCA0C59984F46527: Downloading page #1
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out>
ramkrishna@ramkrishna$ youtube-dl --version
2014.01.17.2
ramkrishna@ramkrishna$ python --version
Python 2.7.3

**Comment by ArchieGu** [comment]
Hi,
This is the information I got. Could you please tell me what went wrong?
Cus the crawler keeps telling me url does not exist.

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=qT4nc92yQRM&list=PLDCA0C59984F46527']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-1019-azure-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.0.2-static, ffprobe 4.0.2-static
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLDCA0C59984F46527 - add --no-playlist to just download video qT4nc92yQRM
[youtube:playlist] PLDCA0C59984F46527: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out'),))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 1102, in https_open
    req, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)`

Thank you.
