### ISSUE TITLE
Embed video thumbnails in audio files as cover art

### ISSUE THREAD

**Issue by dequis** [rg3/youtube-dl#2404]
So I found that the `-f bestaudio` feature downloads m4a files from youtube, which is great, but I'm missing my thumbnails. m4a files support embedding images in them, and video players such as mpv show those images as a static replacement of the video stream. Just like most of the music in video sites, but with a jpeg instead of a video with a single repeated frame.

I was considering writing a small script to get those files with `youtube-dl --get-thumbnail` and then embed them with [AtomicParsley](http://atomicparsley.sourceforge.net/) (a mpeg4 metadata manipulator, as [this page](http://stackoverflow.com/questions/17798709/ffmpeg-how-to-embed-cover-art-image-to-m4a) suggests it's [not working with ffmpeg](http://trac.ffmpeg.org/ticket/2798)), but then realized it would be a good feature to have as part of youtube-dl, since it already has features to add metadata to the video.

Does this sound like a desirable feature? Is the dependency with AtomicParsley an issue? If it's ok, I might go ahead and implement it, then send a PR later.

**Comment by nullvideo** [comment]
@cup, is right because **AtomicParsley** is not only the program that is able to embed metadata into a MPEG4 file. There are several others that do the same job. One worse or better than another. But, it seems the method of using **AtomicParsley** is quite easy because they provide pre-built binaries on their website.
