### ISSUE TITLE
Feature request: retrieve Brightcove videos when they're specified in an object (not just in an og:video property)

### ISSUE THREAD

**Issue by jillh510** [rg3/youtube-dl#2754]
The page at http://www.nytimes.com/news/minute/2014/03/17/times-minute-whats-next-in-crimea/?_php=true&_type=blogs&_php=true&_type=blogs&_r=1 contains Brightcove content, but the data (http://c.brightcove.com/services/viewer/federated_f9?&width=100%25&height=100%25&flashID=nytd_video_embed_rnd402816803&%40videoPlayer=ref%3A100000002771961&playerID=760102458001&bgcolor=%23000000&publisherID=1749339200&isVid=true&isUI=true&wmode=transparent&dynamicStreaming=true&optimizedContentLoad=true&AllowScriptAccess=always&useExternalAdControls=true&autoStart=true&includeAPI=false&templateErrorHandler=nytd_video_embed_rnd402816803_template_error_handler&quality=high&%40videoList=&templateLoadHandler=nytd_video_embed_rnd402816803_template_load_handler&debuggerID=&startTime=1397669708544) is specified as the data of an object of type 'application/x-shockwave-flash', rather than as the content of an og:video property.

**Comment by yan12125** [comment]
@jillh510 New York Times now uses their own site instead of brightcove to host videos, and youtube-dl will support such cases in the next version.

@Tomtomgo The video you provided now uses og:video property, so it's supported by youtube-dl.

I'm closing this issue because all videos mentioned here can be downloaded without any problem. If anyone finds another video with unhandled brightcove videos, feel free to open a new issue and paste the URLs.
