### ISSUE TITLE
Support for (and ability to recode to) Matroska (.mkv)

### ISSUE THREAD

**Issue by Qazerowl** [rg3/youtube-dl#3228]
The Matroska Multimedia Container (.mkv file) is a freely licensed multimedia container that supports every video and audio format and supports other features like multiple subtitles, 3D video, and chapters/bookmarks. This makes it objectively better than MPEG-4 (.mp4 file) in every way, except widespread compatibility.

Adding support for the .mkv container would allow any form of encoding to support 3D video and multiple subtitles, support a more open standard, and easily allow for consistency among those who use Matroska for all other videos.

**Comment by nwgat** [comment]
i have a related question
do the reencode to mkv affect the video?
wouldn't remuxing be a better idea?

most flv streams are h264 with upto L4.1 and mkv supports that already since its made to contain anything

remuxing means that you DO not touch the video/audio, recoding means you will affect the quality of video/audio, so my question is, wouldnt it be useful to have a flv > mkv remux, you can do this with ffmpeg using `ffmpeg -i input.flv -c copy -map 0 output.mkv` as command

so i would like a --remux-mkv option that basicly just does this
takes the stream flv and passes it thru ffmpeg with the above options

**Comment by jaimeMF** [comment]
@nwgat Open a new issue for that.

**Comment by rzr** [comment]
@nwgat did you reported new issue about mkv support  ? that one is related to mkv too : 
https://github.com/rg3/youtube-dl/issues/6185

Env var are welcome too

**Comment by chkuendig** [comment]
isn't this easily achievable with some simple argumens?
` --recode-video=mkv --postprocessor-args "-v verbose -c copy -map 0" `
