### ISSUE TITLE
vimeo.com: Support for embed-only videos

### ISSUE THREAD

**Issue by bkircher** [rg3/youtube-dl#3582]
The error message is clear but how can I circumvent it? There is no page that embeds this video.

$ youtube-dl -ct -v http://vimeo.com/user22258446/review/91613211/13f927e053
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-ct', '-v', 'http://vimeo.com/user22258446/review/91613211/13f927e053']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.23
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[vimeo] 91613211: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 218, in _real_extract
    webpage = self._download_webpage(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 283, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 223, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 211, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 520, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 227, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

Original page: http://devweek.com/2014/assets.html

**Comment by palashcode** [comment]
same problem with 2016.08.31

**Comment by 2wenty2wo** [comment]
Can confirm, also having this problem with Vimeo videos after updating YouTube-DL.

**Comment by yan12125** [comment]
@palashcode @2wenty2wo Could you paste your commands and logs?

**Comment by 2wenty2wo** [comment]
@yan12125 Sure, I just ran it again with the "-v" command, I'm not sure if that's the log you're talking about. Thank you for the super quick reply :)

---------

youtube-dl -v https://player.vimeo.com/video/166756641
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://player.vimeo.com/video/166756641']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 2.7.11 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 166756641: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 409, in _real_extract
    webpage = self._download_webpage(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 403, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 418, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

**Comment by yan12125** [comment]
How did you get the URL https://player.vimeo.com/video/166756641? Is it embedded in another website?

**Comment by 2wenty2wo** [comment]
Yeah it's embedded on https://www.heyhey.tv/exclusive-member-vid/1984-episode-39/
I paid legally to get all the old Australian TV "Hey Hey It's Saturday" episodes and I've been downloading them for my Dad. It's been downloading fine until I updated youtube-dl tonight. Now I get that error.

**Comment by yan12125** [comment]
Could you try:
```
youtube-dl -v "https://player.vimeo.com/video/166756641" --referer "https://www.heyhey.tv/exclusive-member-vid/1984-episode-39/"
```

**Comment by 2wenty2wo** [comment]
Thanks @yan12125 that did work. Just going to take ages now that I have to add a referer. 40+ more videos to go haha. Thanks again.

**Comment by ddmee** [comment]
Hey, I had this same error with Vimeo, for a paid-for video: 'ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video'.

Using this method was successful:   Woot! 
`youtube-dl -v "https://player.vimeo.com/video/166756641" --referer "https://www.heyhey.tv/exclusive-member-vid/1984-episode-39/"
`

Perhaps it is a good idea to add something about this into some documentation somewhere?

**Comment by therohanchawla** [comment]
@2wenty2wo u can always create a .txt file for batch command

**Comment by aleksandersumowski** [comment]
I'm still having this issue. Anyone could help me to work out whats happening?

youtube-dl -v https://player.vimeo.com/video/245919510?api=1\&title=1 --referer=\"https://skillsmatter.com/skillscasts/10935-thrilled-to-have-bozhidar-batsov-with-us-for-a-community-update-on-cider-at-clojurex-2017\"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://player.vimeo.com/video/245919510?api=1&title=1', u'--referer="https://skillsmatter.com/skillscasts/10935-thrilled-to-have-bozhidar-batsov-with-us-for-a-community-update-on-cider-at-clojurex-2017"']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.10 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[vimeo] 245919510: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 470, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 535, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 515, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 484, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

**Comment by TechieGenie** [comment]
In the place of referer argument, value need not be the complete URL. Just the website name is enough.
