### ISSUE TITLE
Download just dash manifest?

### ISSUE THREAD

**Issue by nschwermann** [rg3/youtube-dl#3763]
I'm not really interested in the video, I just want the dash manifest. But adding --youtube-include-dash-manifest to the command doesn't seem to even save the manifest and it also still downloads the video. Is there a way to get just the manifest? Is this manifest API documented anywhere? Do I even need youtube-dl to get it?
Thanks!

**Comment by Avbrella** [comment]
As youtube-dl also downloads annotations, thumbnails, and descriptions is this now a valid feature request or is the preceding solution good enough?

**Comment by dhesson** [comment]
@schwiz not sure if this'll help you (it's been so long since you asked), but I branched the latest version and added dash manifest urls to the result data.  Also, I'm no python master, so I just did it however so I can have dash mpds, lol.  I commented out a lot of the extractors (we only use youtube), so I wouldn't use my fork.

https://github.com/dhesson/youtube-dl/commit/2d0e886e592e6fbb68362c67366fedf25518b64b

**Comment by jjhesk** [comment]
@diegosuarez does it have official support command now?

**Comment by yan12125** [comment]
FYI: ```manifest_url``` is now exported:
```
$ youtube-dl -j iVAgTiBrrDA | jq '.formats[0].manifest_url'
"https://manifest.googlevideo.com/..."
```

**Comment by jjhesk** [comment]
@yan12125  wow you are so fast! bravo

**Comment by Khang-NT** [comment]
Some videos is missing dash manifest URL, for instance:
`youtube-dl -j kCd72das64k`

Does anyone know why?

**Comment by yan12125** [comment]
@Khang-NT: There are no MPD-based formats in kCd72das64k. Actually they're uncommon in non-live YouTube videos.

**Comment by Lee-Carre** [comment]
@jjhesk

> Where do i get `jq`

* [`jq` website](//stedolan.github.io/jq/)
* [`jq` source repo](//github.com/stedolan/jq)
