### ISSUE TITLE
A way to download subtitles without downloading the video

### ISSUE THREAD

**Issue by foresto** [rg3/youtube-dl#3806]
I downloaded a video from crunchyroll only to find that the subtitles were not downloaded. It would be nice if I could now download the subtitles without having to transfer the entire video again, but I don't see any such option.

I'm testing with this page:
http://www.crunchyroll.com/yamishibai-japanese-ghost-stories/episode-2-zanbai-641889

This is on version 2014.08.05.

**Comment by jaimeMF** [comment]
The subtitles behaviour in the last version should be better: with just `--write-sub` it will download only the english subtitles, with `--sub-lang` or `--all-langs` it will download others.

If you only want to download the subtitles just run `youtube-dl 'http://www.crunchyroll.com/yamishibai-japanese-ghost-stories/episode-2-zanbai-641889' --skip-download --write-sub`:
```
[Crunchyroll] 641889: Downloading webpage
[Crunchyroll] 641889: Downloading media info
[Crunchyroll] 641889: Downloading media info for 360p
[Crunchyroll] 641889: Downloading media info for 480p
[Crunchyroll] 641889: Downloading media info for 720p
[Crunchyroll] 641889: Downloading media info for 720p
[Crunchyroll] 641889: Downloading media info for 1080p
[Crunchyroll] 641889: Downloading media info for 1080p
[Crunchyroll] 641889: Downloading subtitles for English (US)
[Crunchyroll] 641889: Downloading subtitles for Español
[Crunchyroll] 641889: Downloading subtitles for Español (España)
[Crunchyroll] 641889: Downloading subtitles for Français (France)
[Crunchyroll] 641889: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Yamishibai - Japanese Ghost Stories Episode 2 – Zanbai-641889.enUS.ass
```
It shouldn't matter if the video has already been downloaded or not.

Since I think the solution is enough, I'm closing the issue. Thanks for the report.
