### ISSUE TITLE
-j and --write-description now incompatible with each other?

### ISSUE THREAD

**Issue by joeschmoe40** [rg3/youtube-dl#4053]
I have a script that runs youtube-dl like this:

youtube-dl.py  -j --write-description -o tmptmp "$url" | something ...

The objective of the above line is to write the description to the file "tmptmp.description" as well as to write the "json" data to the standard output (it is piped into some further program(s) that analyze the json data).

This was working correctly as recently as October 23rd (2014), but got broken some time after that (in particular, it is broken in the 10/27/2014 version).  Now, I get no "tmptmp.description" file.  Note that no error message is generated; it just silently ignores it.  If I remove "-j" form the command line, then it works as before.  So, it seems like it is a "one or the other, but not both" situation.

I would like to see the previous behavior restored.  I have work-around-ed it in my script, but I'd prefer it work the way it used to.

Note: This is all on Mac OSX, using the Unix command line.

**Comment by jaimeMF** [comment]
Sorry for the delay. In the next version the `_filename` field will always exist, thanks for reporting it. 

About the `\n`, they are perfectly fine in json, I don't know which programming language are you using for processing the output, but it will probably have json libraries. For shell scripts I recommend using [jq](https://stedolan.github.io/jq/).

About the description differences, for the test video http://www.youtube.com/watch?v=BaW_jenozKc, they look identical to me:
```shell
$﻿ ﻿﻿﻿﻿youtube-dl test:youtube -j | jq .description -r
test chars:  "'/\ä↭𝕐
test URL: https://github.com/rg3/youtube-dl/issues/1892

This is a test video for youtube-dl.

For more information, contact phihag@phihag.de .
```
```shell
$ ﻿cat youtube-dl\ test\ video\ \'\'_ä↭𝕐-BaW_jenozKc.info.json | jq .description -r
test chars:  "'/\ä↭𝕐
test URL: https://github.com/rg3/youtube-dl/issues/1892

This is a test video for youtube-dl.

For more information, contact phihag@phihag.de .
```
```shell
$ cat youtube-dl\ test\ video\ \'\'_ä↭𝕐-BaW_jenozKc.mp4.description
test chars:  "'/\ä↭𝕐
test URL: https://github.com/rg3/youtube-dl/issues/1892

This is a test video for youtube-dl.

For more information, contact phihag@phihag.de .
```
I think the only difference is that the `.description` file has a newline at the end, but I thinks that's expected, since most files have it.

I'm closing the issue, but feel free to open a new one if you think the description in the json dump has any problem or with any other issue you find.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl version 2015.01.30.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by joeschmoe40** [comment]
[quote]I believe this issue to be fixed in youtube-dl version 2015.01.30.1 and newer. See our FAQ if you need help updating.[/quote]

Two comments:
1) When you say "I believe *this* issue to be fixed", to which issue do you specifically refer?  There were several issues raised in this thread (I should know, I started most of them)

2) I recently "upgraded" to version 2015.01.30.2, and found a major breakage (not related to this thread specifically).  Whenever I view a certain kind of video (fetched via youtube-dl), VLC plays it as if it was only 10 seconds long.  Backing up to an earlier version of youtube-dl fixes the problem, so I know that's where the problem is.

**Comment by jaimeMF** [comment]
1. The issue of `_filename` not always being present. If you want to have warnings for conflicting options, please open a new issue.

2. As [explained in the BUG reporting guide](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), open a new issue with the output of `youtube-dl --verbose URL`, otherwise we can't really do anything.

**Comment by joeschmoe40** [comment]
>The issue of _filename not always being present. If you want to have warnings for conflicting options, please open a new issue.

OK - thanks for the clarification.  No worries there.

>As explained in the BUG reporting guide, open a new issue with the output of youtube-dl --verbose URL, otherwise we can't really do anything.

No worries.  I'm sure other people will notice this same problem and file more formal reports on it.
