### ISSUE TITLE
Support new site www.rtp.pt

### ISSUE THREAD

**Issue by accorreia123** [rg3/youtube-dl#4382]
D:\Downloads\youtube-dl -i -f 18 -t --verbose --write-sub http://ww
w.rtp.pt/play/p405/e174042/paixoes-cruzadas
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-i', '-f', '18', '-t', '--verbose', '--write-sub',
'http://www.rtp.pt/play/p405/e174042/paixoes-cruzadas']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.12.04.2
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:64789'}
[generic] paixoes-cruzadas: Requesting header
WARNING: Falling back on generic information extractor.
[generic] paixoes-cruzadas: Downloading webpage
[generic] paixoes-cruzadas: Extracting information
ERROR: Unsupported URL: http://www.rtp.pt/play/p405/e174042/paixoes-cruzadas; pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 651, in _real_extract
  File "youtube_dl\utils.pyo", line 1425, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 13, column 131
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 553, in extract_info
  File "youtube_dl\extractor\common.pyo", line 241, in extract
  File "youtube_dl\extractor\generic.pyo", line 1044, in _real_extract
ExtractorError: Unsupported URL: http://www.rtp.pt/play/p405/e174042/paixoes-cru
zadas; please report this issue on https://yt-dl.org/bug . Make sure you are usi
ng the latest version; type  youtube-dl -U  to update. Be sure to call youtube-d
l with the --verbose flag and include its complete output.

**Comment by mcurly** [comment]
hello everybody.
did anyone confirmed the media downloaded by YD on RTP.PT? In my case, although the downloading occurs, the media (be it video or audio) keeps rewinding, skipping back, stuttering. Same thing happens if I use rtmpdump program with command line obtained with rtmpsrv.
I am under:

uname -a output:

Linux dhubu-1404 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
with:

librtmp0 version

dpkg -s librtmp0 output:

Package: librtmp0
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 143
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: rtmpdump
Version: 2.4+20121230.gitdf6c518-1
Depends: libc6 (>= 2.14), libgcrypt11 (>= 1.4.5), libgnutls26 (>= 2.12.17-0), zlib1g (>= 1:1.1.4)
Pre-Depends: multiarch-support
Description: toolkit for RTMP streams (shared library)
 A small dumper for media content streamed over the RTMP protocol (like BBC's
 iPlayer high quality streams). Supplying an RTMP URL will result in a dumped
 flv file, which can be played/transcoded with standard tools.
 .
 This package contains the shared libraries, header files needed by
 programs that want to use librtmp.
Original-Maintainer: Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
Homepage: http://rtmpdump.mplayerhq.hu/


and rtmpdump version:

dpkg -s rtmpdump output

dpkg -s rtmpdump
Package: rtmpdump
Status: install ok installed
Priority: extra
Section: web
Installed-Size: 568
Maintainer: Jon Davies <jon@hedgerows.org.uk>
Architecture: amd64
Version: 2.4-n87-gita9f353c-ppa8~saucy
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.0), zlib1g (>= 1:1.1.4)
Description: A small dumper for media content streamed over the RTMP protocol
 A small dumper for media content streamed over the RTMP protocol (like BBC's
 iPlayer high quality streams). Supplying an rtmp url will result in a dumped
 flv file, which can be played/transcoded using ffmpeg/mplayer, etc.
Homepage: http://rtmpdump.mplayerhq.hu/

Can anyone shed some light into this issue?

Thanks in advance.
