### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by ersinkarakadioglu** [rg3/youtube-dl#4520]
Im getting this error today and yesterday from my mp3 downloading website. Does anyone else encountered this problem?

youtube-dl http://youtube.com/watch?v=dTaD9cd8hvw --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://youtube.com/watch?v=dTaD9cd8hvw', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.3 - Linux-3.2.0-23-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.10-4, avprobe 0.8.10-4, ffmpeg 0.8.10-4, ffprobe 0.8.10-4, rtmpd                                                                                                               ump 2.4
[debug] Proxy map: {}
[youtube] dTaD9cd8hvw: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); ple                                                                                                               ase report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type                                                                                                                 youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its co                                                                                                               mplete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 276, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1370, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Thanks

**Comment by sisihagen** [comment]
Same here, no matter which video try download, playlist, all videos, ever same error.

youtube-dl -tif 43 --verbose https://www.youtube.com/channel/UCGS956shcnUGt3ocVURB3hg/videos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-tif', '43', '--verbose', 'https://www.youtube.com/channel/UCGS956shcnUGt3ocVURB3hg/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.02.1-gentoo_no_offensive_sites
[debug] Python version 2.7.9 
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCGS956shcnUGt3ocVURB3hg: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 231, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1286, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Regards

**Comment by iggyvolz** [comment]
Make sure you solve the captcha through the same connection you use with youtube-dl.  If you use a proxy with youtube-dl, use the same proxy to solve the captcha.  If you don't use a proxy with youtube-dl, don't use a proxy to solve the captcha.

**Comment by gboddin** [comment]
wget on ipv6 is failing as well (429)

This is from a dedicated server, so I'm assuming they're blocking high-bandwidth connections.

So be carefull if you have a mix of ipv6 and ipv4, if you solve the captcha on IPv4 and connect with IPv6 it won't work ;)
