### ISSUE TITLE
ceskatelevize ERROR: Unable to download JSON metadata: HTTP Error 404

### ISSUE THREAD

**Issue by nasredin** [rg3/youtube-dl#4531]
Hello,

today i get error when tried download this show:
http://www.ceskatelevize.cz/ivysilani/ivysilani/10441294653-hyde-park-civilizace/214411058091220

comand:
youtube-dl "http://www.ceskatelevize.cz/ivysilani/ivysilani/10441294653-hyde-park-civilizace/214411058091220"

reply:

[CeskaTelevize] 214411058091220: Downloading webpage
[CeskaTelevize] 214411058091220: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

regards 
HN

**Comment by pointh** [comment]
The error repeated on 01/01/2015:

youtube-dl http://www.ceskatelevize.cz/ivysilani/10552566680-atp-tyden-tenisu/
[CeskaTelevize] 10552566680-atp-tyden-tenisu/: Downloading webpage
[CeskaTelevize] 10552566680-atp-tyden-tenisu/: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~/tmp$ youtube-dl --verbose http://www.ceskatelevize.cz/ivysilani/10552566680-atp-tyden-tenisu/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ceskatelevize.cz/ivysilani/10552566680-atp-tyden-tenisu/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.16.2
[debug] Python version 2.7.3 - Linux-3.2.0-74-generic-i686-with-Ubuntu-12.04-precise
[debug] exe versions: none
[debug] Proxy map: {}
[CeskaTelevize] 10552566680-atp-tyden-tenisu/: Downloading webpage
[CeskaTelevize] 10552566680-atp-tyden-tenisu/: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 276, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1370, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
