### ISSUE TITLE
Site Requests (Speedvideo Videopremium)

### ISSUE THREAD

**Issue by alewin** [rg3/youtube-dl#4618]
Hi, could you add support for speedvideo and videopremium

exemple
http://speedvideo.net/do5k6dou390x
http://videopremium.tv/jupb7ub71qny

**Comment by phihag** [comment]
As [mentioned in our contribution guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#does-the-issue-involve-one-problem-and-one-problem-only), please do not involve more than one issue per issue report. youtube-dl does only support sites that do not specialize in distributing copyright-infringing content. Since (judging from the titles) both example URLs refer to copyrighted content that is unlikely being distributed lawfully, we cannot add support for either.

If speedvideo or videopremium also distribute content they're allowed to distribute, please open new issues (one per video service, unless the services are clearly related) with an example URL of a video that does not infringe copyright.
