### ISSUE TITLE
about youtube-dl installation

### ISSUE THREAD

**Issue by angel100w** [rg3/youtube-dl#4652]
hello,
may be this is a little off topic but what are home directory and path and how do i find them.
if i put youtube-dl.exe for windows and ffmpeg under the same folder anywhere like in my document for exemple will it be able to find ffmpeg and merge the youtube 1080p video and audio, keep in mind that ffmpeg.exe is located under his own folder in subfolder bin, and that i will be using youtube-dl by going to the folder where it is located in the command prompt

**Comment by phihag** [comment]
Thank you for your report!

If you put youtube-dl and ffmpeg in the same directory that you're running the command from, it will work natively.

To make a different directory work - either for ffmpeg, or for youtube-dl, or for both - simply create the directory (say, `C:\bin`, or `C:\Users\angel\bin`, or `C:\Program Files\ffmpeg\bin`), put all the executables directly in there, and then [set your PATH environment variable](https://www.java.com/en/download/help/path.xml) to include that directory.

From then on, after restarting your shell, you will be able to access both youtube-dl and ffmpeg (and youtube-dl will be able to find ffmpeg) by simply typing `youtube-dl` or `ffmpeg`, no matter what directory you're in.

I am closing this issue since I think after going through the above-mentioned steps it should just work, but if they don't succeed, please do comment and we will reopen the issue. Thanks!
