### ISSUE TITLE
File date

### ISSUE THREAD

**Issue by mihaicris** [rg3/youtube-dl#4667]
Hi, 

I am not sure if this is an issue, but when I update one channel and there are new videos, the new file downloaded has a different file date than the date generated in the file name (the upload date).
If the file has been uploaded and downloaded on the same day 9.01 why the file date is 3.01?

![2015-01-09_133022](https://cloud.githubusercontent.com/assets/5946912/5679184/0359c920-9804-11e4-8846-1172c576dac3.png)

Any idea why is this happening?

Thanks.

**Comment by phihag** [comment]
This is because the file modified time is determined during the actual download (i.e. it's the time associated with the file, presumably a timestamp of when the video got uploaded to YouTube) and upload_date is the time of publication (i.e. the time when the video was made available, **and** the time that is shown on the webpage).

You can pass in the `--no-mtime` option to disable mtime modification; the file modification time will them be the time of the download.

I do think that should answer what is happening. I am closing the issue now, but you are welcome to suggest a different behavior. What would you prefer? Bear in mind that the situation is quite complicated as it is with the introduction of timezones; also, depending on the extractor, we may just have the *date* 2015-01-09, and not a precise timestamp.

**Comment by mihaicris** [comment]
The option <code>--no-mtime</code> is doing as I would have expected, the file modification time is the download time.
I am not sure if this option should be  the default since others might consider the Last-modified information better as default. 
As far as I am concerned, using <code>--no-mtime</code> solved my problem. 
Thanks. ... I must read the docs ;)
