### ISSUE TITLE
•This website requires you to log in

### ISSUE THREAD

**Issue by shubhamjsharma3lac** [rg3/youtube-dl#4693]
I had extracted a best-video link from a youtube video.
link: "https://r3---sn-vgqsened.googlevideo.com/videoplayback?dur=6705.667&requiressl=yes&mt=1421123535&mv=u&ms=au&gcr=us&mm=31&source=youtube&ratebypass=yes&expire=1421145382&id=o-AKyrjlkyozW9Y_8ZlxB1fU_hU1eAQq2vzmPo_tbDJwDz&sparams=dur%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&fexp=900242%2C900718%2C904843%2C927622%2C930821%2C932404%2C9405634%2C9405777%2C941004%2C943917%2C945125%2C947209%2C947218%2C947225%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201%2C959701%2C961901&mime=video%2Fmp4&ip=23.101.206.60&key=yt5&itag=18&upn=w0xaQyG5_Oc&ipbits=0&signature=8BDD56D631ECD6F7E7610BF5F51E869D359A12CF.2E2D7C9A994CE280653169EBCE2AA8BF5EF5AF9F"

while trying to open the link in web browser I am getting a error message stating that
"•This website requires you to log in.
This error (HTTP 403 Forbidden) means that Internet Explorer was able to connect to the website, but it does not have permission to view the webpage."

**Comment by phihag** [comment]
It is hard to say what's happening here since this bug report is missing essential information. Please review our [issue reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). In particular, the full output of youtube-dl when called with `-v` would give us a hint whether extraction worked alright, and how you called youtube-dl in the first place.

Does downloading the video with youtube-dl work?

Notably, URLs are not generally accessible without the cookies extracted by youtube-dl (use `--cookies cookiefile.txt` to write them somewhere). Unless guaranteed otherwise, the request must also come from the same IP address. These restrictions differ from service to service. For YouTube  - most likely the service in use here, although we can't say for certain without the `-v` output - the request generally needs to come from the same IP address, and *may* need to have the same cookies.

Can you elaborate how you copied over the cookies into Internet Explorer? Did you run youtube-dl on the same machine that Internet Explorer is running on?

**Comment by shubhamjsharma3lac** [comment]
No I had run the youtube-dl from the azure virtual machine and extracted the download link from there l.
And I am trying to use that download link for playing the videos in the media element.

Sent from my Windows Phone
________________________________

**Comment by phihag** [comment]
I've amended our [FAQ entry for this question](https://github.com/rg3/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).
