### ISSUE TITLE
Youtube list

### ISSUE THREAD

**Issue by ashwini-singh** [rg3/youtube-dl#4788]
Whenever i try to download a video from a youtube list,
eg https://www.youtube.com/watch?v=IcrbM1l_BoI&list=RDCevxZvSJLk8&index=3
I end up getting a error that list is not recognized as internal or external command (I use Youtube-dl in Windows 7). 

YouTube playlists are supported by Youtube-DL, but are youtube lists supported? If not, please add its support like the list mentioned above.

**Comment by jaimeMF** [comment]
This is probably a problem with quoting the url. Since the url contains special characters for the shell (the `&` in that case), you have to quote the url before passing it to youtube-dl: `youtube-dl "https://www.youtube.com/watch?v=IcrbM1l_BoI&list=RDCevxZvSJLk8&index=3"` (single quotes `'` are also supported in unix shells, but I think windows needs double quotes).

I'm closing the issue, but if you still have the problem, please [post the full output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) of `youtube-dl --verbose "https://www.youtube.com/watch?v=IcrbM1l_BoI&list=RDCevxZvSJLk8&index=3"`.
