### ISSUE TITLE
Unsupported/Broken site - RTVE.es?

### ISSUE THREAD

**Issue by jjarava** [rg3/youtube-dl#4823]
Hi!

I've just updated to the latest version (`2015.01.30.2`) and I've tried to download a video from RTVE.es.

The video plays properly in the browser, but if I try to get it via youtube-dl, I get an error about "*Unsupported URL*".

The full --verbose output is;

```python
Mac-JJJ:Cuentame jjarava$ youtube-dl "http://www.rtve.es/m/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t16-ultimo-minuto-nuestra-vida-capitulo-276/2969138/?media=tve" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.rtve.es/m/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t16-ultimo-minuto-nuestra-vida-capitulo-276/2969138/?media=tve', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ?media=tve: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?media=tve: Downloading webpage
[generic] ?media=tve: Extracting information
ERROR: Unsupported URL: http://www.rtve.es/m/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t16-ultimo-minuto-nuestra-vida-capitulo-276/2969138/?media=tve
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 694, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1495, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 37, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 618, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1110, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.rtve.es/m/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t16-ultimo-minuto-nuestra-vida-capitulo-276/2969138/?media=tve
```

**Comment by jaimeMF** [comment]
Thanks for the report, it will work it the next version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.02. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by cyttorak** [comment]
youtube-dl --verbose -g "http://www.rtve.es/alacarta/videos/programas-y-concursos-en-el-archivo-de-rtve/anarquismo-vivir-utopia-1930-1939/942896/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-g', 'http://www.rtve.es/alacarta/videos/programas-y-concursos-en-el-archivo-de-rtve/anarquismo-vivir-utopia-1930-1939/942896/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.3 - Linux-3.18.7+-armv6l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffmpeg 0.8.16-6, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1675, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
@cyttorak Probably the same as #5011. For future reports, please open a new issue, it makes easier to track them.

**Comment by cyttorak** [comment]
thanks

**Comment by SergioWheel** [comment]
I'm also having problems download videos from the RTVE.es site:

30/5/2015 10:02:52 AM: Connecting to http://www.rtve.es/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t5-capitulo-122/703907/
30/5/2015 10:02:53 AM: 30/5/2015 10:02:53 AM: video helper support...
30/5/2015 10:02:53 AM: ****** previous log start ******
30/5/2015 10:02:53 AM: ****** could not get video url ******
30/5/2015 10:02:53 AM: 
30/5/2015 10:02:53 AM: ****** previous log end ******

30/5/2015 10:02:53 AM: Error:ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
30/5/2015 6:22:07 PM: Connecting to http://www.rtve.es/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t5-capitulo-122/703907/
30/5/2015 6:22:08 PM: 30/5/2015 6:22:08 PM: video helper support...
30/5/2015 6:22:08 PM: ****** previous log start ******
30/5/2015 6:22:08 PM: ****** could not get video url ******
30/5/2015 6:22:08 PM: 
30/5/2015 6:22:08 PM: ****** previous log end ******

Is this an issue with the site or program not able to grab video as I managed to downlaod videos that once didn't download but most I'm not able to trying many times to re-start without success as I'm using the latest version of video download capture.
