### ISSUE TITLE
Config file syntax for site specific parameters?

### ISSUE THREAD

**Issue by pps** [rg3/youtube-dl#4895]
I just added
`-f 299+bestaudio/137+bestaudio/298+bestaudio/bestvideo+bestaudio`
to the youtube-dl config file at
`~/.config/youtube-dl/config`
to specify which youtube video sizes I prefer.

Problem is, when I now try to use youtube-dl to download files from vimeo, that download now fails. ("ERROR: requested format not available").

Is there a syntax for the config file so that we can specify certain video sizes for youtube but keep the default behavior for other sites?

Thank you!

**Comment by jaimeMF** [comment]
Simply add `/best` at the end (`-f 299+bestaudio/137+bestaudio/298+bestaudio/bestvideo+bestaudio/best`) it will fallback to the default format.
I'm closing the issue, since I think that should work. Please comment here if it doesn't solve your problem.

There's already a proposal for supporting per site configuration: #3101.

**Comment by pps** [comment]
It works, thanks!
