### ISSUE TITLE
tvcatchupaustralia

### ISSUE THREAD

**Issue by tevatahiti** [rg3/youtube-dl#4899]
Hi,
Thank you very much for the software, it is amazing!!!!
Can you add this website : http://www.tvcatchupaustralia.com/ ?
I hope you can help me as I trying hard to keep a beautiful doc from there
Thank you 
Have a nice day
Jimmy

**Comment by phihag** [comment]
Can you [name an example URL](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md#is-the-description-of-the-issue-itself-sufficient)?

**Comment by tevatahiti** [comment]
Hi Philipp,
Thank you for the mail
Here is an example:
http://www.tvcatchupaustralia.com/nitv/tribal-scent/s1-ep1-69414
Thanks again
btw your soft is fantastic!!!
Jimmy

Philipp Hagemeister a écrit:

**Comment by robin007bond** [comment]
A temporary workaround, you can download the original URL in youtube-dl instead:
http://www.sbs.com.au/ondemand/video/357036099545

**Comment by phihag** [comment]
Thank you for the report. youtube-dl 2015.02.09.2 and newer should extend the generic extractor so that it captures tvcatchupaustralia. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by tevatahiti** [comment]
Hey Philippe,
Thank you but have you tried it?
Here is what I get: 
youtube-dl http://www.tvcatchupaustralia.com/nitv/tribal-scent/s1-ep1-69414
[generic] s1-ep1-69414: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s1-ep1-69414: Downloading webpage
[generic] s1-ep1-69414: Extracting information
[SBS] 357036099545: Downloading webpage
[ThePlatform] 9TSIrIo4dVJ_: Downloading XML
[ThePlatform] 9TSIrIo4dVJ_: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
Thanks

**Comment by phihag** [comment]
Your log shows that it works fine; the problem is with the SBS or ThePlatform downloader. Since I'm not from Australia and none of our users (hint hint) provided an Australian VPN connection to us developers, I only tested that the redirect to SBS works fine.

Please do open a new issue with the output of `youtube-dl -v http://www.sbs.com.au/ondemand/video/357036099545`. Bear in mind that any developer not from Australia and without access to an Australian VPN is very very unlikely to be able to fix the SBS/ThePlatform downloader for this use case.
