### ISSUE TITLE
Please add a possibility to only download a video if its upload date is known.

### ISSUE THREAD

**Issue by GijsTimmers** [rg3/youtube-dl#4916]
I often use the following command:

    $ youtube-dl -o "%(upload_date)s_%(title)s.%(ext)s" <youtube URL>

While this usually returns the date as part of the filename, it sometimes can't fetch the date and will return something like `NA_Big_Buck_Bunny.mp4` as its filename.

Right now, I run a script after downloading that removes all `NA_` files, using a regex. But this is cumbersome.

Therefore, it would be nice to be able to download a video only if its date is known. But this option doesn't exist at the moment. I was thinking of an extra option in the `--date` switch:

    # Download only the videos uploaded on January 1, 1970
    $ youtube-dl --date 19700101

    # Download only the videos with a valid upload date
    $ youtube-dl --date any

What do you think? If this option is not desired, could you think of another way to solve this problem?

**Comment by phihag** [comment]
Thank you for report. Since youtube-dl 2015.02.10.2 there is a generic filtering mechanism which can be employed by adding `--match-filter "upload_date"`. This may seem to be a roundabout way at first, but is actually way more powerful. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by GijsTimmers** [comment]
Exactly what I was looking for! Thank you!
