### ISSUE TITLE
Using forcethumbnail=true and Download=False using python

### ISSUE THREAD

**Issue by enricoluigi** [rg3/youtube-dl#5008]
Im pretty sure this is not the right place to post but i couldnt find an oficial forum or group.

im trying to get the thumbnail url from a video using python, how do i do that?
this is my code wich shows the Url and Title:

def getdata(url)
                        ydl = youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s'})
                        result = ydl.extract_info(url,download=False)
                        url = result['url']
                        title = result['title']
			writecvs(url, title, tags)

Thanks and sorry for posting in the wrong place.

**Comment by phihag** [comment]
This is the right place to post - what made you think otherwise?

You can simply look into the `thumbnail` property. Bear in mind that unlike id or title, it may be `None` or unset. That happens if the service does not provide a thumbnail, doesn't support thumbnails at all, or youtube-dl doesn't correctly extract the thumbnail (in the latter case, feel free to [create a new bug report](https://github.com/rg3/youtube-dl/issues/new), provided you are using the [latest version](https://yt-dl.org/latest/version)).

The following code works fine for me:

```
import youtube_dl


def getdata(url):
    with youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s'}) as ydl:
        result = ydl.extract_info(url, download=False)
    url = result['url']
    title = result['title']
    thumbnail = result.get('thumbnail')
    print('url: %r, title: %r, thumbnail: %r' % (url, title, thumbnail))
    # writecvs(url, title, tags)

getdata('http://www.youtube.com/watch?v=BaW_jenozKc')
```

I am closing this issue now, since the code works fine for me. If there is still a problem, please say so and we will reopen it. Thanks!
