### ISSUE TITLE
Skipping DASH manifest

### ISSUE THREAD

**Issue by amkrankruleuen** [rg3/youtube-dl#5118]
user@sub2:~/conversion# youtube-dl -e "https://www.youtube.com/watch?v=7f8nSWtJLQo"

WARNING: [youtube] 7f8nSWtJLQo: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
Becky G - Magik 2.0 (Lyric Video)  ft. Austin Mahone

**Comment by dstftw** [comment]
>Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by amkrankruleuen** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-e', '--verbose', 'https://www.youtube.com/watch?v=7f8nSWtJLQo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 0.8.16-6, avprobe 0.8.16-6, ffmpeg 2.3, ffprobe 2.3
[debug] Proxy map: {}
WARNING: [youtube] 7f8nSWtJLQo: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
Becky G - Magik 2.0 (Lyric Video)  ft. Austin Mahone

**Comment by ivan** [comment]
The same error is printed for https://www.youtube.com/watch?v=RQuY8kERaU0 (though the video downloads anyway.)

**Comment by baruns** [comment]
What is the solution then?? It's happening for latest version also.. Video gets downloaded without problem... Strange!!!

[test@my ~]# youtube-dl -s -4 http://www.youtube.com/watch?v=5OAW3TKwfyk --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-s', u'-4', u'http://www.youtube.com/watch?v=5OAW3TKwfyk', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.6.6 - Linux-2.6.32-042stab106.6-i686-with-centos-6.6-Final
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 5OAW3TKwfyk: Downloading webpage
[youtube] 5OAW3TKwfyk: Downloading video info webpage
[youtube] 5OAW3TKwfyk: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {43} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {18} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {5} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {36} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {17} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {137} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {248} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {136} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {247} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {135} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {244} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {134} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {243} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {133} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {242} signature length 38.41, html5 player en_US-vflzomeEU
[youtube] 5OAW3TKwfyk: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflzomeEU/html5player.js
[youtube] {160} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {278} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {140} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {171} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {249} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {250} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] {251} signature length 40.41, html5 player en_US-vflzomeEU
[youtube] 5OAW3TKwfyk: Downloading DASH manifest
[youtube] 5OAW3TKwfyk: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflzomeEU/html5player.js
[youtube] 5OAW3TKwfyk: Downloading DASH manifest
WARNING: [youtube] 5OAW3TKwfyk: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[test@my ~]#

**Comment by yan12125** [comment]
For those who are sick about these warnings, downgrading to version 2015.06.25 works.

@dstftw For ```na93MI5NFy0```, the video mentioned in #6182, commit c608ee491f48820139491b6363e48ef151cc6d8c gives a warning while commit 1bbe660dfa713d377fdf0eeec6b6d6a5fa8c86d9 not. I guess it's caused by additional DASH MPD requests. Would it be better to revert PR #6097 before we're sure all DASH manifests can be extracted correctly?

**Comment by dstftw** [comment]
I guess this burst of bug reports is not due to warning, but *please-report-this-issue* message. Silencing it will probably [suffice](https://github.com/rg3/youtube-dl/commit/77c6fb5b24c477c9de022f252dc9958a4b3b8b42).

**Comment by maxnordlund** [comment]
Wouldn't it be better to silence the warning completely if the other DASH succeeded? At least without the `--verbose` flag set.

**Comment by dstftw** [comment]
Probably, why such a concern about that? It doesn't ask to submit an issue anymore.

**Comment by maxnordlund** [comment]
Well, it doesn't make much sense for a tool to cry wolf _every_ time it's used, don't you think? If I see a warning I take it as a hint to investigate if something is up, but this is just business as usual, which means that I'll start ignoring all warnings.

It's not about how many issues there are on Github, it's about the users getting spammed with irrelevant warnings.

**Comment by dstftw** [comment]
It doesn't spit this warning every time, only on some music videos basically. You can use `--no-warnings` if you are so concerned about being spammed.

**Comment by bealparslan** [comment]
Hello, I'm read all duplicate issues. But this issue very important. I'm using youtube-dl 2015.07.21 version. Warnings / errors do not want to hide. Please correct this problem.

[root@localhost ~]# youtube-dl https://www.youtube.com/watch?v=tDq3fNew1rU --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=tDq3fNew1rU', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.6.6 - Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tDq3fNew1rU: Downloading webpage
[youtube] tDq3fNew1rU: Downloading video info webpage
[youtube] tDq3fNew1rU: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {43} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {18} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {5} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {36} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {17} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {136} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {247} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {135} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {244} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {134} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {243} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {133} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {242} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {160} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {278} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {140} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {171} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {249} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {250} signature length 40.40, html5 player en_US-vflDv401v
[youtube] {251} signature length 40.40, html5 player en_US-vflDv401v
[youtube] tDq3fNew1rU: Downloading DASH manifest
[youtube] tDq3fNew1rU: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflDv401v/html5player.js
[youtube] tDq3fNew1rU: Downloading DASH manifest
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://r3---sn-u2oxu-f5fs.googlevideo.com/videoplayback?fexp=901816%2C903311%2C9406194%2C9408142%2C9408710%2C9408860%2C9414856%2C9415041%2C9415397%2C9415531%2C9415540%2C9416126%2C9416215%2C9416403%2C9416650%2C9416729%2C9417689%2C9417709&pcm2cms=yes&pl=20&itag=22&mime=video%2Fmp4&upn=R701I8pxbaQ&sparams=dur%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&id=o-AOqijFrPLTHRsP6iKpcepanQ8r2gr4-4K_sRJ_tLyIIZ&source=youtube&lmt=1429771443630151&key=yt5&ip=MY_SERVER_IP&expire=1437591751&dur=213.739&sver=3&requiressl=yes&mv=u&mt=1437570052&ms=au&mn=sn-u2oxu-f5fs&mm=31&ratebypass=yes&signature=36FE793913C267CA25334DAC38142B75915F7C3E.3A9A12F983904986131972B41D6926D25840832A'
[download] Destination: Sean Paul - Got 2 Luv U Ft. Alexis Jordan [Official Music Video]-tDq3fNew1rU.mp4
[download] 100% of 65.24MiB in 00:02

**Comment by jaimeMF** [comment]
In the next version, for the music videos the extra manifest won't be downloaded (no more warnings).

**Comment by bealparslan** [comment]
It will handle the problem as soon as possible, you can publish an update. thank you.
