### ISSUE TITLE
Format Merging Auto Correction

### ISSUE THREAD

**Issue by Athertonius** [rg3/youtube-dl#5154]
When downloading different formats and merging them, but entering `-f someaudio+somevideo`, the programme returns: `ERROR: The first format must contain the video, try using "-f somevideo+someaudio"`. If it already "understands" the formats and can offer the alternate form, why can the programme not be run with the alternate form, preserving normal stream order in the merge? :confused:

**Comment by jaimeMF** [comment]
It would complicate a bit the code, why can't you just use `-f somevideo+someaudio`?

**Comment by Athertonius** [comment]
It wasn't a purposeful use of the argument, I only discovered it after I
ran the program overnight, stopping at the error. I'd just think that this
"problem" could have been avoided...

**Comment by jaimeMF** [comment]
From the option help:
> You can merge the video and audio of two formats into a single file using `-f <video-format>+<audio-format>`

So I think it's OK to only support that order.

**Comment by nateschiffer** [comment]
I strongly disagree with the closing of this bug. The current behavior is extremely user-hostile.

Just ran into this needless annoyance again, for about the 100th time. You see the Terminal lists the audio-only streams _first_, so naturally I will sometimes input those first.

Essentially the error message is saying "I know what you want to do. I know it will work, because I've already parsed all the formats. I know the exact thing to do to fix the problem. But I (the robot), am going to make you (the human) do some extra work just so you can accomplish what I already know you want."

I submitted the patch above (which imo did not "complicate the code"). It also fixed some bugs (audio+audio/video+video) that weren't fixed yet, and the later fix... complicated the code.

Seriously @jaimeMF, WTF? How is this UI annoyance the _least_ undesirable behavior? "RTFM" is no excuse.

**Comment by yan12125** [comment]
As #6454 is more general than #8157, we'll look at the latter as changing the code one time and solve two problems is better than changing the code two times.
