### ISSUE TITLE
Urgent Feature: Allow manual extractor selection/override

### ISSUE THREAD

**Issue by BlackPropeller** [rg3/youtube-dl#5159]
Having the ability to manually tell youtube-dl what extractor to use while providing a link that may not be the URL the extractor expects.

For example:
`youtube-dl --use-extractor 'youtube' -g http://www.blahblahblah.com/some_captcha_workaround.php?v=xxxxxxxxxxx`
...would cause youtube-dl to treat the link as a youtube video url.

I need this feature to try to work on a captcha workaround by processing everything outside of youtube-dl and return the captcha-less video page's source code (it would be identical to the source that youtube-dl sees when there is no captcha).

Another cool upgraded or advanced use of this feature would be the ability feed/pipe the pure source code into youtube-dl after captcha processing or bypass.

**Comment by jaimeMF** [comment]
We would have to modify a lot the regexes to make it work and it wouldn't work because we end up downloading the page `youtube.com/watch?v=<id>` for all the input urls.
Note that since the source code of youtube-dl is freely available, you can download it and modify the [youtube extractor](https://github.com/rg3/youtube-dl/blob/98998cded6e179b35055177f75fc921d99ee5938/youtube_dl/extractor/youtube.py#L187) for testing it.

See the reasons in #4551 to know why passing the webpage source as input is not possible (among others it won't work for playlists and for youtube videos we need at least two pages).
