### ISSUE TITLE
please add support for new twitter video (not vine)

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#5239]
example URL: https://twitter.com/TheHeatMiser_/status/577886337983864832/video/1

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report.

**Comment by naglis** [comment]
Sorry, closed the wrong issue.

**Comment by CiscoPress** [comment]
any news?

**Comment by aaronvegh** [comment]
Count me in for a vote on this.

**Comment by joepie91** [comment]
I need this as well, I suspect (unless this is yet another video player type not covered here...).

* __Page URL:__ http://www.rtlnieuws.nl/nieuws/buitenland/honderden-gewonden-na-enorme-explosie-china (RT video down the page)
* __Frame URL:__ https://amp.twimg.com/amplify-web-player/prod/source.html?embedded=1&json_rpc=1&rpc_init=1 (generic, so probably loaded otherwise)

**Comment by dstftw** [comment]
Supported since 2015.10.18.
