### ISSUE TITLE
Add support for Vessel

### ISSUE THREAD

**Issue by tb01110100** [rg3/youtube-dl#5275]

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by tb01110100** [comment]
Sorry, here you go: https://www.vessel.com/videos/JYZEYDYx0

**Comment by naglis** [comment]
Thank you for the report. Support for vessel.com has been added and should be available in the next release of youtube-dl. Note that the provided URL requires subscription, so, assuming you are a subscriber, you would need to [specify your Vessel username and password to youtube-dl](https://github.com/rg3/youtube-dl#authentication-options) in order to download it.

**Comment by tb01110100** [comment]
Thank you!
