### ISSUE TITLE
help for app engine

### ISSUE THREAD

**Issue by funfarooq** [rg3/youtube-dl#5406]
currently i have youtube-dl server on my hostgator server with following code 

$url = 'http://www.youtube.com/watch?v=rClUpezLmrY';
  
     
     $string = 'python youtube-dl -g '.$url;
	//echo $string;
    $string2 = 'python youtube-dl --help';
    exec($string, $result, $status);
   // echo json_encode(array('status' => $status, 'url_orginal'=>$url, 'url' => $result, 'command' => $string));
	 $urlf = json_encode(array( ''=> $result));
	 $urlf = str_replace('{"":["','',$urlf);
	 $urlf = str_replace('"]}','',$urlf);
	 $urlf = str_replace('\/','/',$urlf);
	 echo $urlf;

it use to work fine but my ip address is blocked by youtube and now i wanna move it google app engine and it doesnot support execute command if you help me out with some thing that can be executed on google app engine will be lot help full

**Comment by jaimeMF** [comment]
You'll have to write it in python and use youtube-dl as a python module. Note that since the python version in the App Engine is missing some standard library modules, you have to patch youtube-dl. If you don't want to start the project yourself, you can look into [youtube-dl-api-server](https://github.com/jaimeMF/youtube-dl-api-server).

(By the way: I hope you saniteze `$url`, otherwise you are vulnerable to attacks)
