### ISSUE TITLE
Point me to the part of code where youtube-dl gets the video url, adds header and then create and send the request to the server.

### ISSUE THREAD

**Issue by kai18** [rg3/youtube-dl#5425]
I have tried extracting the video url from the webpage and use that in wget and curl out of curiosity, and as expected i get a 403. I would like to know how the entire request is created, for educational purpose. I have tried going through the source code of the youtube-dl extractor file for youtube but maybe i am not skilled enough to understand it. If someone could please point me in the right direction, that would be great.

**Comment by jaimeMF** [comment]
I'm closing the issue since it's not a problem with youtube-dl.

You may want to look into [these lines](https://github.com/rg3/youtube-dl/blob/8f02ad4f12549865a2a4436328075f4b20b906ef/youtube_dl/extractor/youtube.py#L1040-L1105), for some urls you need to process the signature and that's a harder task (look into the `_decrypt_signature`method).
