### ISSUE TITLE
Fish shell doesn't work (tested with OSX 10.9)

### ISSUE THREAD

**Issue by thang1thang2** [rg3/youtube-dl#5507]
Using OSX 10.9.5, and the Fish shell, version 2.1.1-1204-gb5d9e36, youtube-dl didn't work. I tried the command `youtube-dl  https://www.youtube.com/playlist?list=PL91045D0297689C75`, and the command `youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/playlist?list=PL91045D0297689C75`.

Both commands failed identically, with this error:

    No matches for wildcard 'https://www.youtube.com/playlist?list=PL91045D0297689C75'.
    fish: youtube-dl  https://www.youtube.com/playlist?list=PL91045D0297689C75
                      ^
    Usage: youtube-dl [OPTIONS] URL [URL...]

    youtube-dl: error: You must provide at least one URL.
    Type youtube-dl --help to see a list of all options.

Using the 'sh' shell worked perfectly, however.

**Comment by yan12125** [comment]
For all shells, including Fish, you need to enclose URLs with '?' or '&' in single or double quotes.

**Comment by thang1thang2** [comment]
Great! Thanks for the information, I couldn't find it in the man page. The sh shell worked just fine without using quotations, which is why I thought it was a fish shell error.

**Comment by yan12125** [comment]
Simply because on Mac sh does not support the special character '?'. Anyway, it's a good practice to enclose URLs in quotes.

**Comment by jaimeMF** [comment]
That's because in both shells `?` is used for filename expansion, but if no filenames matches (like for `https://www.youtube.com/playlist?list=PL91045D0297689C75`) fish just outputs the error while bash returns the original string.  I use the fish shell and I'm used to quoting every url, you'll also get used. See https://github.com/fish-shell/fish-shell/issues/1965 and https://github.com/fish-shell/fish-shell/issues/967 if you want to know more about fish behaviour.
