### ISSUE TITLE
Clarification "skip" warning

### ISSUE THREAD

**Issue by Issam2204** [rg3/youtube-dl#5600]
Hi! Thank you for the beautiful program :)

I have a question: I generally use this command to download music playlist from youtube

>youtube-dl --extract-audio --audio-format best --embed-thumbnail --prefer-ffmpeg --no-check-certificate https://www.youtube.com/playlist?list=XXXXX

On each download I read this:

>[youtube] Post-process file EXAMPLE.m4a exists, skipping

I'd like to know if the skipping action is normal and why it happens. Is there any way to "correct" this? The only way to hide it is to use -q but then I'd not see all the other information which I find useful.

Thank you again!

**Comment by jaimeMF** [comment]
It's normal, YouTube already provides an audio file so that's what it downloads. It doesn't need to do anything else. If you want the audio in other format you can use `--audio-format mp3`or similar.

Don't use `--no-check-certificate`, it turns off certificate verification, so someone could manipulate the content you receive.

**Comment by Issam2204** [comment]
Perfect! Thank you very much jaimeMF!
