### ISSUE TITLE
Support for bt.no

### ISSUE THREAD

**Issue by danieman** [rg3/youtube-dl#5620]
Hello,
would you please add support for videos from the Norwegian newspaper bt.no?
Examples:
1) http://www.bt.no/nyheter/lokalt/Kjemper-for-internatet-1788214.html
2) http://www.bt.no/tv/#!/video/100250/norling-dette-er-forskjellen-paa-1-divisjon-og-eliteserien
3) http://www.bt.no/spesial/vestlendingen/#!/86588

Thank you very much! :-)

**Comment by barsnick** [comment]
For those videos that use VGTV as their provider, i.e. bttv.vgtv.no, I have a modification of the VGTV extractor which works fine. Yet I haven't submitted it yet because *.vgtv.no hosts quite a few sites, and I'd like to make the extractor generic. (It's just a copy/paste hack right now.)

I don't have access to my code right now, but can make it available once I do.

**Comment by dstftw** [comment]
All mentioned bt.no URL willl be supported in the next version. Thanks for the report.
