### ISSUE TITLE
Dumping to `stdout` is broken for version `2015.04.26`

### ISSUE THREAD

**Issue by cipriancraciun** [rg3/youtube-dl#5627]
As the subject says, if one tries to dump to `stdout` a video whose ID starts with an underscore (`_`), `youtube-dl` instead tries to save it to disk.

> youtube-dl --output - -- 'https://www.youtube.com/watch?v=_KYvp8PrCFc'

**Comment by yan12125** [comment]
Maybe you need to specify the ```best``` format. E.g.
```
youtube-dl -f best --output - 'https://www.youtube.com/watch?v=_KYvp8PrCFc'
```

**Comment by cipriancraciun** [comment]
I think I've found the issue:  with the latest version (`2015.04.26`) it seems the option to write to `stdout` is broken (i.e. `--output -`).

I've downgraded to `2015.04.09` and it seems to be working now.

**Comment by jaimeMF** [comment]
as @yan12125 said you have to use `-f best`, because when ffmpeg/avconv is installed youtube-dl now defaults to `-f bestvideo+bestaudio/best` which gives a better quality video. `bestvideo+bestaudio` doesn't currently support being dump to stdout, and with a naive approach the two files would need to be downloaded first, that's not what you want when reading from stdout. If you really need to output to stdout `bestvideo+bestaudio` feel free to open a new issue.
