### ISSUE TITLE
Youtube-dl has Problems on RTLNow and other RTL sites

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#5681]
Hey, 

I have a bug since today in the morning. I dont know what kind of bug it is. RTLNow are a Video on Demand site. Downloads of videos on RTLNow dont works, but that is okay, this is not the main Problem. The main problem is, I cant play over rtmpdumb the videos. Yesterday evening all works finde, but today, I use on my Debian 8 system in the root terminal an update:

youtube-dl -U 

I have now the newsst version ---> youtube-dl is up-to-date (2015.05.10)

If I use youtube-dl for a Video on RTLNow, there is this error message:

mplayer <(youtube-dl --no-playlist -o - "http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015")
MPlayer2 2.0-728-g2c378c7-4+b1 (C) 2000-2012 MPlayer Team
Cannot open file '/home/jj-jana/.mplayer/input.conf': No such file or directory
Failed to open /home/jj-jana/.mplayer/input.conf.
Cannot open file '/etc/mplayer/input.conf': No such file or directory
Failed to open /etc/mplayer/input.conf.

Playing /dev/fd/63.
[RTLnow] 201855: Downloading webpage
[RTLnow] 201855: Downloading player data XML
[download] Destination: -
ERROR: unable to download video
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Failed to recognize file format.

Exiting... (End of file)
---------

Yestterdax all works fine, why not today no more? :-( Has someone an idea? 

Other sites like Streamcloud are still working.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)

**Comment by JJ-Jana** [comment]
Hello, I am now on a PC of a friend with Linux Mint 17.1 there is the same error too. I hope I do it right with --verbose. Look this output of the terminal:
------------------------------

mplayer <(youtube-dl --no-playlist --verbose -o - "http://rtl-now.rtl.de/unter-uns/untermieter.php?film_id=200397&player=1&season=2015") 
MPlayer2 2.0-701-gd4c5b7f-2ubuntu2 (C) 2000-2012 MPlayer Team
Cannot open file '/home/birne/.mplayer/input.conf': No such file or directory
Failed to open /home/birne/.mplayer/input.conf.
Cannot open file '/etc/mplayer/input.conf': No such file or directory
Failed to open /etc/mplayer/input.conf.

Playing /dev/fd/63.
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-playlist', u'--verbose', u'-o', u'-', u'http://rtl-now.rtl.de/unter-uns/untermieter.php?film_id=200397&player=1&season=2015']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-i686-athlon-with-LinuxMint-17.1-rebecca
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[RTLnow] 200397: Downloading webpage
[RTLnow] 200397: Downloading player data XML
[debug] Invoking downloader on u'rtmpe://fms.rtl.de/hds'
[download] Destination: -
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de/hds -o - --swfVfy http://rtl-now.rtl.de/includes/vodplayer.swf --pageUrl 'http://rtl-now.rtl.de/unter-uns/untermieter.php?film_id=200397&player=1&season=2015' --playpath mp4:200397/manifest-hds --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : hds
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] WARNING: Can't resume in stdout mode, ignoring --resume option
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:200397/manifest-hds
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/hds
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtl-now.rtl.de/unter-uns/untermieter.php?film_id=200397&player=1&season=2015
[rtmpdump] DEBUG: app      : hds
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: 7f 30 cc ac 55 6d 23 86 cf 55 3a 5b 32 50 95 23
[rtmpdump] DEBUG: 51 a3 d7 67 95 62 e4 f6 fd 17 b6 1a 20 69 7b 4f
[rtmpdump] DEBUG: HandShake: Type Answer   : 06
[rtmpdump] DEBUG: HandShake: Server Uptime : 1245781530
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.5.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 589
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: dc 74 db e1 ad 94 a9 22 0a 18 71 9a b8 f2 fa 76
[rtmpdump] DEBUG: 0e aa 96 c7 07 6e 70 d2 8c dc 60 9f c7 c4 81 a1
[rtmpdump] DEBUG: fe f7 fe b5 99 61 33 33 62 1a 6b 32 40 3f 7d 4d
[rtmpdump] DEBUG: 25 8c 71 33 d1 fe 7f 50 9b 1a 78 94 56 1f fa d0
[rtmpdump] DEBUG: 9f 91 db 3d 9b 5d b8 83 43 30 1f 84 5b dc b0 6c
[rtmpdump] DEBUG: 72 3a fa 92 dd c8 d2 2c 10 e9 4d 29 d0 7c 56 be
[rtmpdump] DEBUG: 34 37 0c 6d 31 03 af 56 9b 26 09 f7 ae c5 8e 9d
[rtmpdump] DEBUG: e3 9c c9 52 68 b3 7d ba 4c 02 97 c8 21 e4 ce 66
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: bd 90 42 c2 2a f6 98 6c 1d 8f 02 00 65 fc 3a 5f
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: 29 1c 2d 1c 46 67 d7 94 ba 27 05 26 55 2d cc 56
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: cc 18 07 1c 9d fe b2 bd f8 78 2c 05 42 08 5e 93
[rtmpdump] DEBUG: 10 89 61 f3 48 98 03 65 36 5c c5 7b 35 11 69 42
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: fc 53 f0 12 3b 22 69 6d 23 dc 34 f9 bd b8 1c 1c
[rtmpdump] DEBUG: 01 9e cb 83 6f 29 aa 0d cd d2 31 b4 6e c4 d2 ec
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 68 13 2c 83 57 61 78 cf b9 e9 e0 f9 91 12 cd 78
[rtmpdump] DEBUG: 89 09 48 8c c9 cb 16 01 9c c3 ac f3 32 54 43 85
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 36 0c 9f 81 32 f1 2a e6 3b 7f 6e 43 12 d7 26 ad
[rtmpdump] DEBUG: cb 03 94 6f 68 98 90 5e 57 f4 f1 c1 5c 13 3a fb
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 68 13 2c 83 57 61 78 cf b9 e9 e0 f9 91 12 cd 78
[rtmpdump] DEBUG: 89 09 48 8c c9 cb 16 01 9c c3 ac f3 32 54 43 85
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 180 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	[ Server.Reject ] : (_defaultRoot_, _defaultVHost_) : Application (hds) is not defined.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1484, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1155, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1422, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 2] No such file or directory: '-'

Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Failed to recognize file format.


Exiting... (End of file)

**Comment by dstftw** [comment]
What if you just download it without streaming to stdout?

**Comment by JJ-Jana** [comment]
If I just downloaded it, of RTLNow, that dont works. 
----------

youtube-dl --verbose http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015
[1] 1277
[2] 1278
tuxxen@tuxxen-rechner:~$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] folge-2: Requesting header
[redirect] Following redirect to http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&productdetail=1
[generic] folge-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] folge-2: Downloading webpage
[generic] folge-2: Extracting information
ERROR: Unsupported URL: http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&productdetail=1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 937, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 11, column 117
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1467, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&productdetail=1

^C
[1]-  Exit 1                  youtube-dl --verbose http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855
[2]+  Fertig                  player=1


I said it in my first post, just the stream method with mplayer, youtube-dl and rtmpdump are working. RTLNow videos has a DRM . 

But other sites there works the stream. Has rtl change something? Or is the new update of youtube-dl a bug? Older version of youtube-dl I tried and it dont works on RTLNow too. :-( Could a change been of RTLNow?

**Comment by jaimeMF** [comment]
@JJ-Jana you have to quote the url, otherwise youtube-dl only gets `http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855`

**Comment by JJ-Jana** [comment]
@jaimeMF, yes thats right. I thought with --verbose is full output. Maybe I use now without --verbose, but Download not working, I said in my first post, too. Just the stream works bit not for the last days. :( 


youtube-dl http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855
[generic] folge-2: Requesting header
[redirect] Following redirect to http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&productdetail=1
[generic] folge-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] folge-2: Downloading webpage
[generic] folge-2: Extracting information
ERROR: Unsupported URL: http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&productdetail=1

**Comment by dstftw** [comment]
@JJ-Jana did you even read @jaimeMF post? You **have** to put the URL into **quotes** in order for shell not to drop everything after an **ampersand** ([more on this](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)):
```
youtube-dl --verbose 'http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015'
```

**Comment by JJ-Jana** [comment]
Oh, I am so sorry. I have not read right what jaime wrote. My english is not the best, excuse. Why I have to quote the url at RTLNow? On youtube.com I use everytime without quote and it works. 

And the download at RTLNow is not my problem. This dont works. I know it a logn time. 

But look now with quote:


youtube-dl --verbose 'http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[RTLnow] 201855: Downloading webpage
[RTLnow] 201855: Downloading player data XML
[debug] Invoking downloader on u'rtmpe://fms.rtl.de/hds'
[download] Destination: Die Versicherungsdetektive - Folge 2-201855.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmpe://fms.rtl.de/hds -o 'Die Versicherungsdetektive - Folge 2-201855.flv.part' --swfVfy http://rtl-now.rtl.de/includes/vodplayer.swf --pageUrl 'http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015' --playpath mp4:201855/manifest-hds --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : hds
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:201855/manifest-hds
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/hds
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015
[rtmpdump] DEBUG: app      : hds
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: fa 8f 89 07 71 e4 12 ea 28 ea bf d2 df 9b 8e 55
[rtmpdump] DEBUG: cf 62 03 4a e3 c9 77 a5 6f 69 4d e3 39 cb 1b a5
[rtmpdump] DEBUG: HandShake: Type Answer   : 06
[rtmpdump] DEBUG: HandShake: Server Uptime : 1391468803
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 501
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: be fe 36 27 d6 b3 e8 48 cc 21 0d 6d 96 32 b5 74
[rtmpdump] DEBUG: f3 38 d2 70 e7 c6 e9 c8 d2 e8 18 21 92 a5 5b a4
[rtmpdump] DEBUG: 84 f6 63 7b 06 86 e9 45 1e 26 35 05 e5 02 92 ab
[rtmpdump] DEBUG: cf f3 71 0f 20 79 eb ec e9 a2 23 69 03 37 9d 6b
[rtmpdump] DEBUG: 0a 95 ea 54 d6 f9 ca 1c ac 60 f5 48 05 2e e4 f8
[rtmpdump] DEBUG: f7 6e 1c c1 ab 0e ed ab bb c3 ad 6b 04 c8 25 b2
[rtmpdump] DEBUG: 87 26 29 e0 0d bd 89 17 c3 2a 42 9a 2a 1c 6f 27
[rtmpdump] DEBUG: e1 0a f5 e2 2d 97 cf a5 2f ed 12 52 ce 76 6a c9
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: 81 77 16 56 78 3d f2 33 39 ff d7 d7 85 53 57 60
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: 59 3d 13 28 30 fb 47 c4 73 7e 12 92 68 c2 cf 2b
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 27 d4 0d 9a 14 9d a3 ef 84 6b de 6e 7c 91 74 57
[rtmpdump] DEBUG: 9c c9 40 fa 74 85 5d 0c 4e 52 53 57 a7 87 e8 8e
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 8e 7c 0f c2 2a 17 40 09 fb 2d 9f 8a cf 3c c6 f9
[rtmpdump] DEBUG: 2b ba f7 1a 7e 13 ac 0d d4 45 c3 55 03 55 d7 87
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: a7 27 e0 f0 14 e3 f4 6a 49 76 93 14 da 62 c9 c3
[rtmpdump] DEBUG: 67 a8 d6 a7 13 91 68 a5 c0 be 30 bd a6 93 eb 1d
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 49 3e 2b 93 5f 30 d4 ce 08 61 81 3f 88 11 c2 89
[rtmpdump] DEBUG: 3d 3a 19 8d 92 bd 92 02 d3 53 10 e2 2b e5 84 c6
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: a7 27 e0 f0 14 e3 f4 6a 49 76 93 14 da 62 c9 c3
[rtmpdump] DEBUG: 67 a8 d6 a7 13 91 68 a5 c0 be 30 bd a6 93 eb 1d
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 180 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	error>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Rejected>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	[ Server.Reject ] : (_defaultRoot_, _defaultVHost_) : Application (hds) is not defined.>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_error>
[rtmpdump] ERROR: rtmp server sent error
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <close>
[rtmpdump] ERROR: rtmp server requested close
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : fms.rtl.de
[rtmpdump] DEBUG: Parsed app     : hds
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : fms.rtl.de
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:201855/manifest-hds
[rtmpdump] DEBUG: tcUrl    : rtmpe://fms.rtl.de:1935/hds
[rtmpdump] DEBUG: swfUrl   : http://rtl-now.rtl.de/includes/vodplayer.swf
[rtmpdump] DEBUG: pageUrl  : http://rtl-now.rtl.de/die-versicherungsdetektive/folge-2.php?film_id=201855&player=1&season=2015
[rtmpdump] DEBUG: app      : hds
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: ce bb 86 a6 57 09 84 a6 96 0b 04 d1 7a 3b 9b 3c
[rtmpdump] DEBUG: 4b d9 68 c1 71 e8 13 70 62 28 2e d9 7e 70 5e 3a
[rtmpdump] DEBUG: SWFSize  : 1051380
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 391, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1484, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1155, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1417, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1359, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 490, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


Many errors, but this is not my problem. My problem is just the stream funktion dont works since some days any more .( Has no one an idea?

**Comment by jaimeMF** [comment]
> Why I have to quote the url at RTLNow? On youtube.com I use everytime without quote and it works. 

That's how the shell works, the documented linked by @dstftw explains the details.

> Many errors, but this is not my problem. My problem is just the stream funktion dont works since some days any more .( Has no one an idea? 

Since the download itself fails, streaming to stdout obviously won't work. We first need to make the download work.

**Comment by JJ-Jana** [comment]
Oh, that was it. Okay Im sorry.
The download works never before at rtlnow . I read in the internet this could be becuse rtlnow videos have drm . Someone of debianforum.de says he would watch rtlnow videos with mplayer and youtube-dl over with rtmpdump. And he gave me a command like do this:

mplayer <(youtube-dl --no-playlist -o - "URL")

He says the vidro will not really downloaded just in the tmp and will delete after close or something right this. I think that rtlnow has change something thst we users do not this and have to use damn flas playet. :-( Other sites works great without this errors. Just rtlnow sites. But a codec is not misding right?

**Comment by JJ-Jana** [comment]
Hello? What does have to do the shit of you? I deal with this post and this type purely nothing at all! Only because somebody does not look in the course with Git, must I suffer from it? Thank you very much! Well, you wanted never to help me anyway really! Then it can also make no difference to me. But only thus as an info if this type is the same one like me he must have the same address IP!

**Comment by JJ-Jana** [comment]
Hello, please delete my Issue here. This Issue is not right any more. Now it gives new URL see like here: Site request: www.nowtv.de, successor to rtl-now #5771

**Comment by dstftw** [comment]
Will be covered by nowtv.de in the next version.
