### ISSUE TITLE
youtube-dl no longer downloading entire channels

### ISSUE THREAD

**Issue by AbuFiraas** [rg3/youtube-dl#5685]
I was using the following command to download entire channels, and it was working pretty well, with the occasional "content too short" error (which from what I understand, is youtube's fault):

youtube-dl -citw ytuser:<youtube username>

However now when I attempt to download a channel, it never actually takes place. It starts through the usual output, but then just stops after "extracting video information". I've tried it on several different channels, all with the same results Output below:

<path>$ youtube-dl -citw ytuser:SheikhOmarBakri
[download] Downloading playlist: SheikhOmarBakri
[youtube:user] SheikhOmarBakri: Downloading video ids from 1 to 51
[youtube:user] playlist SheikhOmarBakri: Downloading 1 videos
[download] Downloading video #1 of 1
[youtube] Setting language
[youtube] UKY3scPIMd8: Downloading webpage
[youtube] UKY3scPIMd8: Downloading video info webpage
[youtube] UKY3scPIMd8: Extracting video information

Then it just stops right there, whereas before it would continue to actually download the channel

The only thing I can think of is that maybe something went wrong with python? But as far as I can tell, I have python installed.

Can someone point me in the right direction?

Running Ubuntu 14.04

**Comment by yan12125** [comment]
Maybe it's again a youtube server issue. Add `-v` option, wait for more time and check whether there's a timeout error or not. The default timeout in youtube-dl is 600 seconds. Use ```--socket-timeout``` if you don't want to wait for such a long time. For other problems, post the full verbose log.

**Comment by sharethewisdom** [comment]
I think this is related to the fact that youtube has (abandoned the old API)[https://support.google.com/youtube/answer/6098135?hl=en], although it should have downloaded (this one video)[https://www.youtube.com/watch?v=UKY3scPIMd8].

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by AbuFiraas** [comment]
Thanks, following the "How do I update youtube-dl?" section worked! apt-get said that youtube-dl was already at the newest version but apparently not :P

**Comment by sharethewisdom** [comment]
> apt-get said that youtube-dl was already at the newest version
packages can be downloaded from mirrors that aren't up-to-date, try updating `/etc/apt/sources.list` with synchronized mirrors.

**Comment by jeffreyschultz** [comment]
Any resolution to this issue? I am using the latest version from yesterday. Using Mac OS X I ran the following in terminal. Before I start mucking around with the source code myself, I wanted to make sure I am using the proper arguments.

youtube-dl -citw -v ytuser:ChemPlayer

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-citw', u'-v', u'ytuser:ChemPlayer']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.18
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[youtube:user] ChemPlayer: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] ChemPlayer: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1884, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jeffreyschultz** [comment]
One other thing to mention is that I think his channel is "Chem Player", which I can't seem to enter into youtube-dl. It treats the "Player" as a separate channel.

**Comment by dstftw** [comment]
There is no such channel https://www.youtube.com/user/ChemPlayer. The channel is https://www.youtube.com/channel/UCiU1dHvZObB2iP6xkJ__Icw, so use this URL.

**Comment by jeffreyschultz** [comment]
Never mind. The following worked.

youtube-dl -citw -v https://www.youtube.com/channel/UCiU1dHvZObB2iP6xkJ__Icw/featured

It doesn't like a username with a space in it. I can use ytsearch but then I get a bunch of unexpected results.

**Comment by jeffreyschultz** [comment]
You beat me to it! Very nice response time.

**Comment by jeffreyschultz** [comment]
Might be a problem--i don't know. The site says this channel has 139 videos. The tool only reports 106.

**Comment by dstftw** [comment]
Exactly 106 videos https://www.youtube.com/channel/UCiU1dHvZObB2iP6xkJ__Icw/videos - count yourself.

**Comment by jeffreyschultz** [comment]
Hmmm... then Youtube is reporting an incorrect number. I didn't count them myself, but I certainly appreciate the effort you put into it! If you go to a search result where they show up and hover over their username, it says they have 139 videos, unless that count somehow includes hidden or total videos that may no longer be available.

I apologize for you having to put in the effort. I had been having issues with the tool for a week or so, and saw the discrepancy and tacked it onto this list.

I thank you for your assistance. The tool works as advertised! :+1:
