### ISSUE TITLE
Thumbnails not being embedded

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#5840]
It also leaves the thumb jpg around after the attempt to embed it in the file.

user@lappy/~$ youtube-dl -t --embed-subs --add-metadata --xattrs --console-title --embed-thumbnail https://www.youtube.com/watch?v=tiOXY1fuv4k
[youtube] tiOXY1fuv4k: Downloading webpage
[youtube] tiOXY1fuv4k: Extracting video information
[youtube] tiOXY1fuv4k: Downloading DASH manifest
[youtube] tiOXY1fuv4k: Downloading thumbnail ...
[youtube] tiOXY1fuv4k: Writing thumbnail to: Cre8ive Exercise-tiOXY1fuv4k.jpg
[download] Destination: Cre8ive Exercise-tiOXY1fuv4k.f136.mp4
[download] 100% of 14.21MiB in 00:07
[download] Destination: Cre8ive Exercise-tiOXY1fuv4k.f141.m4a
[download] 100% of 3.34MiB in 00:02
[ffmpeg] Merging formats into "Cre8ive Exercise-tiOXY1fuv4k.mp4"
Deleting original file Cre8ive Exercise-tiOXY1fuv4k.f136.mp4 (pass -k to keep)
Deleting original file Cre8ive Exercise-tiOXY1fuv4k.f141.m4a (pass -k to keep)
[ffmpeg] Adding metadata to 'Cre8ive Exercise-tiOXY1fuv4k.mp4'
[ffmpeg] There aren't any subtitles to embed
[metadata] Writing metadata to file's xattrs
ERROR: Only mp3 and m4a are supported for thumbnail embedding for now.

**Comment by vxbinaca** [comment]
Thanks! Much appreciated!

**Comment by sebma** [comment]
Hi this issue is not solved, see the following :

$ youtube-dl --restrict-filenames --format 18 --embed-thumbnail --verbose http://youtube.com/watch?v=Lac9MORX5oY
[debug] System config: []
[debug] User config: [u'--ignore-errors', u'--continue', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'-f', u'mp4/flv', u'--add-metadata', u'--write-description']
[debug] Command-line args: [u'--restrict-filenames', u'--format', u'18', u'--embed-thumbnail', u'--verbose', u'http://youtube.com/watch?v=Lac9MORX5oY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.8 - Linux-3.16.0-41-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Lac9MORX5oY: Downloading webpage
[youtube] Lac9MORX5oY: Extracting video information
[youtube] Lac9MORX5oY: Downloading DASH manifest
[info] Writing video description to: La_Parole_est_puissante_-_Shora_KUETU__18__Lac9MORX5oY.description
[debug] Invoking downloader on u'https://r7---sn-4gxx-25gd.googlevideo.com/videoplayback?mn=sn-4gxx-25gd&expire=1434987154&pl=18&requiressl=yes&ip=82.246.107.187&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-AEL_Mg-pLxzPG84nTyQ_mPt9tIyPyHPPH-R-0PIRm339&initcwndbps=772500&upn=3SFG6ol5N-k&sver=3&mm=31&source=youtube&ratebypass=yes&dur=12488.248&mv=m&mt=1434965517&ms=au&fexp=9405969%2C9407141%2C9408093%2C9408142%2C9408214%2C9408420%2C9408710%2C9412773%2C9413503%2C9414627%2C9415071%2C9415304%2C9415636%2C9415969%2C9416126%2C9416456%2C952640&key=yt5&itag=18&mime=video%2Fmp4&ipbits=0&signature=CC14A82DE47F7D7BC122E62AF83B9A2159CC6C33.5D4CC9A1505B515C1436D8277F01874E29ADDD70&lmt=1404999344340158'
[download] La_Parole_est_puissante_-_Shora_KUETU__18__Lac9MORX5oY.mp4 has already been downloaded
[download] 100% of 860.62MiB
[ffmpeg] Adding metadata to 'La_Parole_est_puissante_-_Shora_KUETU__18__Lac9MORX5oY.mp4'
[debug] ffmpeg command line: avconv -y -i La_Parole_est_puissante_-_Shora_KUETU__18__Lac9MORX5oY.mp4 -c copy -metadata 'comment=http://www.tv2vie.org/

« Au commencement était la Parole, et la Parole était avec Dieu, et la Parole était Dieu. Elle était au commencement avec Dieu. Tout a été fait par elle, et rien de ce qui a été fait n'"'"'a été fait sans elle. En elle était la vie, et la vie était la lumière des hommes. La lumière brille dans les ténèbres, et les ténèbres ne l'"'"'ont pas accueillie. » Jean 1:1-5' -metadata 'description=http://www.tv2vie.org/

« Au commencement était la Parole, et la Parole était avec Dieu, et la Parole était Dieu. Elle était au commencement avec Dieu. Tout a été fait par elle, et rien de ce qui a été fait n'"'"'a été fait sans elle. En elle était la vie, et la vie était la lumière des hommes. La lumière brille dans les ténèbres, et les ténèbres ne l'"'"'ont pas accueillie. » Jean 1:1-5' -metadata 'artist=TV2VIE pour Jésus-Christ' -metadata 'title=La Parole est puissante - Shora KUETU' -metadata date=20140611 -metadata 'purl=https://www.youtube.com/watch?v=Lac9MORX5oY' La_Parole_est_puissante_-_Shora_KUETU__18__Lac9MORX5oY.temp.mp4
ERROR: Only mp3 and m4a are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1527, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/embedthumbnail.py", line 78, in run
    raise EmbedThumbnailPPError('Only mp3 and m4a are supported for thumbnail embedding for now.')
EmbedThumbnailPPError

Can you please look into it ?

**Comment by pulpe** [comment]
@sebma In latest version it works. If you don't know how to update, look here https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl

**Comment by sebma** [comment]
I am using youtube-dl launchpad package "2015.06.15-1~webupd8~utopic0" from "https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8?field.series_filter=utopic" but youtube-dl --version says : 2015.05.04

Is there another launchpad PPA repository dedicated to youtube-dl so I can use it for my ubuntu automatic updates ?

**Comment by vxbinaca** [comment]
@sebma  Switch to the pip version it stays fresh

Disable the custom PPA for youtube-dl and then do this:

```
sudo apt-get purge youtube-dl 
sudo apt-get update
sudo apt-get install python-pip atomicparsley
sudo pip install youtube-dl
```

To upgrade in the future, use:

```sudo pip install --upgrade youtube-dl```

Your version should report the latest.

**Comment by sebma** [comment]
Thanks, but now the version is the same as that in the launchpad package (2015.06.15), I don't know what went wrong, lol.

Now, thumbnail embedding works fine.

I understand the pip method but I wanted all my packages to be updated via : 
sudo apt-get upgrade

That is why I am looking for a youtube-dl dedicated launchpad PPA, do you know if there is any ?

**Comment by vxbinaca** [comment]
Try prodding the maintainer on Ubuntu repository to update his version rather than use a PPA.
