### ISSUE TITLE
subtitles (second) lines missing for videos from BBC iplayer (extractor = bbc.co.uk)

### ISSUE THREAD

**Issue by Pat38** [rg3/youtube-dl#6038]
Hello everybody,

When downloading subtitles files (*.srt) with the option "--write-sub" or the option "--all-subs" applied on videos from the BBC, the files contain only the first line of each dialogue. All the second lines are missing.
 
Thank you in advance for fixing this bug.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by Pat38** [comment]
For example this one : 

http://www.bbc.co.uk/iplayer/episode/b012cnkx/guilty-pleasures-luxury-in-2-the-middle-ages

**Comment by Pat38** [comment]
youtube-dl --version
2015.06.15

**Comment by yan12125** [comment]
Thanks for the report. This problem will be fixed in the next version.

I've changed how subtitles are handled in youtube-dl. You need some additional options ```--convert-subtitles srt``` to get a .srt file. For example:
```
youtube-dl --write-sub -v --convert-subtitles srt "http://www.bbc.co.uk/iplayer/episode/b012cnkx/guilty-pleasures-luxury-in-2-the-middle-ages"
```

There's a known bug. If you use ```--skip-download```, ```--convert-subtitles``` is ignored. A current workaround is creating a fake file "Guilty Pleasures - Luxury in..., 2. The Middle Ages-b012cnhl.flv" and omitting ```--skip-download```
