### ISSUE TITLE
How can I get youtube-dl to slow down for a moment when other applications (e.g. web browser) need internet bandwidth?

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#6114]
As someone who doesn't have internet at home, I love using Youtube-dl when I'm at a coffee shop and downloading all the youtube videos for viewing offline when I'm back home. Thank you, developer(s).

How can I have bandwidth-maximizers (a euphemism for bandwidth hogs) like youtube-dl and wget to automatically yield bandwidth to other applications, without my having to specify a maximum download speed?
Let's say I'm downloading a 500mb Youtube video. If internet bandwidth is used exclusively for the video, let's say it would take 10 minutes to download. Let's say that at the fifth minute of downloading, I need to check a website on my web browser. I find that the webpage loads very very slowly (if at all). I could do several things, all not ideal:
1. Temporarily cancel the youtube-dl process
2. Wait until youtube-dl is finished
3. Next time I use youtube-dl specify a maximum download speed using the rate-limit option (i.e., -r or --rate-limit)

I'd rather youtube-dl (or wget) be sensitive to other applications/programs on my linux computer and temporarily decrease download speed when it senses other programs are in need of the internet. Is this possible? How can I do this?

**Comment by dstftw** [comment]
Shaping bandwidth and prioritizing traffic are responsibilities of routing software not end-user program. You'll need to figure out how to prioritize traffic for "important" applications (e.g. your browser) on your OS or if it's not capable to do it out of the box install some personal network shaper/balancer with per applications policies.
I'm closing this since it's out of scope of youtube-dl.
