### ISSUE TITLE
Integrate with Electron

### ISSUE THREAD

**Issue by steelbrain** [rg3/youtube-dl#6143]
I am trying to extract a few videos from URLs like http://kasa.com/2015/06/19/saving-your-vacation/
They have iframes and sometimes flash objects that are added using javascript on document ready and stuff, and [Electron][1] supports headless DOM interactions and programmatic usage.
So I want to load urls in electron and when their document is ready and all the content is loaded, I wanna pass that document's current HTML to youtube-dl to extract and do it's magic on.
Does Youtube-DL supports HTML input like that? if not then can we get it any time soon?

[1]:https://github.com/atom/electron

**Comment by jaimeMF** [comment]
Even if it would only be used for the generic extractor, I don't like that option too much since we could also need the url for cases where the files are specified as relative paths. I understand that only giving the urls wouldn't be enough because the content is generated with JS, but I think that the proper way is to add a new extractor for that site (feel free to open a new issue and if you have spare time [you can try to implement it yourself](https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions)), I would doubt that it can't be reproduced using python.

Alternative approach: You can always start an http server that servers the webpage and run `youtube-dl localhost:<random port>`, it's not pretty but it should work.

**Comment by steelbrain** [comment]
@jaimeMF I just had another idea, since electron is all nodejs and chromium, maybe we could spawn it and listen on a port to proxify the requests, specify it as a proxy in youtube-dl. and then it loads those pages in itself and when the DOM triggers the `DOMContentLoaded` event, we could complete the proxification event!

**Comment by steelbrain** [comment]
:disappointed: didn't work. I think I am gonna write site rules then. Thanks.
