### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kesavanm** [rg3/youtube-dl#618]
When I try with this , I'm getting the following error. Did I miss something?

```
priya@localhost:~$ /usr/local/bin/youtube-dl http://www.youtube.com/watch?v=IutLHjlV4_k
[youtube] Setting language

WARNING: unable to set language: <urlopen error [Errno -3] Temporary failure in name resolution>
[youtube] IutLHjlV4_k: Downloading video webpage
ERROR: unable to download video webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
priya@localhost:~$
```

**Comment by michu1989** [comment]
I had a similar problem. 

> youtube-dl https://youtu.be/i50jx4pMGTw
[youtube] i50jx4pMGTw: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'),))

and

> youtube-dl https://youtu.be/i50jx4pMGTw
[youtube] i50jx4pMGTw: Downloading webpage
[youtube] i50jx4pMGTw: Downloading video info webpage
ERROR: i50jx4pMGTw: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


I am using ubuntu on WSL Windows 10. At the beginning I installed the program by:
`sudo apt-get install youtube-dl`

The attempt to download any movie ended with the above errors.



I found this solution on the Ubuntu forum.

```
 sudo apt-get remove youtube-dl
sudo apt-get install python-pip  
sudo pip install youtube-dl  
```


It worked for me.

**Comment by Nottt** [comment]
I think most people coming here from google only wants to know if there's a flag or something to just retry or keep retrying for X amount of time.

When you are doing big downloads, or a playlist, it's really annoying if this happens and you waste everything you have already downloaded
