### ISSUE TITLE
youtube-dl is downloading incorrect audio/mp4 files

### ISSUE THREAD

**Issue by saundershayes** [rg3/youtube-dl#6251]
Recently youtube-dl has been downloading audio/mp4 files with a file size different from the file size specified in the MPEG-DASH MPD. For example, if I get the MPEG-DASH MPD using youtube-dl 

curl $(youtube-dl https://www.youtube.com/watch?v=x9vmoQ5WABU --youtube-include-dash-manifest --dump-intermediate-pages -s | grep manifest.google | cut -d ' ' -f 5)

you can see that the content length of the audio/mp4 files is supposed to be 3702900 and 7431829 bytes, but instead youtube-dl gives audo/mp4 files that are 3740463 and 7469392 bytes. When the youtube client javascript makes requests for the audio/mp4 files, it expects the files to be the ones specified in the MPD with the above command, so it would seem that youtube-dl is downloading incorrect/modified audio/mp4 files.

**Comment by dstftw** [comment]
Metadata served by DASH manifest are incorrect.

**Comment by saundershayes** [comment]
If the metadata is incorrect then are you also saying that audio file requests from youtube.com specify an incorrect content length in their request parameters? The content length matches the manifest for every other audio/video format. Why do you think the metadata from the DASH manifest is incorrect?

**Comment by dstftw** [comment]
Sorry, I've misread your post (it's the bitrate that is is usually incorrect). Filesize shift is due to youtube-dl fixup policies to fix known issues with media files (you may notice `[ffmpeg] Correcting container in` is output). In particular this happens for `m4a_dash` container. You can pass `--fixup never` to disable this completely. Then you'll get files of the same size as in manifest.

**Comment by saundershayes** [comment]
Great thanks! That did the trick. Appreciate the help.
