### ISSUE TITLE
Downloading playlists from the last video to the first video

### ISSUE THREAD

**Issue by Asad3ainJalout** [rg3/youtube-dl#6308]
Hello, I have been loving your program so far, its absolutely amazing. I was wondering however, if there is a way to download a playlist backwards. Some Youtubers have the first video of the series last on the playlist, with the latest video first. Usually, when i download their videos, to force the videos to be in order on my filesystem i use "youtube-dl -o '%(autonumber)s-%(title)s' url.to.playlist"

I tried useing --playlist-start=12 --playlist-end=1 to no avail. Is there a way to do it that i missed?

**Comment by jaimeMF** [comment]
Try with the `--playlist-reverse` option, if I'm not mistaken you should use --playlist-end=12 and the first video to be downloaded will be the 12nd entry.

**Comment by Asad3ainJalout** [comment]
so i checked my man pages, and tried to run it, and there is no --playlist-reverse option. This is on the current stable version of debian

**Comment by jaimeMF** [comment]
It's available [since December 2014](https://github.com/rg3/youtube-dl/commit/ff815fe65aab83db7e11251db5eafc76504adf05), the version in debain is probably older. [Read our FAQ](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#how-do-i-update-youtube-dl) to get the last version.

**Comment by Asad3ainJalout** [comment]
Thank you very much (although I am a bit late)
