### ISSUE TITLE
Wait for user input after downloading

### ISSUE THREAD

**Issue by Krzysiu** [rg3/youtube-dl#6522]
THE CASE. Hello! There's no way in Windows to log all console output or keep command line window opened after executing an application. The workaround - creating batch file with "youtube-dl.exe %&#42;{EOL}pause" - could give different results than direct execute (it's my case&#42;). 

THE REQUEST. So my request is the new command line option in "Verbosity / Simulation Options" section to make youtube-dl wait for user input after doing its job, so user could read debug messages. Of course it's not needed when user uses cmd.exe, but when running it externally, it would help a lot. 

SIMILAR OPTIONS IN OTHER APPS. I've seen some apps having such switch. The example is TrID. It's there as "-w Wait for a key before exiting".

PROPOSED BEHAVIOR. In youtube-dl there could be like switch like --wait or --user-input or --pause (I think that 1st is the best) with description "wait for user input after completing job" and youtube-dl would show "Press any key to continue..." in a new line after completing all jobs. I thought about description "...after download", but it wouldn't be clear for case when user is downloading whole playlist or other job with more than one download.

Greetings and thanks for your work :)

&#42; youtube-dl gives me an error when I run it from Firefox, but command line window closes and I don't see how it's named. When I'm creating batch file with pause on the end, it works fine, so I can't reproduce it :)

**Comment by ad-m** [comment]
:+1:

PS. Use Linux, please.

**Comment by dstftw** [comment]
Just run youtube-dl in opened cmd.exe.

**Comment by Krzysiu** [comment]
@dstftw you didn't read my request, did you? Your "solution" won't help in my case.

As you can see - http://superuser.com/questions/306167/how-to-prevent-the-command-prompt-from-closing-after-execution - it's rather a popular problem, but here every other solution than built-in could change the result. It doesn't matter if it's cmd.exe, start.exe or batch file. It's just different, produces different result, runs application in slightly different env.

**Comment by yan12125** [comment]
> The workaround - creating batch file with "youtube-dl.exe %*{EOL}pause" - could give different results than direct execute (it's my case*). 

What's the difference? The results should be the same.

**Comment by midas02** [comment]
@phihag  Can this be reopened please? This suggestion was never even discussed properly.

I would be really keen on such a feature as well, as it makes it much easier to call youtube-dl from within shell environments. Using batch files is not always desirable, and is sometimes even impossible (e.g. they're impossible to use with accented characters).

**Comment by yan12125** [comment]
On Windows this command should make the same effect like --wait:
```
youtube-dl https://youtube.com/xxx --exec "pause"
```

**Comment by midas02** [comment]
Thanks @yan12125, hadn't thought of that. Still, it would make it easier to have such an option available. Is there any reason for not implementing it? I can't imagine it would take a long time to implement.

**Comment by yan12125** [comment]
You're right --exec is not the best solution.

> Using batch files is not always desirable, and sometimes even impossible (e.g. they're impossible to use with accented characters)

Anything wrong with accented characters?

**Comment by midas02** [comment]
Yes. Try using a word like Löwe in a batch file. The umlauted o will come out in all kinds of shapes and sizes, depending on the character set the user's computer is using.
Another issue is when a string contains a percent sign. Batch files interpret these as variables, so you have to double them before writing that string to a batch file.
So the above are just two examples of why it's complicated to work with batch files, and you sometimes have to re-engineer your strings before writing them to batch files just because you know they will be mishandled. It's much easier if it could be avoided altogether.

**Comment by yan12125** [comment]
I see. It's a pity that Windows has awful Unicode support. I guess the reason that this function is not implemented in youtube-dl is that it's totally unrelated to video downloading. Instead, it's more related to process handling of the operating system. To get things like "Wait for a key before exiting" correctly implemented in Python is absolutely difficult, so it's better to leave things handled by the underlying operating system. (for example the "pause" command on Windows)

> it makes it much easier to call youtube-dl from within shell environments

Could you describe more? Although I have no plan to reopen this, it's always harmless with some brainstorming :)

**Comment by midas02** [comment]
>>it makes it much easier to call youtube-dl from within shell environments

> Could you describe more? Although I have no plan to reopen this, it's always harmless with some brainstorming :)

Nothing special. Imagine pieces of code where a programmer wants to invoke youtube-dl, for instance with functions like ShellExecute and the likes. Then you may want to need a way to freeze the output of youtube-dl before the execution window disappears, like when you're using the -F parameter. So again, there are ways of engineering around that, but it's easier if you could leave that task up to youtube-dl.

**Comment by yan12125** [comment]
Hmm, I heard that Powershell supports UTF-8 better. How about giving it a try?

**Comment by midas02** [comment]
Ah don't worry, I was only interested in the --wait option. For the time being, I'll just work around it by adding ' && pause ' to my youtube-dl strings.

**Comment by sngbrdb** [comment]
Not to resurrect an old thread, but I've yet to see an answer to this and finally found one.  At some point the `--exec CMD` option was added to youtube-dl... it will execute whatever `CMD `you specify after the download has occurred - such as `timeout /t 30`  :grinning: 

However:
- You need to include the `CMD` in single quotes if there are parameters, such as `--exec 'timeout /t 30'`
- The file (fully qualified path) you downloaded is automatically passed as a parameter to the CMD being executed... the windows `timeout` command fails because it doesn't know what to do with the extra parameter  :man_facepalming:  

Workaround?  Include a return character within the quoted command  :stuck_out_tongue:  You probably need to use a config file; I don't see how you can do that from the command line.  But my config file literally looks like this:

```
--exec 'timeout /t 30
'
```


The `--exec` is on line 46, and the closing single quote is on line 47.  Without the line break, you get this output:

```
[exec] Executing command: timeout /t 30  "c:\vids\downloadedfile.mp4"
ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
ERROR: Command returned error code 1
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 2035, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\postprocessor\execafterdownload.py", line 29, in run
youtube_dl.utils.PostProcessingError: Command returned error code 1
```

With the line break:
```
[exec] Executing command: timeout /t 30
 "c:\vids\downloadedfile.mp4"

Waiting for  0 seconds, press a key to continue ...

c:\apps\internet\youtube-dl>
```

:sunglasses: 

.
