### ISSUE TITLE
Question about why requests for an MSNBC extractor have been ignored for more than a year

### ISSUE THREAD

**Issue by bonacker** [rg3/youtube-dl#6548]
My extractor request posted yesterday (8/12/15) for MSNBC.com, one of the largest news sites on the internet was closed without comment, because it was a duplicate of an earlier request. 

I see now that there is an open request https://github.com/rg3/youtube-dl/issues/2371 from February, 2014, a year and a half ago that received no replies or action.

YouTube-dl supports NBC.com, and NBC shares resources with MSNBC as they are the same company, but the URLs NBC uses are mostly MSNBC.com URLs. 

I don't understand why these requests have been completely ignored while much smaller sites receive extractors. 

Don't get me wrong. I am grateful for the outstanding work done by the YouTube-dl volunteer coders, but I'd think an important site like NBC News deserves at least a post describing why it won't work with YouTube-dl.  

Thanks for all the work you guys do.

**Comment by dstftw** [comment]
Your issue has been closed as a duplicate of another since we do the same for every duplicate we find to keep open issues as distinct as possible.
Lack of support for particular extractor may be due to lots of reasons. Generally, no responses in extractor support request issue means that no one of developers/contributors have interest/time implementing it. As you already mentioned, as volunteers we are working on things and features we prefer most.
