### ISSUE TITLE
Display currently downloaded video length

### ISSUE THREAD

**Issue by cousteaulecommandant** [rg3/youtube-dl#6567]
Sometimes knowing how many KB or % of video has been downloaded just isn't enough, and you want to preview the video to check it's working, the right topic, the correct language, etc.  So you open the .part file with a video player, and skip through the video till you find a dialog or something.  If you skip too far away, the player will get stuck at the end or stop or do something weird, which isn't too nice.

It would be nice if youtube-dl displayed the length of the downloaded video, something like

```
[download]  11.8% of 4.06MiB at 207.41KiB/s ETA 00:17 (00:12/01:43)
```

The info of the total video length can be obtained through the `%(duration)s` parameter (when available), and the current downloaded length can be approximated using a simple rule of three.

Problem with this idea is that the `duration` parameter doesn't seem to get passed to the `[download]` routines at all, so this would probably involve modifying a bunch of protocols and modules in `downloader/`; maybe it's not trivial to do.

**Comment by dstftw** [comment]
`duration` is now always available and may be incorrect. Video may be of variable bitrate so that it does not uniformly distirubted across timespan. For fragment based downloaders it would need to be extrapolated each on each fragment meaning that current timepoint and total time length of the video will jump like file size when downloading f4m or hls with native. So I can barely see any benefit in this since it would be too approximate.
