### ISSUE TITLE
E-learning courses from Microsoft Virtual Academy

### ISSUE THREAD

**Issue by accorreia123** [rg3/youtube-dl#6667]
Please do allow youtube-dl be able of downloading from https://www.microsoftvirtualacademy.com

A sample of a course is:
https://www.microsoftvirtualacademy.com/en-US/training-courses/microsoft-azure-fundamentals-virtual-machines-11788

Regards

**Comment by CollinChaffin** [comment]
HI just curious this is still open since last year, is this site still not supported?

**Comment by Hrxn** [comment]
Doesn't look like it, if it's still open..

**Comment by CollinChaffin** [comment]
I guess what I was asking since the DEVs are so awesome it's unusual to see such a popular large site  in this list without even seeing an assignment to a DEV who's working on it, especially after almost a whole year.  Hence why I was hoping a DEV could jump in and if so, there must be a big roadblock that makes this site that much different than the existing supported ones or something?

**Comment by CollinChaffin** [comment]
Is there a standard template of info we need to help dig out of the show/episode pages to place in these issues to allow dev work to start and/or if after a year there is something holding up a big site liket this from being added, is there anything the rest of us can do to assist the effort like testing, etc.?

**Comment by Hrxn** [comment]
Well, at least there seems to be a download link inside of the video player..

**Comment by CollinChaffin** [comment]
Awesome Sergey!  Thanks for adding this one!

**Comment by accorreia123** [comment]
It works great!!!

Tnkx.
