### ISSUE TITLE
REQUEST: Add qianmo.com to support list

### ISSUE THREAD

**Issue by starkshaw** [rg3/youtube-dl#6747]
Qianmo.com is a Chinese online video society, I found this site is not supported yet, and [generic] download is not valid. Please add support to this website.

**Comment by jaimeMF** [comment]
[Post an example url](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by starkshaw** [comment]
@jaimeMF Hi, here is an example URL: http://qianmo.com/kawaei/281

**Comment by TRox1972** [comment]
The site seems to be down, displaying the message "网站维护中..." (website maintenance). Anyone know if this is temporary or an lasting issue?

**Comment by starkshaw** [comment]
@TRox1972 I checked the web archive (http://web.archive.org/web/*/http://qianmo.com) it seems it at least online on Mar 14 2016

**Comment by yan12125** [comment]
https://qianmo.com/ (whose SSL certificate is for yuanqi.tv) displays something quite different from a video hosting site. Anyone know the relation of yuanqi and qianmo?

**Comment by yan12125** [comment]
And by the way, http://weibo.com/qianmoinc, which claims to be the official Weibo (a micro blog service in China), has no updates since Nov 2015. I guess the site is really dead.
@starkshaw Please close this issue if you don't need the support for qianmo.com anymore. You can always reopen it once qianmo.com is back.

**Comment by starkshaw** [comment]
@yan12125 Thanks.
