### ISSUE TITLE
unable to stop it from downloading playlist or more pages.

### ISSUE THREAD

**Issue by interneteur** [rg3/youtube-dl#6754]
I am trying to make it so if a url inserted it only downloads the webpage for that url.  And does not continue downloading the video's or playlist.  

This is what I have so far
```
                ydl_opts = {
                    'list_thumbnails:': True,
                    'no-playlist': True,
                    'youtube_include_dash_manifest': False,
                    'logger': MyLogger(),
                    'progress_hooks': [my_hook],
                }
                with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                    video = ydl.extract_info(url,  download=False)

```
But for some reason it still tries for the playlist, and continues with the channel or user.

```
02:25:06 high: worker.extract_thumb(u'http://www.youtube.com/user/Funnycatsandnicefish') (653367d9-5574-4760-ba2f-c20e96860d9b)
[youtube:user] Funnycatsandnicefish: Downloading channel page
[youtube:playlist] UUERQZLRMniqsMlgBxme32cQ: Downloading webpage
[download] Downloading playlist: Uploads from Funnycatsandnicefish
[youtube:playlist] UUERQZLRMniqsMlgBxme32cQ: Downloading page #1
[youtube:playlist] UUERQZLRMniqsMlgBxme32cQ: Downloading page #2
[youtube:playlist] playlist Uploads from Funnycatsandnicefish: Downloading 293 videos
[download] Downloading video 1 of 293
[youtube] _yzClcFwlO0: Downloading webpage
[youtube] _yzClcFwlO0: Extracting video information
```

Any help would be appreciated

**Comment by jaimeMF** [comment]
It's `noplaylist` not `no-playlist`. But the only thing that options does is that if the url also contains a video (like https://www.youtube.com/watch?v=FXxLjLQi3Fg&list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re) it forces the download of the video instead of the full playlist.

[Could explain with more detail](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#bugs) why do you need that feature and how it should work?

**Comment by interneteur** [comment]
I think it would be beneficial to the community when parsing a url with youtube-dl, it can cause for a worker to go far longer than necessary once the data needed has already been extracted.

And one could argue that the top video in the user directory is most likely the video they want to be associated with

**Comment by jaimeMF** [comment]
>  think it would be beneficial to the community when parsing a url with youtube-dl, it can cause for a worker to go far longer than necessary once the data needed has already been extracted.

If you only want to get the first video all you need to do is use `'playlistend': 1`.

> And one could argue that the top video in the user directory is most likely the video they want to be associated with

That's problematic: some may want the most recent video (from http://www.youtube.com/user/Funnycatsandnicefish/videos) while others would prefer the video featured in the user page.

Since I think that solves your problem, I'm closing the issue.
