### ISSUE TITLE
Pluralsight - banning accounts

### ISSUE THREAD

**Issue by angelbroz** [rg3/youtube-dl#6842]
Hello!

You need to be careful using pluralsight downloader specially pluralsight:course, they are banning accounts.

I made some pluralsight trial accounts, and if you don't use the necessary params your account will get banned.

As far i know you need to set the download rate to ~250k and a sleep-interval ~30

**Comment by yan12125** [comment]
Thanks for the information. However, it's not an issue in youtube-dl, so I'm closing this ticket.

**Comment by CollinChaffin** [comment]
See #6989 for proposed fix

**Comment by angelbroz** [comment]
Thanx!

**Comment by AhmedKamal20** [comment]
Is this still a thing , should I've to worry if i'm using this command ? 
youtube-dl --username <myusername> --password <mypassword> <Pluralsight Video URL>

**Comment by xfsrg** [comment]
It's definitely still possible when using with pluralsight. I was 'temporarily' banned (meaning I had to talk with support to be un-banned). Support mentioned '... requests every 10-30 seconds for a prolonged period of time'. I changed the sleep interval to 45-55 seconds, instead of the 3-5 seconds currently in the pluralsight.py, to (hopefully) avoid any further issues.

**Comment by Zainulabadeen** [comment]
How to use --sleep-interval ?

**Comment by divya369** [comment]
how to set download rate while downloading pluralsight video?

**Comment by pendave** [comment]
![F1)D`Y4WPJOP4 LPJ5X}K2M](https://user-images.githubusercontent.com/1331881/56792515-5ed73780-683c-11e9-92a1-ef3f18a5b136.png)

Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email. | Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email. | Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email. |   |   |  
-- | -- | -- | -- | -- | --
Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email. | Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email. |   |   |  
Our security systems have flagged your Pluralsight account for an unusual amount of activity. Because of this, your account has been blocked. Please note that this high volume of activity is in violation of our terms of service. If you're not aware of what is causing this high volume of activity, it is possible that your account may have been compromised. Please change your password if that is the case. We will unblock your account when you acknowledge our terms of use by replying to this email.

 
 

 
Thank you,Pluralsight Support |   | Thank you,Pluralsight Support |   | Thank you,Pluralsight Support
  | Thank you,Pluralsight Support |   | Thank you,Pluralsight Support
 
Thank you,Pluralsight Support

**Comment by pendave** [comment]
I get my new registered account works

This one with error 

> Unable to download webpage: <urlopen error [WinError 10053]

`youtube-dl --sleep-interval 60 --max-sleep-interval 100 --verbose --username "XXXXXX" --password "XXXXXX" "https://app.pluralsight.com/library/courses/javascript-module-fundamentals"`

So I try to add a proxy and it works.

`youtube-dl --proxy 127.0.0.1:1985 --sleep-interval 60 --max-sleep-interval 100 --verbose --username "XXXXXX" --password "XXXXXX" "https://app.pluralsight.com/library/courses/javascript-module-fundamentals"`
