### ISSUE TITLE
Specify default audio format

### ISSUE THREAD

**Issue by DVassilev** [rg3/youtube-dl#7058]
Hello,

When I try to --extract-audio how can I also specify a number of --audio-formats so that if it is .m4a or .mp3 or .webm it doesn't convert but if it's something else it converts to .mp3?

Additionally, with --extract-audio which formats are kept and which are converted?

Thanks,
Daniel

**Comment by yan12125** [comment]
> When I try to --extract-audio how can I also specify a number of --audio-formats so that if it is .m4a or .mp3 or .webm it doesn't convert but if it's something else it converts to .mp3?

AFAIK currently it's impossible with the CLI only, while I guess it's possible with [this approach](https://github.com/rg3/youtube-dl/#embedding-youtube-dl). Also, I think such a feature will be never implemented as a CLI option because it's highly customized and rather complicated.

> Additionally, with --extract-audio which formats are kept and which are converted?

If there are audio-only files (for example videos on YouTube), youtube-dl will just download the audio-only file and do no conversion. Otherwise, conversion occurs.

**Comment by DVassilev** [comment]
@yan12125 I understand that conversion doesn't occur if it can download the audio directly but is there any way of knowing what format it will convert to if it can't download just the audio?

**Comment by yan12125** [comment]
[This code segment](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py#L220-L263) determines the output codec from the input file codec and the preferred codec option (```--audio-format```). In short, if the preferred codec is not set, youtube-dl tries to keep the same codec as the input file.
