### ISSUE TITLE
Need help getting best possible quality for crunchyroll videos.

### ISSUE THREAD

**Issue by hdubb** [rg3/youtube-dl#7156]
I read that mkv videos have better quality than mp4

I use this code:

youtube-dl -u username -p password --verbose --batch-file C:\Users\H\Desktop\crunchyroll.txt --sub-lang enUS --write-sub --sub-format ass --embed-subs --recode-video mkv

I am getting a low bitrate for my audio. It is 64kpbs and it is "vorbis stereo"

Maybe I can try to change the audio to aac?

Also, I have a premium account so I am downloading 1080p

**Comment by hdubb** [comment]
I added:

--audio-format aac

and removed --recode-video mkv because the mp4 audio was better but then it made the subtitles into TX3G format even though I have it as --sub-format ass

I am also using ffmeg

**Comment by jaimeMF** [comment]
youtube-dl by default downloads the best quality available, I'm not an expert but you can't magically get a better quality by converting to other format. If crunchyroll doesn't provide a mkv file, converting the mp4 file won't result in a better quality.

> and removed --recode-video mkv because the mp4 audio was better but then it made the subtitles into TX3G format even though I have it as --sub-format ass

That's because the mp4 format doesn't support ass subtitles, therefore they must be converted.

If you need further help we will need the actual urls you are downloading.
