### ISSUE TITLE
Unable to download vimeo password protected videos

### ISSUE THREAD

**Issue by pokryva** [rg3/youtube-dl#7169]
Hi,
I am unable to download vimeo password protected videos. I tested and I am able to download regular vimeo videos though.

youtube-dl output:

sudo youtube-dl -U
youtube-dl is up-to-date (2015.10.13)
youtube-dl https://vimeo.com/xxxxxxxx --verbose --video-password xxxxxx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'--verbose', u'--video-password', u'PRIVATE']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.3 - Linux-3.12.31-armv6l-with-debian-7.8
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprobe 0.8.17-6
[debug] Proxy map: {}
[vimeo] xxxxxxxx: Downloading webpage
[vimeo] xxxxxxxx: Extracting information
[vimeo] xxxxxxxx: Verifying the password
[vimeo] xxxxxxxx: Downloading webpage
[vimeo] xxxxxxxx: Extracting information
ERROR: video password verification failed!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 301, in _real_extract
    flags=re.DOTALL)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 312, in _real_extract
    smuggle_url(url, {'_video_password_verified': 'verified'}))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 309, in _real_extract
    raise ExtractorError('video password verification failed!')
ExtractorError: video password verification failed!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

For obvious reasons (this is a pay-for-view video of some DIY instructions, I don't think the owner would appreciate distributing the password over the net) I cannot provide the link and the actual password. I can confirm that this video is playable, when I enter the URL via browser and provide the password.

**Comment by jaimeMF** [comment]
Thanks for the report, it should work again in the next version. Please comment here or open a new issue if it doesn't work with your video.

**Comment by pokryva** [comment]
It works like a charm, thank you!

**Comment by emma-goldman** [comment]
I'm encountering this issue again, verbose output below:

`PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx --video-password xxx -u 'PRIVATE' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'--video-password', u'PRIVATE', u'-u', u'PRIVATE', u'--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[vimeo] Logging in
ERROR: Wrong login info: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

`or

> PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx -p I5O2013 -u PRIVATE --verbose
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'-p', u'PRIVATE', u'-u', u'PRIVATE', u'--verbose']
> [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
> [debug] youtube-dl version 2018.03.03
> [debug] Python version 2.7.14 (CPython) - Windows-10-10.0.16299
> [debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
> [debug] Proxy map: {}
> [vimeo] Logging in
> ERROR: Wrong login info: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2199, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "c:\python27\lib\urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "c:\python27\lib\urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "c:\python27\lib\urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "c:\python27\lib\urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "c:\python27\lib\urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

or without -u at all:

`PS C:\Users\Xyz\Videos> youtube-dl https://vimeo.com/xxxxxxxx -p xxxxxxx --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/xxxxxxxx', u'-p', u'PRIVATE', u'--verbose']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: account username missing`

Tried updating to no avail.

Cheers

**Comment by dstftw** [comment]
Error message clearly states: Wrong login info.
