### ISSUE TITLE
Adult Swim - possbile change in permissions

### ISSUE THREAD

**Issue by JPS96** [rg3/youtube-dl#7197]
I have been using youtube-dl for a while to get "Rick and Morty" episodes form adult swim. It has been working perfectly until S02E10. I believe that they may be trying to prevent UK users from accessing the video due to copyright.
The following command:
" youtube-dl http://www.adultswim.com/videos/rick-and-morty/the-wedding-squanchers/"
Returns the following error:
" ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by JPS96** [comment]
Yeah sorry, Copy & Paste the wrong output. Here it is: 
" [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/rick                                                -and-morty/the-wedding-squanchers/']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.10.12
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-72939-g5b0f55a, ffprobe N-72939-g5b0f55a
[debug] Proxy map: {}
[AdultSwim] the-wedding-squanchers: Downloading webpage
[AdultSwim] Rick and Morty - The Wedding Squanchers Part 1: Downloading segment                                                 information
[AdultSwim] Rick and Morty - The Wedding Squanchers Part 1: Downloading m3u8 inf                                                ormation
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by                                                 HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you                                                 are using the latest version; type  youtube-dl -U  to update. Be sure to call y                                                outube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1872, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default "
Thanks

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by JPS96** [comment]
No, there is a pop up requesting me to sign in with a certain my cable provider. I live in UK and so can not complete the form.
This has not been an issue in previous video downloads.
trying older videos in the browser present me with "Video format or MME type is not supported".
Maybe this is an issue with their website!?

**Comment by kylef000** [comment]
Trying it from here in the US, it works correctly. 
`[AdultSwim] the-wedding-squanchers: Downloading webpage
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading segment information
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading m3u8 information
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading m3u8 information
[download] Downloading playlist: Rick and Morty - The Wedding Squanchers
[AdultSwim] playlist Rick and Morty - The Wedding Squanchers: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/rickandmorty/2015/10/rickandmorty_cc_209_lo9o0o9ian890be521vs/hls/rickandmorty_cc_209_lo9o0o9ian890be521vs_stream_10.m3u8'
[download] Destination: Rick and Morty - The Wedding Squanchers-mR_aktoURbqISjtz-matJw-0.mp4`

Trying with my UK located VPN reproduces the 403 error you are having. 

`[AdultSwim] the-wedding-squanchers: Downloading webpage
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading segment information
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[AdultSwim] Rick and Morty - The Wedding Squanchers: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden`

It definitely seems that region locking is the issue here.

**Comment by remitamine** [comment]
looks like the geo restriction apply on for UK IP.
in all of the urls in this episode there is this part `/no_uk_geo/`:
http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/rickandmorty/2015/10/rickandmorty_cc_209_lo9o0o9ian890be521vs/hls/rickandmorty_cc_209_lo9o0o9ian890be521vs_stream_mobile.m3u8
http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/rickandmorty/2015/10/rickandmorty_cc_209_lo9o0o9ian890be521vs/hls/rickandmorty_cc_209_lo9o0o9ian890be521vs_stream_tv.m3u8
http://amd.cdn.turner.com/adultswim/episodes/no_uk_geo/rickandmorty/2015/10/rickandmorty_cc_209_lo9o0o9ian890be521vs/hds/rickandmorty_cc_209_lo9o0o9ian890be521vs_stream_web.f4m
i tried to download with IP outside US other than UK and it's working.

**Comment by JPS96** [comment]
Thanks for the feedback guys. I had almost forgotten about this ticket. I will use a VPN to attempt this from an IP outside the UK.
Is there any protocols for marking this as solved if this is successful? Im confident that your reports, as well as  changes to the website, point to location restrictions.
Thanks JPS96
