### ISSUE TITLE
status for supported websites

### ISSUE THREAD

**Issue by zodman** [rg3/youtube-dl#7259]
Hi

i had been using youtube-dl for long time its a great software very usefull.

Well i had a idea it is posible to use the https://rg3.github.io/youtube-dl/supportedsites.html and add a red/green image and report the status supported ...

tnx!

**Comment by dstftw** [comment]
There is already such a feature (look for `(Currently broken)`). Even though I don't see much point maintaining this since it will require some human resources to keep it up to date we could otherwise throw into development.
After all when you want to download something you just giving it a try but not looking at some indicator webpage.
