### ISSUE TITLE
periscope: add support for live streams

### ISSUE THREAD

**Issue by Crihub** [rg3/youtube-dl#7501]
If possible, it would be nice to download live periscope streams, beside replays.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by bonacker** [comment]
I noticed this also. I don't have a Periscope stream to post at the moment, but this is what happens.

The live stream downloads to a file, but if you try to play the file in mPlayer or VLC, it won't play. When the stream has ended, the finished file will play perfectly.

Is there a way to pipe the downloading stream to a player rather than to a file?

**Comment by dstftw** [comment]
@bonacker use `-o -` option and pipe to whatever play you use.

**Comment by dstftw** [comment]
Live streams are downloaded just fine. Tested with live from [here](http://onperiscope.com/).

**Comment by Crihub** [comment]
Thanks all for the info. For the benefit of other users who might face the same issue: the cause was not lack of support by youtube-dl, but an old version of ffmpeg.
After updating ffmpeg to version 2.8.x, live streams are now downloaded just fine.
While the periscope live stream is ongoing you can't play the partial downloaded file (I think this is a limitation of the mp4 format), but when the stream ends (or if you quit ffmpeg pressing "q") you will get a fully functional file.
