### ISSUE TITLE
youtube download ssl error

### ISSUE THREAD

**Issue by beringov** [rg3/youtube-dl#7610]
Error with youtube downloads 

ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLEr
ror(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

Version 2015.11.21

**Comment by NicholasGFerguson** [comment]
I had the same thing happen, except my error message is a little bit longer. I had just gotten another error before this so I updated to 2015.11.21 and now this happens every time:

ERROR: Unable to download webpage: (urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)) (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by dstftw** [comment]
Duplicate.
