### ISSUE TITLE
can't download from dailymotion since today

### ISSUE THREAD

**Issue by wwwamroth** [rg3/youtube-dl#7829]
Hi guys, yesterday everything was works fine but today I can't download from daily, tried latest version but no luck.

![screenshot](https://cloud.githubusercontent.com/assets/16242980/11720258/25e73d7c-9f67-11e5-8f62-87edf42d8367.png)

Any help would be great, thanks.

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.
[**Don't post screenshots** when reporting bugs](https://github.com/rg3/youtube-dl#bugs).

**Comment by phihag** [comment]
What @dstftw means is: Please do post the output, but preferably as text. You can select text in the Windows console by right-clicking anywhere and then selecting `Mark`.

I believe this issue to be fixed in youtube-dl version 2015.12.10. See [our FAQ](https://yt-dl.org/update) if you need help updating. Thanks for the report!

**Comment by wwwamroth** [comment]
Thanks for quick update guys! its working now.
