### ISSUE TITLE
extraction error

### ISSUE THREAD

**Issue by chaitanya11** [rg3/youtube-dl#8134]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflnrstgx/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
It's likely you're using an out-dated version. Please update to the latest (2016.01.01) via [update instructions](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl). Feel free to open new issues if the problem is still with the latest version. Don't forget to include the [full verbose log](https://github.com/rg3/youtube-dl/#bugs).
