### ISSUE TITLE
AtresPlayer default HLS downloading produces non working files

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [rg3/youtube-dl#8261]
I tried to download:
http://www.atresplayer.com/television/programas/equipo-de-investigacion/temporada-1/capitulo-148-coches-robados_2016011500469.html
using the default HLS download and it produces a non working file.
But, if I download using the "http" format I get a working file.
So, either HLS download is fixed or "http" format is made the default until HLS is fixed

**Comment by saidma** [comment]
This site takes the video mp4 http://catchvideo.net/?url=http%3A%2F%2Fwww.atresplayer.com%2Ftelevision%2Fprogramas%2Fequipo-de-investigacion%2Ftemporada-1%2Fcapitulo-160-blanqueador_2016041500301.html but youtube-dl (since the November 2015 version) only download flv (F4M manifest). With this type video can not play the video online until all parts (manifest) are downloaded and attached.
