### ISSUE TITLE
Slow pull request processing

### ISSUE THREAD

**Issue by dyn888** [rg3/youtube-dl#8283]
For the past month and more i can constantly see over 100 pull requests in queue, without much action around them. Why is processing so slow -- do you lack people on this project?

In any case, my pull request is just about YouTube itags, nothing complex and it could be merged right away, yet it sits there for more than 2 weeks already. If you have time, feel free check & merge https://github.com/rg3/youtube-dl/pull/8130 ... thanks! It's basically itag info, which is already present for some itags, i only expanded it to all other itags.

**Comment by dstftw** [comment]
youtube-dl is voluntary project and most of collaborators work on issues they prefer or find most important/interesting/easy to implement/whatever. Most of us are unable to spend much time contributing due to fulltime jobs, study or another activities so that's pretty obvious we can't handle everything on time. After all last year we received about 650 PR agains 400 year before, same for issues. Moreover quite some PRs are controversial, some are waiting for author's fixes. At the moment we have more active collaborators than ever.

**Comment by dyn888** [comment]
Then again some pull requests are pretty simple, and they still wait there for weeks, with some i noticed authors even delete their fork in the meantime, or close them themselves out of frustration. Something should be done to merge new PRs faster, that's the reason i opened this in the first place. I am well aware it's a voluntary project, and PRs are crucial part of it.

**Comment by phihag** [comment]
Can you elaborate what that *something* is that should be done? I am well-aware of the problem, but have decided that I have more important priorities nowadays and just drop in for the occasional contribution.

**Comment by dyn888** [comment]
Thanks for your contributions! :)
Nothing extra, just more of what already works, for instance, accept more people to the project if that's possible, then some old PRs could be perhaps closed, if not usable anymore, or if the original author is not willing to fix them. Other than that everyone can understand popular projects will have a lot of contributions, so it's normal to wait a little.
