### ISSUE TITLE
Format Question...

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#8335]
Hello:  have been using **-f 'best[height<=?1080]/best'** to download and it is a HUGE improvement over the old 35/22/18 stuff (mostly since it can get any type like WebM, Ogg or whatever matches), but I really would prefer to save 720p over 1080 most of the time and more and more sites are full 1080.  

Sadly if I do **-f 'best[height<=?960]/best'**  it then often goes clear down to 480 if no 720 is found.  

Is it possible to do something like:  **-f 'best[height<=?960]/best[height<=?1080]/best'** so that it will pull 720 if found, if not then go to 1080??

Thanks so much!!

**Comment by dstftw** [comment]
You totally misunderstand how `/` works.
It takes first expression from the left, examines whether it matches some formats, if any - selects best from this set, otherwise it takes second expression and so on. `best[height<=?960]` means: download best format among all formats that have height lower than or equal to 960 or that does not have height at all, so it's pretty obvious it will select 480 when 720 is missing as closest one under 960.
Instead you should also limit the lower bound with `best[height>=700][height<=960]/...` or just use exact value of height `best[height=720]/...`. Also read [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by artphotodude** [comment]
Right - thanks for the clarification!  Is there also also a way to include a preference for a lower or higher bitrate in the same string?  I.E.  one video's -F returns this:

**hls-3050     mp4        1280x720   3050k , avc1, mp4a 
http-720p    mp4        1280x720   , 24fps**

So if I wanted to prefer the http over the hls, can that be done in the same -f tag, or a combination with another tag?

Thanks Again!

**Comment by dstftw** [comment]
This is all covered in aforementioned link.

**Comment by artphotodude** [comment]
**tbr** isn't working since only one of the videos lists the Bitrate.  Can I exclude the term _**hls**?
