### ISSUE TITLE
Torrent/magnets support

### ISSUE THREAD

**Issue by D4Ndan** [rg3/youtube-dl#8490]
I know there are other solutions like peerflix or webtorrent, but they're node.js apps and its usage and installation its very tedious for the average user. 

I found this while searching around:
https://github.com/touchandgo-devs/touchandgo
It's is posible to implement something like this on youtube-dl?

**Comment by dstftw** [comment]
This is out of scope of youtube-dl.

**Comment by paranormal** [comment]
Please, clear this up. Why is it out of scope? I'd like to write mentioned support.

**Comment by paranormal** [comment]
With mpv it could be a nice feature.

**Comment by Hrxn** [comment]
I agree, it is completely out of scope.

You need to get your priorities straight. youtube-dl is primarily used to download videos for archival purposes.

Besides, it is written in python, and doing torrent with python is just... not good. [Touchandgo](https://github.com/touchandgo-devs/touchandgo), what you mentioned, is based on a python wrapper for libtorrent, and I didn't hear good things about that.

libtorrent is written in C++, and I think that is the gold standard when it comes to torrent. I would definitely use a torrent client that is based on libtorrent.

Anyway, just tacking some library x, that is not written in python, to youtube-dl is just not a very good idea, because it is just not feasible. It would require too much work, that can be used elsewhere instead.

**Comment by paranormal** [comment]
No, I didn't mean using something outside of python scope. Although I agree that using c/c++ is better option, looking how flawlessly peerflix works make me think that this is an option to move on.

**Comment by Hrxn** [comment]
Well, yeah, I guess youtube-dl and node could be glued together, this would definitely open up exciting new possibilities. But as I said, it is a question of priorities..

By the way, can't you use peerflix together with mpv? Since peerflix uses Node, I'd assume that the output of the torrent stream gets directed through a local server, so it can be accessed with mpv via http, I think this should be possible.
