### ISSUE TITLE
[Support Request] for anime-on-demand.de

### ISSUE THREAD

**Issue by kitokirisaki** [rg3/youtube-dl#8518]
Example URl: https://www.anime-on-demand.de/anime/161 (This link is the Mainpage of the Anime. Not the link to the Video)

It is necessary to register

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by kitokirisaki** [comment]
There is no direct play link . But I have even copied the HTML INPUT tag .

<input class="highlight streamstarter_html5" title="Japanischen Stream mit Untertiteln starten" data-playlist="/videomaterialurl/1911/OmU/1080/KFMuN1NUNC8oQDBhMDZiNWUwNTMwMmE3NmMyNTQ3MmRhNDc3NDgxYjllZWFiNWE5NDZjYzQ3MWYxMGNhMmUzY2FmZjI0NmZlMGM=" data-otherplaylist="[]" data-displaydescription="true" data-displaytitle="true" data-nolangswitch="true" data-lang="jap" type="submit" value="Japanisch (UT)">

**Comment by kitokirisaki** [comment]
geo-restricted?

**Comment by dstftw** [comment]
You also have to provide account credentials if it requires paid subscription.

**Comment by kitokirisaki** [comment]
Can i send you the data via pm?

**Comment by kitokirisaki** [comment]
./youtube-dl https://www.anime-on-demand.de/anime/161 -u<user> --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.anime-on-demand.de/anime/161', u'-u<user>', u'--verbose']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: none
[debug] Proxy map: {}
[AnimeOnDemand] Downloading login page
[AnimeOnDemand] Logging in as <user>
[AnimeOnDemand] 161: Downloading webpage
[AnimeOnDemand] episode-1: Downloading playlist JSON
[AnimeOnDemand] episode-1: Downloading m3u8 information
ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "./youtube-dl/youtube_dl/utils.py", line 830, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)

**Comment by ztarbugz** [comment]
Currently they are switching from RTMP streams to HTML5 (beta). As kitokirisaki said an account is neccessary, but you can create a free one. The series following this link is completly free, so testing is possible: https://www.anime-on-demand.de/anime/162

**Comment by Crypt0Graf** [comment]
It is possible to download episodes from AoD with youtube-dl. They are using .m3u8-playlists in the new HTML5-version, which are supported by youtube-dl. 
You'll need to monitor the traffic, for example [with Firefox](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor). After starting the video, you'll get something like "playlist.m3u8?aodSecure_starttime" in the monitor, which can be used for some things, but is basically unusable for download. Under this entry, you'll get something like 
"chunklist_w1601181907_b13568000_", this is a playlist on 56b60eb28ccee.streamlock.net:1936 (the streaming-server of AoD) which serves the Episode in "1080p+", which is a high-bitrate FHD-video in Blu-Ray-quality. Under that, you'll get other chunklists, the next should be "chunklist_w1601181907_b6400000_", which is the playlist for "normal" Full-HD. Under this, you'll get other chunklists with lower quality. Now copy the chunklist with your preferred resolution and open a terminal for youtube-dl. Enter "youtube-dl", then paste the chunklist-URL and set an output name with "-o [Filename]". The last step is required, because youtube-dl may be unable to set a short filename; so replace [Filename] with you preferred name (need to be without space in the title).
Then press enter, and youtube-dl will download the file. This may take some time, and a 20-minute episode will need between 1.2 and 1.9 GB of space in the highest resolution.

However, this is only possible with the HTML5-version. For more information, look at my screenshot.

![aod dl](https://cloud.githubusercontent.com/assets/17383011/13643117/90b3faa6-e61f-11e5-8484-203cd9d6aaa7.jpeg)

Regards, 
CTG

**Comment by Parn06** [comment]
> Currently they are switching from RTMP streams to HTML5

While the latest version (2016.04.13) of youtube-dl works fine for series with html5, I can't download any video which is streamed the classic way (without html5).

As far as I understand the code correctly (I'm not good with python) the animeondemand extractor looks for an input with "streamstarter_html5" in its class tag. The "classic" version however does not have this tag. It would be just "streamstarter" instead.

Here are two sites to verify:
HTML5 (works just fine for all episodes): https://www.anime-on-demand.de/anime/162
classic (just downloads the teasers): https://www.anime-on-demand.de/anime/137

I suggest a similar approach as there is for downloading the teasers: If no playlist item for html5 was found, then retry looking for the classic way.

**Comment by Crypt0Graf** [comment]
Hi, the extractor for AnimeOnDemand  is still working great for HTML5-able episodes, though they changed the streaming format for desktop browsers recently.
Unfortunately, he isn't able to recognize movies like https://www.anime-on-demand.de/anime/175 or https://www.anime-on-demand.de/anime/178 , as they aren't listed like episodes.
