### ISSUE TITLE
Different return codes for different situations, please.

### ISSUE THREAD

**Issue by RonJohn2** [rg3/youtube-dl#852]
Hi,

(Great job fixing the "slow flv" issue!)

ERROR: Unable to download video webpage: HTTP Error 404: Not Found
Also, when it fails to d/l the complete video.

Please exit with different "greater than 1" codes when such errors occur.  That way, scripts can handle them in the appropriate manner.

Thanks.

**Comment by weedy** [comment]
I would like to have a different exit code for network based problems vs. out of space or other things.

**Comment by sergei-sh** [comment]
I have a big script which downloads hundreds of videos and also tracks which video is already downloaded, which no needs to being downloaded and log errors. Logging errors means automatically assigning error status after a try, not just reading console. So I need to distinguish between a) success b) no video on page c) video is present but page is not supported (error happened). Now I have to analyze each log contents.

**Comment by yan12125** [comment]
@sergei-sh Please go to #882 for future discussions. Exit codes sounds a possible feature for me, while this issue is already superseded by #882.

By the way, it's almost impossible to check whether there are videos or not. A common approach is introducing some heuristics, for example finding error strings in the web page. It should work in most cases but nobody can guarantee.

Anyway, #10308 should be resolved first - adding more exception classes to the code base.
