### ISSUE TITLE
Installationfolder of youtube-dl

### ISSUE THREAD

**Issue by muckl100** [rg3/youtube-dl#8549]
i startet youtube-dl on my desktop, but where did it install itself?

**Comment by dstftw** [comment]
Nowhere. If you're on Windows youtube-dl.exe is a portable standalone application that does not require installation.

**Comment by muckl100** [comment]
so when i download youtube-dl and run it directly after it, theres no installation? and how do i install it then?

**Comment by phihag** [comment]
Installation means unpacking and configuring files so that a software can be run. For the youtube-dl.exe on Windows, there is no installation required - you can just run it. If you want, move the file `youtube-dl.exe` to somewhere on your [PATH](https://en.wikipedia.org/wiki/PATH_(variable)) and create a [configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration), but that's all the installation possible, and neither is required.
