### ISSUE TITLE
ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by abderrahmane-tj** [rg3/youtube-dl#8944]
Love your work <3

error suggested i report this, i am not sure if this is the right place to do so but here we go :

Running Windows 8.1 64
using cmder

```
λ youtube-dl.exe -F https://www.youtube.com/watch?v=ZxRMAW4C9iw --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'https://www.youtube.com/watch?v=ZxRMAW4C9iw', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ZxRMAW4C9iw: Downloading webpage
[youtube] ZxRMAW4C9iw: Downloading video info webpage
[youtube] ZxRMAW4C9iw: Extracting video information
[youtube] {22} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {43} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {18} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {5} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {36} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {17} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {137} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {299} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {136} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {298} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {135} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {134} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {133} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {160} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] {140} signature length 40.43, html5 player en_US-vflpmpoFG
[youtube] ZxRMAW4C9iw: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflpmpoFG/base.js
[youtube] ZxRMAW4C9iw: Downloading MPD manifest
WARNING: [youtube] ZxRMAW4C9iw: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[info] Available formats for ZxRMAW4C9iw:
format code  extension  resolution note
140          m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k, 67.40MiB
160          mp4        256x144    144p  128k , avc1.4d400c, 30fps, video only, 59.16MiB
133          mp4        426x240    240p  262k , avc1.4d4015, 30fps, video only, 130.63MiB
134          mp4        640x360    360p  646k , avc1.4d401e, 30fps, video only, 299.49MiB
135          mp4        854x480    480p 1179k , avc1.4d401f, 30fps, video only, 569.11MiB
136          mp4        1280x720   720p 2375k , avc1.4d401f, 30fps, video only, 1.10GiB
298          mp4        1280x720   720p60 3510k , avc1.4d4020, 60fps, video only, 1.45GiB
137          mp4        1920x1080  1080p 4698k , avc1.640028, 30fps, video only, 2.07GiB
299          mp4        1920x1080  1080p60 6144k , avc1.64002a, 60fps, video only, 2.60GiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
5            flv        426x240    small , h263, mp3  @ 64k
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by KaelosBeren** [comment]
+1

Having this same issue on some videos.

**Comment by Tharyrok** [comment]
Hello, I encounter the same problems,
I stick my you debug.

`[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=abV7sNisXEE', u'--print-traffic', u'-v', u'--no-color', u'-s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.9 - Linux-4.4.0-0.bpo.1-amd64-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1
[debug] Proxy map: {}
[youtube] abV7sNisXEE: Downloading webpage
send: u'GET /watch?v=abV7sNisXEE&gl=US&hl=en&has_verified=1&bpctr=9999999999 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: www.youtube.com\r\nCookie: PREF=f1=50000000&hl=en\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 15 Apr 2016 15:50:50 GMT
header: Server: gwiseguy/2.0
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: text/html; charset=utf-8
header: Cache-Control: no-cache
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=604800
header: Set-Cookie: VISITOR_INFO1_LIVE=J-NWkUW0dHw; path=/; domain=.youtube.com; expires=Thu, 15-Dec-2016 03:43:50 GMT; httponly
header: Set-Cookie: YSC=WVr5LLB61cY; path=/; domain=.youtube.com; httponly
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] abV7sNisXEE: Downloading video info webpage
send: u'GET /get_video_info?&video_id=abV7sNisXEE&el=info&ps=default&eurl=&gl=US&hl=en HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: www.youtube.com\r\nCookie: YSC=WVr5LLB61cY; VISITOR_INFO1_LIVE=J-NWkUW0dHw; PREF=f1=50000000&hl=en; s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 15 Apr 2016 15:50:50 GMT
header: Server: gwiseguy/2.0
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: X-Content-Type-Options: nosniff
header: Strict-Transport-Security: max-age=604800
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: application/x-www-form-urlencoded
header: Content-Encoding: gzip
header: X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
header: Cache-Control: no-store
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] abV7sNisXEE: Extracting video information
[youtube] {22} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {43} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {18} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {5} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {36} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {17} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {137} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {248} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {299} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {303} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {136} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {247} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {298} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {302} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {135} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {244} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {134} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {243} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {133} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {242} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {160} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {278} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {140} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {171} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {249} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {250} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] {251} signature length 45.40, html5 player en_US-vflg4mKgv
[youtube] abV7sNisXEE: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflg4mKgv/base.js
send: u'GET /yts/jsbin/player-en_US-vflg4mKgv/base.js HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: s.ytimg.com\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Content-Type: text/javascript
header: Timing-Allow-Origin: https://www.youtube.com
header: Date: Thu, 14 Apr 2016 20:50:15 GMT
header: Expires: Fri, 22 Apr 2016 20:50:15 GMT
header: Last-Modified: Thu, 14 Apr 2016 19:46:22 GMT
header: X-Content-Type-Options: nosniff
header: Server: sffe
header: Content-Length: 394145
header: X-XSS-Protection: 1; mode=block
header: Cache-Control: public, max-age=691200
header: Age: 68436
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
header: Connection: close
[youtube] abV7sNisXEE: Downloading MPD manifest
send: u'GET /api/manifest/dash/fexp/9412913%2C9415327%2C9416126%2C9416891%2C9418643%2C9420452%2C9422596%2C9426926%2C9426985%2C9428398%2C9431865%2C9432044%2C9432750%2C9433628%2C9433776%2C9434746/ipbits/0/playback_host/r1---sn-5hne6n7e.googlevideo.com/ip/2001%3A913%3A1000%3A7000%3Ac82a%3A160c%3Ad0e2%3Aaa57/itag/0/key/yt6/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/id/o-AFJqwkO_SLbIgU2Qj-Q23_bHxsVOve4QDZQDp-Hj0B3V/sparams/as%2Cgcr%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/signature/EA844678C225827104196851298569C8B4C38181.16850F3D49B6F0101262B5F7AE52A1DD14103A5AA/upn/3gFbxMRFMcQ/nh/IgpwcjA0LmFtczE2KgkxMjcuMC4wLjE/hfr/1/expire/1460757050/source/youtube/mm/31/mn/sn-5hne6n7e/gcr/be/ms/au/mt/1460735258/mv/u/requiressl/yes/sver/3/pl/36 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: manifest.googlevideo.com\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Content-Type: text/html; charset=UTF-8
header: Date: Fri, 15 Apr 2016 15:50:51 GMT
header: Pragma: no-cache
header: Expires: Fri, 01 Jan 1990 00:00:00 GMT
header: Cache-Control: no-cache, must-revalidate
header: Server: HTTP server (unknown)
header: Content-Length: 2354
header: X-XSS-Protection: 1; mode=block
header: X-Frame-Options: SAMEORIGIN
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
header: Connection: close
WARNING: [youtube] abV7sNisXEE: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
`

**Comment by KonomiKitten** [comment]
Seeing this almost every day with select videos now, I've attached by verbose output of one of the videos showing this error.

[youtube-dl_2016.09.19_verbose.txt](https://github.com/rg3/youtube-dl/files/483940/youtube-dl_2016.09.19_verbose.txt)

**Comment by yan12125** [comment]
Confirmed that RbpCa0rhzIg has the same problem.

**Comment by VADemon** [comment]
Confirmed, ID: s9AwHypS1lg

`[youtube] s9AwHypS1lg: Downloading MPD manifest
WARNING: [youtube] s9AwHypS1lg: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError());`

[youtube-dl_2016.09.24_verbose_s9AwHypS1lg.txt](https://github.com/rg3/youtube-dl/files/491916/youtube-dl_2016.09.24_verbose_s9AwHypS1lg.txt)

**Comment by JamesTheAwesomeDude** [comment]
Getting this on `WiBwU2JjYz8` (purchased movie), and can confirm @VADemon's as well.

**Comment by heikobornholdt** [comment]
Getting this on every video from this user: https://www.youtube.com/user/ROCKETBEANSTV

**Comment by Giorgi** [comment]
Still getting this error in version 2017.5.26.0

**Comment by dstftw** [comment]
yt-dl.org/reporting
