### ISSUE TITLE
progresshook with download timestamp while using youtube-dl

### ISSUE THREAD

**Issue by ramadivyasri** [rg3/youtube-dl#9192]
Hi, Is there any provision to print the download progress along with appropriate timestamp?

**Comment by yan12125** [comment]
Could you give your expected sample output?

**Comment by ramadivyasri** [comment]
[youtube] PMFHQXxqYOg: Downloading webpage
[youtube] PMFHQXxqYOg: Downloading video info webpage
[youtube] PMFHQXxqYOg: Extracting video information
[youtube] PMFHQXxqYOg: Downloading MPD manifest
[info] Writing video description metadata as JSON to: Minions - The Competition (2015) - Animated Short HD-PMFHQXxqYOg.info.json
[download] Destination: Minions - The Competition (2015) - Animated Short HD-
[[download]   0.0% of 6.41MiB at  6.59KiB/s ETA 16:36 <EpochTimeStamp>
[[download]   0.0% of 6.41MiB at 19.48KiB/s ETA 05:36 < EpcohTimeStamp>
[[download]   0.1% of 6.41MiB at 44.79KiB/s ETA 02:26 < EpcohTimeStamp>
[[download]   0.2% of 6.41MiB at 94.66KiB/s ETA 01:09   < EpcohTimeStamp>
and so on....
I want to get the epoch time for each hook that is being generated and printed while download goes on. Can the dl print the progress hook with relevant timestamp?? If this feature does not exist, how can it be implemented??

**Comment by yan12125** [comment]
This is not implemented. You can modify the function [```FileDownloader.report_progress```](https://github.com/rg3/youtube-dl/blob/617e58d/youtube_dl/downloader/common.py#L239-L296) so that it displays timestamps. I can't make the change in official youtube-dl as many third party applications parse these lines to for progress reporting and adding an extra field is likely to break them.
