### ISSUE TITLE
Can't find youtube-dl.conf

### ISSUE THREAD

**Issue by Thor7** [rg3/youtube-dl#9389]
Hello...I'm a noob user of linux, I've been using Manjaro for a couple of days...I installed youtube-dl, but I can't find any file named youtube-dl.conf on the whole system.

**Comment by dstftw** [comment]
There is no such file by default you should create it yourself.

**Comment by Thor7** [comment]
I created one...but can't paste it in /etc/

**Comment by dstftw** [comment]
You need root access to paste into /etc.

**Comment by Thor7** [comment]
ok, thanks....you said that such a file is not there by default but I find it strange that in the manual it was phrased

> On Linux, the system wide configuration file is located at /etc/youtube-dl.conf and the user wide configuration file at ~/.config/youtube-dl/config. 

>

**Comment by dstftw** [comment]
"Located" does not necessarily imply created by default.

**Comment by Thor7** [comment]
actually it kind of does....someone should edit the manual,clearely stating that it needs to be created and it's not already there.

**Comment by Hrxn** [comment]
Well, think of it like that: In almost all cases, no matter what program, these config files do not exist by default, never.

**Comment by Thor7** [comment]
I'm a new linux user...I has no idea...btw...
1.MPV config file needs to be also created?
2.how do I display MPV video stats while playing a file?

**Comment by Hrxn** [comment]
1. Yes
2. Not sure what you mean. Something like this: https://github.com/Argon-/mpv-stats?

You need the script file from there. And yes, this file also needs to be put in the right place, manually.

**Comment by Thor7** [comment]
what settings do you use in your config file?could you share them please?

**Comment by Hrxn** [comment]
First of all, for reference, the full mpv manual is here: https://mpv.io/manual/master/

I use mpv primarily on Windows, so the configuration is a bit different, because you can't use all the options on other platforms in the same way.

If I use mpv on Linux, I only used the default configuration, to be honest.

The default/example `mpv.conf` is here: https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf
The default/example `input.conf` is here: https://github.com/mpv-player/mpv/blob/master/etc/input.conf

I basically use just some options like this:
```
no-osc
keep-open
geometry=50%:20%
on-top=yes
audio-file-auto=no
sub-auto=no
hwdec=no
```

**Comment by dstftw** [comment]
Continue any further offtopic discussions privately.
