### ISSUE TITLE
adding extra characters to the original file name 

### ISSUE THREAD

**Issue by adeebothman** [rg3/youtube-dl#9625]
after using youtube-dl -t {link} to download playlist from youtube 
it download file very well, but it adds extra characters to the file name like this one 
ex: this command
[ youtube-dl -t  https://www.youtube.com/playlist?list=PLAwxTw4SYaPnMwH5-FNkErnnq_aSy706S ]
 should download the first video with this title _"**Welcome to Developing Android Apps**"_
instead it downloaded with this one _" Welcome to Developing Android Apps-**2Wo_QfQZ0lE**.mp4"_

finally thank you for such a great tool it changed my life :+1: 
i hope we can figure the solution soon

**Comment by dstftw** [comment]
It's intentional. Use `-o "%(title)s.%(ext)s"`.

**Comment by adeebothman** [comment]
can you explain it to me please
i understand that i should replace (ext).s with (mp4).s , but (title)s with
what ? what should write in stead of title ?

**Comment by phihag** [comment]
The `-o` option specifies a *template* for the filename. It is not recommended to actually replace anything in there.

You're passing in the option `-t`, which is equivalent to `-o "%(title)s-%(id)s.%(ext)s"` (which is, coincidentally, also the default behavior). This makes the filename include the video ID, which is extremely useful if you want to find the original video URL in a pinch.

If you only want the title and extension (there are [lots of other fields too](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template)), pass in `-o "%(title)s.%(ext)s"` instead of `-t`.

If that's the behavior you want all the time, consider [creating a configuration file](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration).
