### ISSUE TITLE
Legal issues regarding youtube-dl

### ISSUE THREAD

**Issue by palikacska** [rg3/youtube-dl#9810]
Hi,

I was recently looking for an all-in-one solution that would allow me to search & play YouTube videos without even starting a browser to avoid using bloatware (Chrome instances eat up 300 MB if I open up the YouTube search page.. big shame of the 21st century).

I found Minitube and it wasn't that bad, but lacking a few basic features, like selecting output audio device and keyboard shortcuts, so I chose not to purchase and use it. One of the facts I read about made me raise my head. There was a discussion about a removed download feature of MiniTube. It used to be able to download videos, but Google lawyers might have done a great job threatening the author to remove the download capability. I'm just curious why can't they address youtube-dl to remove YouTube download feature for enabling people watch & download copyrighted videos without seeing advertisements and stuff.

Can all liability be excluded if it's an open-source / freeware product?

How does this work?

Best
Pál Ács

**Comment by phihag** [comment]
We are not lawyers, and thus cannot answer legal questions, especially those that do not specify which country's laws should be applied.

Pass in `--include-ads` to download advertisements as well.

**Comment by palikacska** [comment]
I don't think you would have to be a lawyer to answer my questions. I did not ask for a legal statement. I am just curious. A lot of YouTube downloading sites, applications, extensions, etc. getting _cease and desist_ letters to remove download capability. Haven't any of you got one of these? How would you react? Could an open-source app like this be killed by some megacorporation like Google? If I have to choose a country, let it be home country, Germany, where (as far as I know) it's prohibited to download copyrighted content and almost all music videos are inaccessible on YouTube.

**Comment by yan12125** [comment]
> Can all liability be excluded if it's an open-source / freeware product?

> Could an open-source app like this be killed by some megacorporation like Google?

Nobody knows. All maintainers/contributors try their best to solve existing problems and implement new features, while nothing is guaranteed.

---

By the way, here's a technical issue: ```--include-ads``` applies to Brightcove-based websites only.

**Comment by palikacska** [comment]
Doesn't fear from big copyright-enforcing recording companies keep you away from doing this work?

**Comment by yan12125** [comment]
No for me. But anyway it doesn't matter. As a technical project,  to fear or not to fear does not affect it's future.

**Comment by Hrxn** [comment]
> I don't think you would have to be a lawyer to answer my questions. I did not ask for a legal statement. I am just curious. [...]

There seems to be a slight misconception about copyright here. Copyright is a legal construct that grants exclusive rights to (re-)usage and (re-)distribution of original creative work to the holder, with certain limitations end exceptions, e.g. _fair use_ etc.
It's not obvious if or to which extent copyright applies here.

And since you mention Germany: No, it's not _per se_ prohibited to download copyrighted content, because the act itself of downloading content is something where copyright does not apply directly. There are some other laws, and there have been reforms over the last years that tried to tackle this "issue" a little bit, but they all focus on (technical) measures of protection or enforcement of copyright, and the legality to circumvent said measures, if present.
But downloading itself, no. There is another legal angle to this regarding the storage of copyrighted content, which complicates this matter, but this can't be seen as a complete substitute, the laws don't really overlap, and so the legal gray area still remains..

That many music videos are not available for German users of YouTube is an entirely different issue, please bear that in mind. This is the result of a longstanding and still ongoing legal battle between YouTube and a nice (sarcasm) German organization called GEMA (You can thank Joseph Goebbels for that). But the very same music videos are available on other sites, run by other companies (German companies in this case, actually), for example.

> Doesn't fear from big copyright-enforcing recording companies keep you away from doing this work?

Not sure where you see the problem here. As I said, this is somewhat of a legal gray area. This means that there is no clear-cut precedent which would settle these issues. And if you ask me, I think the reason that we don't see more litigation aiming in this direction carried out by some corporations (By the way, YouTube/Google for example is not the copyright holder in this whole scenario) is the fear of setting a new legal precedent, that may be unfavorable to the monetary interests of the corporations involved, if you catch my drift.

Oh, and before I forget it: Participation in an open-source project like this is another topic, there is no connection to possible or theoretical violations of copyright statutes from the project itself. If you crush your thumb with a hammer, do you think the manufacturer of the hammer is responsible?

**Comment by challarao** [comment]
One of the former contributors is at Google right now. That explains a lot :)
