### ISSUE TITLE
Allow Random Values for --sleep-interval

### ISSUE THREAD

**Issue by ap4125** [rg3/youtube-dl#9930]
The `--sleep-interval` option is great. I think that this is the main reason why we can run downloads from heavily monitored sites.

Is there a way to modify this option so that it can accept random values? For example, instead of setting it to `--sleep-interval 300` to set it to sleep for 300 seconds or 5 minutes between each download, make it like so:

`--sleep-interval 120-300`

so that the sleep interval would be set between 120 and 300 seconds.

The rationale is to simulate more realistic browsing behavior.

**Comment by shan3k** [comment]
Having a browse here to see what I could actually work on. 
Could we approach it like this?

`        sleep_interval = random.randrange(int(self.params.get('sleep_interval').split('-')[0]), int(self.params.get('sleep_interval').split('-')[1]))
`

I guess thats not ideal because we are taking a string as input and instead we should take two ints (and upper and a lower)? 

Maybe @yan12125 can provide feedback on my noob approach :+1:
